"""
sync.py — documentation synchronization layer
════════════════════════════════════════════════════════════════════
Sits strictly AFTER rendering. It never extracts anything from the backend
and never formats markdown — it only compares an already-rendered
{path: content} dict against whatever this tool previously wrote to
--output, then decides what to write, delete, or leave alone.

Rendering must be deterministic (same backend state -> same rendered text) for
this layer to mean anything; `--function check` proves it by rendering twice,
because springdoc's Page<T> property order once varied between JVM runs and
turned every review into noise. Given that, this layer never needs to diff
DTOs/permissions/validations/error-codes individually: any backend change
already shows up as a content difference in the relevant rendered file. Shared-doc granularity falls out of diffing
index.md's own "## " sections via _split_sections/_diff_sections.

Endpoint-level granularity works the SAME way, one level down: every group
(= controller) lives in one file, endpoints/<group-slug>.md, and every
endpoint inside it is its own "## {METHOD} {path}" section (see
markdown_renderer._endpoint_markdown). _split_sections() doesn't care
whether it's splitting index.md's shared sections or a group file's
endpoint sections — the same "^## " boundary applies either way, so
compare() reuses it for both, just building different change-record types
from the resulting {heading: body} dicts.

Because multiple endpoints now share one file, `file_path` on an
EndpointChange is no longer 1:1 with the endpoint — several changes can
point at the same group file. That's fine for reporting (format_report
notes when this happens), but it means apply()'s deletion pass must NOT key
off individual "removed" EndpointChanges (a group file that still has
surviving endpoints must never be deleted just because one endpoint inside
it went away) — it deletes a managed group file only when that whole group
is entirely absent from the current render. See apply()'s comment.

Every file this layer writes is stamped with MARKER as its first line. A
file only counts as "ours to manage" if it already starts with that exact
line — anything else on disk (hand-written docs, unrelated files) is never
overwritten or deleted, only reported as a conflict.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path

from models.api_doc_model import Endpoint
from renderers.markdown_renderer import group_file_paths

MARKER = "<!-- AUTO-GENERATED by api-doc-generator — do not edit manually -->"


def _is_managed(text: str) -> bool:
    return text.startswith(MARKER)


def _unstamp(text: str) -> str:
    if not _is_managed(text):
        return text
    return text[len(MARKER):].lstrip("\n")


def _stamp(content: str) -> str:
    return MARKER + "\n" + content


def endpoint_section_key(ep: Endpoint) -> str:
    """The '## ' heading text sync diffs this endpoint by within its group
    file — must exactly match _endpoint_markdown()'s H2 heading. Unique
    within a group file because Spring won't allow two operations with the
    same method+path in one app."""
    return f"{ep.method} {ep.path}"


def is_managed_output(output: Path) -> bool:
    index = output / "index.md"
    if not index.exists():
        return False
    try:
        return _is_managed(index.read_text(encoding="utf-8"))
    except OSError:
        return False


def detect_mode(output: Path) -> str:
    return "update" if is_managed_output(output) else "generate"


def read_existing(output: Path) -> dict[str, str]:
    """Every .md file currently under output, raw (marker included if present).
    Does not distinguish managed vs. unmanaged — compare() does that."""
    existing: dict[str, str] = {}
    if not output.exists():
        return existing
    for path in output.rglob("*.md"):
        existing[path.relative_to(output).as_posix()] = path.read_text(encoding="utf-8")
    return existing


@dataclass
class EndpointChange:
    method: str
    path: str
    label: str
    file_path: str
    status: str  # "added" | "removed" | "updated" | "unchanged"


@dataclass
class SharedSectionChange:
    name: str
    status: str  # "added" | "removed" | "changed" | "unchanged"


@dataclass
class Conflict:
    file_path: str
    reason: str


@dataclass
class SyncReport:
    mode: str
    endpoint_changes: list[EndpointChange] = field(default_factory=list)
    shared_changes: list[SharedSectionChange] = field(default_factory=list)
    conflicts: list[Conflict] = field(default_factory=list)

    def by_status(self, status: str) -> list[EndpointChange]:
        return [c for c in self.endpoint_changes if c.status == status]


def _split_sections(text: str) -> dict[str, str]:
    if not text:
        return {}
    parts = re.split(r"(?m)^## (.+)$", text)
    sections: dict[str, str] = {}
    preamble = parts[0].strip()
    if preamble:
        sections["Overview"] = preamble
    it = iter(parts[1:])
    for name, body in zip(it, it):
        sections[name.strip()] = body.strip()
    return sections


def _diff_sections(old_text: str, new_text: str) -> list[SharedSectionChange]:
    old_sections = _split_sections(old_text)
    new_sections = _split_sections(new_text)
    names = list(dict.fromkeys([*old_sections.keys(), *new_sections.keys()]))
    changes = []
    for name in names:
        old = old_sections.get(name)
        new = new_sections.get(name)
        if old is None:
            status = "added"
        elif new is None:
            status = "removed"
        elif old == new:
            status = "unchanged"
        else:
            status = "changed"
        changes.append(SharedSectionChange(name=name, status=status))
    return changes


def _removed_change(key: str, path: str) -> "EndpointChange":
    method, _, ep_path = key.partition(" ")
    label = f"{key} (no longer present in the backend)"
    return EndpointChange(method, ep_path, label, path, "removed")


def compare(
    existing: dict[str, str],
    new_files: dict[str, str],
    endpoints: list[Endpoint],
    mode: str,
) -> SyncReport:
    managed = {p: _unstamp(c) for p, c in existing.items() if _is_managed(c)}
    unmanaged = {p for p, c in existing.items() if not _is_managed(c)}

    report = SyncReport(mode=mode)

    groups: dict[str, list[Endpoint]] = {}
    for ep in endpoints:
        groups.setdefault(ep.group or "Ungrouped", []).append(ep)

    group_files = group_file_paths(list(groups))

    for group, group_endpoints in groups.items():
        path = group_files[group]
        if path in unmanaged:
            # Whole group is a conflict — matches how an unmanaged index.md
            # is handled below: report once, touch nothing.
            report.conflicts.append(
                Conflict(path, f"unmanaged file already exists at this path; "
                                f"{len(group_endpoints)} endpoint(s) left undocumented here")
            )
            continue

        old_sections = _split_sections(managed.get(path, ""))
        new_sections = _split_sections(new_files.get(path, ""))
        by_key = {endpoint_section_key(ep): ep for ep in group_endpoints}

        for key, ep in by_key.items():
            old = old_sections.get(key)
            new = new_sections.get(key)
            if old is None:
                status = "added"
            elif old == new:
                status = "unchanged"
            else:
                status = "updated"
            report.endpoint_changes.append(EndpointChange(ep.method, ep.path, key, path, status))

        # Endpoint-level removal: heading existed in this group's old
        # rendered sections but the group survives with other endpoints.
        for key in old_sections:
            if key == "Overview" or key in by_key:
                continue
            report.endpoint_changes.append(_removed_change(key, path))

    # Group-level removal: a previously-managed group file whose group has
    # zero endpoints left in the current render at all (file itself is gone).
    new_group_paths = set(group_files.values())
    for path, old_text in managed.items():
        if not path.startswith("endpoints/") or path in new_group_paths:
            continue
        for key in _split_sections(old_text):
            if key == "Overview":
                continue
            report.endpoint_changes.append(_removed_change(key, path))

    if "index.md" in unmanaged:
        report.conflicts.append(Conflict("index.md", "unmanaged index.md already exists; shared docs left untouched"))
    else:
        report.shared_changes = _diff_sections(managed.get("index.md", ""), new_files.get("index.md", ""))

    return report


def apply(
    output: Path,
    existing: dict[str, str],
    new_files: dict[str, str],
    report: SyncReport,
) -> tuple[list[str], list[str]]:
    """Writes only added/updated files, deletes only group files this run
    knows to be entirely gone, and never touches unmanaged (conflicting)
    paths.

    Deletion is intentionally NOT driven by report.by_status("removed"):
    since several endpoints can share one group file, a "removed"
    EndpointChange's file_path may be a group file that other, surviving
    endpoints still live in (and that this same apply() call just
    rewrote via the write loop above). Deleting it would destroy those
    survivors. So deletion instead compares the managed path set against
    new_files directly — a group file is deleted only when its path is
    entirely absent from the fresh render, i.e. the whole group is gone."""
    managed = {p: _unstamp(c) for p, c in existing.items() if _is_managed(c)}
    unmanaged = {p for p, c in existing.items() if not _is_managed(c)}

    written: list[str] = []
    for path, content in new_files.items():
        if path in unmanaged:
            continue
        if managed.get(path) == content:
            continue
        target = output / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_stamp(content), encoding="utf-8")
        written.append(path)

    deleted: list[str] = []
    for path in managed:
        if not path.startswith("endpoints/") or path in unmanaged or path in new_files:
            continue
        target = output / path
        if target.exists():
            target.unlink()
            deleted.append(path)

    return written, deleted


def write_all(output: Path, new_files: dict[str, str]) -> None:
    """Generate mode: write everything, stamped, unconditionally."""
    for path, content in new_files.items():
        target = output / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(_stamp(content), encoding="utf-8")


def _shared_file_note(entries: list[EndpointChange]) -> list[str]:
    """After a status group's per-endpoint lines, note once per group file
    when 2+ of those changes landed in the same file — grouping storage
    (endpoints/<group-slug>.md) must never collapse the existing granular
    added/removed/updated/unchanged listing, just make the shared file
    visible alongside it."""
    counts: dict[str, int] = {}
    for c in entries:
        counts[c.file_path] = counts.get(c.file_path, 0) + 1
    notes = []
    for path, count in counts.items():
        if count > 1:
            word = "both" if count == 2 else f"all {count}"
            notes.append(f"  ({word} in {path})")
    return notes


def format_report(report: SyncReport) -> str:
    added = report.by_status("added")
    removed = report.by_status("removed")
    updated = report.by_status("updated")
    unchanged = report.by_status("unchanged")

    lines = [f"Mode        : {report.mode.capitalize()}"]

    lines.append(f"Added       : {len(added)}")
    for c in added:
        lines.append(f"  + {c.label}")
    lines += _shared_file_note(added)
    lines.append(f"Removed     : {len(removed)}")
    for c in removed:
        lines.append(f"  - {c.label}")
    lines += _shared_file_note(removed)
    lines.append(f"Updated     : {len(updated)}")
    for c in updated:
        lines.append(f"  ~ {c.label}")
    lines += _shared_file_note(updated)
    lines.append(f"Unchanged   : {len(unchanged)}")

    changed_sections = [s for s in report.shared_changes if s.status != "unchanged"]
    if changed_sections:
        lines.append("Shared docs : " + ", ".join(f"{s.name} ({s.status})" for s in changed_sections))
    else:
        lines.append("Shared docs : unchanged")

    if report.conflicts:
        lines.append(f"Conflicts   : {len(report.conflicts)} (left untouched, not regenerated)")
        for c in report.conflicts:
            lines.append(f"  ! {c.file_path}: {c.reason}")

    return "\n".join(lines)
