#!/usr/bin/env python3
# Intended for Dev/Test environments only.
"""
api-verify — Post-Implementation API Verification Script for the FILE module.

Generated by the `api-verify` skill (.claude/skills/api-verify/SKILL.md), Full tier.
Translation, not derivation: every path, payload value, error code and dependency edge
below is traceable to one of the inputs named here. Nothing is invented.

Inputs translated:
  - governance/modules/FILE/api-docs/index.md + endpoints/*.md
        -> 12 endpoints, request/response field tables, Known Error Codes table
  - governance/modules/FILE/P3_5_BE/test-execution-manifest.md
        -> DEPENDENCY ORDER (stage B), RULE -> ERR -> TC triples (stage C),
           ENTITY CRUD CHECKLIST
  - governance/modules/FILE/P3_5_BE/backend-test-plan.md   (TC-BE-FILE-001..020)
  - governance/api-verify-config.md                        (stack conventions)

Run: python test_file_apis.py [BASE_URL]
  BASE_URL defaults to env ERP_BASE_URL, else http://localhost:7272.
  The staff login uses the PLATFORM tenant's bootstrap administrator; its password is read from
  env ERP_BOOTSTRAP_ADMIN_PASSWORD (never hard-coded, never written to any output).

Adapted 2026-10-05 to erp-core 1.2.0 (newback main). Every adapted spot carries a
`# erp-core 1.2.0: <change> — <reference>` comment; the classification of every baseline failure
is embedded in the generated file_problems_report.md (see BASELINE / CLASSIFICATION below).
"""

from __future__ import annotations

import json
import os
import secrets
import string
import sys
import time
import zlib
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Optional

import requests

# erp-core 1.2.0: base URL from env ERP_BASE_URL (legacy-suite convention; argv[1] still wins).
BASE_URL = os.environ.get("ERP_BASE_URL", "http://localhost:7272").rstrip("/")
# erp-core 1.2.0: the seeded `admin` no longer has the password `admin` — it is seeded PENDING with
# a placeholder hash and activated with ERP_BOOTSTRAP_ADMIN_PASSWORD at startup — DEVIATIONS [04]
# (Task 2 / admin password); the hard-coded admin/admin credential is removed.
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD_ENV = "ERP_BOOTSTRAP_ADMIN_PASSWORD"
# erp-core 1.2.0: every staff login names its tenant with the X-Tenant-Code header (400
# TENANT_REQUIRED otherwise); the bootstrap admin lives in PLATFORM — DEVIATIONS [05]
# (resolution rule (3); existing tests: the smoke test logs in with X-Tenant-Code: PLATFORM).
TENANT_CODE = "PLATFORM"
# Password of the run-scoped unprivileged staff user of TC-BE-FILE-019's permission half:
# generated at random per run (never hard-coded, never printed), with upper, lower, digit and
# symbol characters so it meets any password policy the target applies.
NOPERM_PASSWORD = ("Aa1!" + secrets.token_urlsafe(16) + "".join(
    secrets.choice(string.ascii_uppercase + string.digits) for _ in range(4)))

# Run-scoped suffix. FILE exposes no hard-delete endpoint for either entity (ENTITY CRUD
# CHECKLIST: FileCategory deactivate = flag, FileDocument = soft status=DELETED), so rows
# from a prior run persist and would collide on FILE_CATEGORY's unique code. Sibling runs
# (CU, NOTIF) share this database, so nothing below asserts on a global count or on "the
# first row returned" — only on values this run created.
RUN_ID = str(int(time.time()))[-6:]

# Owner triple — api-docs Example values (ownerType=PURCHASE_ORDER, moduleCode=PROC),
# with a run-scoped ownerId so list-by-owner only ever sees this run's own rows.
OWNER_ID = 900000 + int(RUN_ID) % 90000
OWNER_TYPE = "PURCHASE_ORDER"
MODULE_CODE = "PROC"

# Size constants are read from the module's own configured limits, not assumed:
#   FileValidationDomainService.DEFAULT_MAX_CONTENT_BYTES = 5 MB  (RULE-FILE-001)
#   FileValidationDomainService.MAX_REQUEST_BYTES         = 10 MB (RULE-FILE-001)
#   spring.servlet.multipart.max-file-size                = 15 MB (application.properties)
DEFAULT_MAX_CONTENT_BYTES = 5 * 1024 * 1024
UNDER_LIMIT_BYTES = 2 * 1024 * 1024        # TC-BE-FILE-001 "2MB file"
OVER_LIMIT_BYTES = 6 * 1024 * 1024         # TC-BE-FILE-002 "6MB file (> 5MB)"

# Lookup keys FILE fronts (FileLookupService LOOKUP_FILE_TYPE / LOOKUP_FILE_STATUS,
# api-docs API-FILE-008). Values are owned by MDL — a real cross-module edge (XM).
LOOKUP_FILE_TYPE = "FILE_FILE_TYPE"
LOOKUP_FILE_STATUS = "FILE_FILE_STATUS"

# ══════════════════════════════════════════════════════════════════
# Result plumbing
# ══════════════════════════════════════════════════════════════════


@dataclass
class TestResult:
    name: str
    passed: bool
    detail: str
    response_snippet: str = ""


@dataclass
class TestSuite:
    entity: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.passed)


@dataclass
class Observation:
    name: str
    detail: str
    response_snippet: str = ""


SUITES: list[TestSuite] = []
OBSERVATIONS: list[Observation] = []
PRECONDITION_FAILURES: list[str] = []
GAPS: list[str] = []
_current_suite: Optional[TestSuite] = None


def start_suite(entity: str) -> TestSuite:
    global _current_suite
    s = TestSuite(entity=entity)
    SUITES.append(s)
    _current_suite = s
    print(f"\n=== {entity} ===")
    return s


def run(name: str, fn):
    """Executes fn(); records pass/fail. fn returns (bool, detail, snippet)."""
    assert _current_suite is not None, "run() called before start_suite()"
    try:
        ok, detail, snip = fn()
    except AssertionError as e:
        ok, detail, snip = False, f"AssertionError: {e}", ""
    except Exception as e:  # noqa: BLE001
        ok, detail, snip = False, f"EXCEPTION: {type(e).__name__}: {e}", ""
    r = TestResult(name=name, passed=ok, detail=detail, response_snippet=snip)
    _current_suite.results.append(r)
    print(f"  [{'PASS' if ok else 'FAIL'}] {name} — {detail}")
    return r


def run_observation(name: str, fn):
    """Stage E — outcome not governed by a RULE + code. Never affects totals."""
    try:
        _, detail, snip = fn()
    except Exception as e:  # noqa: BLE001
        detail, snip = f"EXCEPTION: {type(e).__name__}: {e}", ""
    o = Observation(name=name, detail=detail, response_snippet=snip)
    OBSERVATIONS.append(o)
    print(f"  [OBS ] {name} — {detail}")
    return o


def blocked(name: str, why: str):
    """Records a test that could not run because a precondition failed."""
    assert _current_suite is not None
    r = TestResult(name=name, passed=False, detail=f"BLOCKED-ON-PRECONDITION: {why}")
    _current_suite.results.append(r)
    print(f"  [BLK ] {name} — {why}")
    return r


# ══════════════════════════════════════════════════════════════════
# API client — ApiResponse<T> envelope per api-verify-config.md §3.
# FILE needs two extensions the FIN precedent's JSON-only client lacks:
#   - upload is multipart/form-data (POST /api/v1/files)
#   - download returns a raw byte stream, NOT the ApiResponse envelope
# ══════════════════════════════════════════════════════════════════


class APIClient:
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.token: Optional[str] = None
        self.session = requests.Session()

    def _headers(self, token: Optional[str] = None, lang: Optional[str] = None,
                 json_body: bool = True) -> dict:
        h = {"Content-Type": "application/json"} if json_body else {}
        tok = token if token is not None else self.token
        if tok:
            h["Authorization"] = f"Bearer {tok}"
        if lang:
            h["Accept-Language"] = lang
        return h

    def _make(self, method, path, json_body=None, params=None, token=None,
              lang=None, timeout=60):
        return self.session.request(
            method, f"{self.base_url}{path}", json=json_body, params=params,
            headers=self._headers(token, lang), timeout=timeout,
        )

    def get(self, path, params=None, token=None, lang=None):
        return self._make("GET", path, params=params, token=token, lang=lang)

    def post(self, path, json_body=None, token=None, lang=None):
        return self._make("POST", path, json_body=json_body, token=token, lang=lang)

    def put(self, path, json_body=None, token=None, lang=None):
        return self._make("PUT", path, json_body=json_body, token=token, lang=lang)

    def delete(self, path, params=None, token=None):
        return self._make("DELETE", path, params=params, token=token)

    def upload(self, content: bytes, file_name: str, form: dict,
               token: Optional[str] = None, omit_auth: bool = False):
        """POST /api/v1/files — multipart/form-data.

        Part names come from the implementation contract the api-docs describe:
        `file` (the binary part) plus the UploadRequest fields. The docs render the
        metadata as a nested `request` object; the controller binds it with
        @ModelAttribute, i.e. FLAT form fields. Both spellings are exercised — the
        flat one asserted, the documented nested one recorded as an observation.
        """
        files = {"file": (file_name, content, "application/octet-stream")}
        data = {k: str(v) for k, v in form.items() if v is not None}
        headers = {} if omit_auth else self._headers(token, json_body=False)
        return self.session.post(f"{self.base_url}/api/v1/files",
                                 files=files, data=data, headers=headers, timeout=120)

    def download(self, token_value: str, token: Optional[str] = None):
        """GET /api/v1/files/download?token= — raw byte stream, no envelope."""
        return self.session.get(f"{self.base_url}/api/v1/files/download",
                                params={"token": token_value},
                                headers=self._headers(token, json_body=False), timeout=60)

    def login(self, username: str, password: str,
              tenant_code: str = TENANT_CODE) -> Optional[str]:
        # erp-core 1.2.0: login must carry X-Tenant-Code (TenantResolutionFilter) — DEVIATIONS [05].
        # The token's `tid` claim then carries the tenant, so no other call needs the header.
        r = self.session.post(f"{self.base_url}/api/v1/sec/auth/login",
                              json={"username": username, "password": password},
                              headers={"Content-Type": "application/json",
                                       "X-Tenant-Code": tenant_code},
                              timeout=60)
        if r.status_code == 200:
            return ((r.json().get("data")) or {}).get("accessToken")
        return None


def data_of(resp) -> Any:
    try:
        return resp.json().get("data")
    except Exception:  # noqa: BLE001
        return None


def field_of(resp, key) -> Any:
    d = data_of(resp)
    return d.get(key) if isinstance(d, dict) else None


def err_code(resp) -> Optional[str]:
    try:
        return (resp.json().get("error") or {}).get("code")
    except Exception:  # noqa: BLE001
        return None


def snippet(resp, limit: int = 300) -> str:
    ctype = resp.headers.get("Content-Type", "")
    if "json" not in ctype:
        return f"<{len(resp.content)} bytes, Content-Type={ctype}>"
    try:
        return json.dumps(resp.json(), ensure_ascii=False)[:limit]
    except Exception:  # noqa: BLE001
        return (resp.text or "")[:limit]


def expect_status(resp, want: int, what: str):
    return (resp.status_code == want,
            f"{what}: HTTP {resp.status_code} (want {want})", snippet(resp))


def expect_error(resp, want_status: int, want_code: str, what: str):
    got = err_code(resp)
    ok = resp.status_code == want_status and got == want_code
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got} (want {want_status}/{want_code})",
            snippet(resp))


def field_errors(resp) -> list:
    """The `error.fieldErrors` array of the platform validation envelope (may be absent/null)."""
    try:
        return (resp.json().get("error") or {}).get("fieldErrors") or []
    except Exception:  # noqa: BLE001
        return []


def expect_validation_field(resp, want_field: str, what: str):
    """Assert the platform's deliberate bean-validation refusal: HTTP 400, wire code
    `VALIDATION_ERROR`, and a `fieldErrors` entry naming `want_field`.

    This is GlobalExceptionHandler.handleValidation's documented shape. Asserting the field
    name (not just the status) is what keeps such a test meaningful: it still proves the rule
    is enforced AND on which field, which the generic per-module business code cannot express
    because it carries no per-field detail and reports only one failure at a time.
    """
    got = err_code(resp)
    fields = [fe.get("field") for fe in field_errors(resp)]
    ok = (resp.status_code == 400
          and got == "VALIDATION_ERROR"
          and want_field in fields)
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got}, fieldErrors={fields} "
            f"(want 400/VALIDATION_ERROR naming '{want_field}')",
            snippet(resp))


# ══════════════════════════════════════════════════════════════════
# Test payload bytes — generated in-memory, never read from disk
# ══════════════════════════════════════════════════════════════════


def png_bytes(payload_len: int = 0) -> bytes:
    """A real 1x1 PNG (valid magic bytes, so server-side content sniffing detects
    image/png), optionally padded with a trailing ancillary chunk to reach a size."""

    def chunk(ctype: bytes, body: bytes) -> bytes:
        return (len(body).to_bytes(4, "big") + ctype + body
                + zlib.crc32(ctype + body).to_bytes(4, "big"))

    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = chunk(b"IHDR", (1).to_bytes(4, "big") + (1).to_bytes(4, "big")
                 + bytes([8, 2, 0, 0, 0]))
    idat = chunk(b"IDAT", zlib.compress(b"\x00\xff\xff\xff"))
    iend = chunk(b"IEND", b"")
    out = sig + ihdr + idat + iend
    if payload_len > len(out):
        pad = payload_len - len(out)
        # tEXt is an ancillary chunk: padding does not invalidate the PNG.
        out = sig + ihdr + chunk(b"tEXt", b"pad\x00" + b"A" * max(pad - 16, 0)) + idat + iend
    return out


def exe_bytes(size: int = 4096) -> bytes:
    """A DOS/PE executable header — TC-BE-FILE-004's ".exe disguised as image"."""
    return b"MZ\x90\x00\x03\x00\x00\x00\x04\x00\x00\x00\xff\xff\x00\x00" + b"\x00" * (size - 16)


def text_bytes(size: int) -> bytes:
    """Exactly `size` bytes of plain text — the length is asserted against the
    server-recorded fileSize, so it must be exact, not approximate."""
    seed = ("api-verify FILE run " + RUN_ID + " ").encode()
    return (seed * (size // len(seed) + 1))[:size]


# ══════════════════════════════════════════════════════════════════
# Stage F — created-entity tracking
# ══════════════════════════════════════════════════════════════════

created: dict[str, list] = {
    "FileCategory": [],
    "FileDocument": [],
    "SecUser": [],      # erp-core 1.2.0: TC-BE-FILE-019's unprivileged fixture user
}

LEFT_BEHIND: list[str] = []
PERMANENT_RESIDUE: list[str] = []

# Shared context threaded between suites (FK ids, never hard-coded).
ctx: dict[str, Any] = {}


# ══════════════════════════════════════════════════════════════════
# Stage I — permission preconditions
# ══════════════════════════════════════════════════════════════════


def grants(c: APIClient):
    """Stage I — no grant is needed.

    FILE permissions are enforced (`PERM_FILE_CATEGORIES_*`, `PERM_FILE_BROWSER_*`): the
    @PreAuthorize checks were already live before erp-core (newback initial commit a9ed097), so
    the legacy "SEC-PENDING, nothing enforced" premise was stale; in 1.2.0 they are code-defined
    by `FilePermissions` (P1/srs.md addendum §4). erp-core 1.2.0: super role — DEVIATIONS [06].
    The run authenticates as the
    PLATFORM bootstrap `admin`, whose SYS_ADMIN is a super role holding every active catalog
    authority, so nothing has to be granted. No grant is created, so no journal entry is written
    and no privilege is left standing. The unprivileged user of TC-BE-FILE-019 is created with NO
    role at all (see test_auth_delegation) and is deactivated by cleanup.
    """
    return


# ══════════════════════════════════════════════════════════════════
# Stage A0 — preconditions
# ══════════════════════════════════════════════════════════════════


def preflight(c: APIClient):
    """Stage A0 — the externally-owned values this run's payloads and assertions
    reference are the LOV codes FILE fronts from MDL (XM edge: FileLookupService ->
    MdlLookupApi). Order is grants -> preconditions -> suites; this run needs no grant."""
    start_suite("PREFLIGHT (stage A0)")

    def check(key, wanted):
        def _fn():
            r = c.get(f"/api/v1/files/lookups/{key}")
            vals = data_of(r) or []
            codes = [v.get("code") for v in vals] if isinstance(vals, list) else []
            ctx[f"lookup_{key}"] = codes
            missing = [w for w in wanted if w not in codes]
            if missing or r.status_code != 200:
                PRECONDITION_FAILURES.append(
                    f"{key}: HTTP {r.status_code}, missing active value(s) {missing} — "
                    f"FILE's own api-docs / lifecycle assertions reference them")
            return (r.status_code == 200 and not missing,
                    f"{key}: HTTP {r.status_code}, {len(codes)} active value(s); "
                    f"missing={missing or 'none'}",
                    ",".join(codes))
        return _fn

    # LOV-FILE-001 buckets referenced by the upload response assertions (api-docs
    # FileMetadataResponse examples: fileTypeId=DOCUMENT, and IMAGE for the PNG case).
    run(f"XM — MDL-owned lookup '{LOOKUP_FILE_TYPE}' resolves through FILE (API-FILE-008)",
        check(LOOKUP_FILE_TYPE, ["DOCUMENT", "IMAGE"]))
    # LOV-FILE-002 statuses asserted by the lifecycle suite.
    run(f"XM — MDL-owned lookup '{LOOKUP_FILE_STATUS}' resolves through FILE (API-FILE-008)",
        check(LOOKUP_FILE_STATUS, ["ACTIVE", "ARCHIVED", "DELETED"]))

    # The owner triple is a plain polymorphic string set in FILE's own schema (no FK to
    # any registry), so there is no registry row to precondition-check. Recorded, not asserted.
    def owner_triple_unvalidated():
        r = c.get("/api/v1/files", params={"ownerId": OWNER_ID, "ownerType": OWNER_TYPE,
                                           "moduleCode": MODULE_CODE, "page": 0, "size": 5})
        total = (data_of(r) or {}).get("totalElements")
        return (True,
                f"owner triple ({OWNER_ID}/{OWNER_TYPE}/{MODULE_CODE}) readable: HTTP "
                f"{r.status_code}, totalElements={total} — moduleCode is an unconstrained "
                f"string here (no FK / registry validation on upload), so it is not a "
                f"precondition row", snippet(r))

    run_observation("stage A0 note — moduleCode/ownerType are unvalidated free strings",
                    owner_triple_unvalidated)


# ══════════════════════════════════════════════════════════════════
# 1. FileCategory  (manifest DEPENDENCY ORDER #1 — parent, independent)
# ══════════════════════════════════════════════════════════════════


def test_file_category(c: APIClient):
    """Covers: API-FILE-007 (categories CRUD) ;
    Negative: RULE-FILE-007 / FILE_CATEGORY_CODE_DUPLICATE / TC-BE-FILE-012,
              (PLATFORM) / FILE_CATEGORY_NOT_FOUND / TC-BE-FILE-016 (404 path)
    TC-BE-FILE-011, 012, 019"""
    start_suite("FileCategory")

    # api-docs Example categoryCode is CONTRACTS; a run-scoped suffix is appended for
    # uniqueness only — the business value itself comes from the doc.
    code = f"CONTRACTS_{RUN_ID}"
    ctx["category_code"] = code

    def create():
        r = c.post("/api/v1/files/categories",
                   {"categoryCode": code, "nameAr": "العقود", "nameEn": "Contracts",
                    "maxSizeBytes": 10485760,
                    "allowedContentTypes": "application/pdf,image/png",
                    "isActiveFl": True})
        if r.status_code in (200, 201):
            ctx["category_id"] = field_of(r, "id")
            created["FileCategory"].append(ctx["category_id"])
        return (r.status_code in (200, 201),
                f"HTTP {r.status_code}, id={ctx.get('category_id')}", snippet(r))

    run("TC-BE-FILE-011 — create a category with a new categoryCode (API-FILE-007)", create)

    run("TC-BE-FILE-012 — duplicate categoryCode rejected "
        "(RULE-FILE-007 / FILE_CATEGORY_CODE_DUPLICATE / 409)",
        lambda: expect_error(
            c.post("/api/v1/files/categories",
                   {"categoryCode": code, "nameAr": "مكرر", "nameEn": "Duplicate"}),
            409, "FILE_CATEGORY_CODE_DUPLICATE", "duplicate categoryCode"))

    cid = ctx.get("category_id")
    if cid:
        def get_by_id():
            r = c.get(f"/api/v1/files/categories/{cid}")
            ok = r.status_code == 200 and field_of(r, "categoryCode") == code
            return ok, f"HTTP {r.status_code}, categoryCode={field_of(r, 'categoryCode')}", snippet(r)

        run("TC-BE-FILE-019 — get category by id returns this run's own row", get_by_id)

        def update():
            r = c.put(f"/api/v1/files/categories/{cid}",
                      {"nameAr": "العقود", "nameEn": "Contracts updated",
                       "maxSizeBytes": 10485760,
                       "allowedContentTypes": "application/pdf,image/png"})
            ok = r.status_code == 200 and field_of(r, "nameEn") == "Contracts updated"
            return ok, f"HTTP {r.status_code}, nameEn={field_of(r, 'nameEn')}", snippet(r)

        run("TC-BE-FILE-019 — update category (PUT /categories/{id})", update)
    else:
        blocked("TC-BE-FILE-019 — category get/update", "category create failed")

    run("TC-BE-FILE-016 — unknown category id 404s (FILE_CATEGORY_NOT_FOUND)",
        lambda: expect_error(c.get("/api/v1/files/categories/99999999"),
                             404, "FILE_CATEGORY_NOT_FOUND", "get unknown category"))

    def search_own():
        r = c.post("/api/v1/files/categories/search",
                   {"filters": [{"field": "categoryCode", "operator": "EQUALS", "value": code}],
                    "page": 0, "size": 20})
        page = data_of(r) or {}
        rows = page.get("content") or []
        mine = [x for x in rows if x.get("categoryCode") == code]
        ok = r.status_code == 200 and len(mine) == 1
        return (ok,
                f"HTTP {r.status_code}, rows matching this run's own code={len(mine)} "
                f"(totalElements={page.get('totalElements')})", snippet(r))

    run("TC-BE-FILE-019 — search categories filtered to this run's own code (API-FILE-007)",
        search_own)

    # A category restricted to image/png only — used by the content-type suite.
    def create_image_category():
        img_code = f"IMAGES_{RUN_ID}"
        r = c.post("/api/v1/files/categories",
                   {"categoryCode": img_code, "nameAr": "صور", "nameEn": "Images",
                    "maxSizeBytes": 10485760, "allowedContentTypes": "image/png",
                    "isActiveFl": True})
        if r.status_code in (200, 201):
            ctx["image_category_id"] = field_of(r, "id")
            ctx["image_category_code"] = img_code
            created["FileCategory"].append(ctx["image_category_id"])
        return (r.status_code in (200, 201),
                f"HTTP {r.status_code}, id={ctx.get('image_category_id')} "
                f"(allowedContentTypes=image/png)", snippet(r))

    run("TC-BE-FILE-011 — create an image/png-only category (per-category type override)",
        create_image_category)

    # A category deactivated on purpose, so the documented FILE_CATEGORY_INACTIVE path
    # (api-docs Known Error Codes, 422) can be exercised by the upload suite.
    def create_then_deactivate():
        dead_code = f"RETIRED_{RUN_ID}"
        r = c.post("/api/v1/files/categories",
                   {"categoryCode": dead_code, "nameAr": "ملغاة", "nameEn": "Retired",
                    "isActiveFl": True})
        if r.status_code not in (200, 201):
            return False, f"create failed HTTP {r.status_code}", snippet(r)
        dead_id = field_of(r, "id")
        ctx["inactive_category_id"] = dead_id
        created["FileCategory"].append(dead_id)
        d = c.delete(f"/api/v1/files/categories/{dead_id}")
        return (d.status_code == 204,
                f"deactivate HTTP {d.status_code} (want 204, api-docs DELETE = 204 No Content)",
                snippet(d))

    run("TC-BE-FILE-019 — DELETE /categories/{id} deactivates (soft) and returns 204",
        create_then_deactivate)

    # Stage E — an already-deactivated category deactivated again. No RULE/code governs
    # idempotency here, so this is observed, never asserted.
    def deactivate_twice():
        dead_id = ctx.get("inactive_category_id")
        if not dead_id:
            return True, "skipped — no deactivated category", ""
        r = c.delete(f"/api/v1/files/categories/{dead_id}")
        return (True,
                f"second DELETE on an already-inactive category -> HTTP {r.status_code} "
                f"/{err_code(r)} (no artifact states the expected outcome)", snippet(r))

    run_observation("stage E — deactivate an already-deactivated category (idempotency)",
                    deactivate_twice)

    # Stage E — there is no documented activate endpoint for FileCategory (ENTITY CRUD
    # CHECKLIST shows "(flag)" for both activate and deactivate; only DELETE exists).
    GAPS.append(
        "FileCategory has no documented activate endpoint (api-docs lists only "
        "GET/PUT/DELETE/POST/search), so the deactivate->activate round trip named in the "
        "ENTITY CRUD CHECKLIST cannot be exercised over HTTP; deactivated rows stay inactive.")


# ══════════════════════════════════════════════════════════════════
# 2. FileDocument — upload  (manifest DEPENDENCY ORDER #2)
# ══════════════════════════════════════════════════════════════════


def test_file_document_upload(c: APIClient):
    """Covers: API-FILE-001 (upload) ;
    Negative: RULE-FILE-001 / FILE_DOCUMENT_SIZE_EXCEEDED / TC-BE-FILE-002 / 413,
              RULE-FILE-002 / FILE_DOCUMENT_TYPE_NOT_ALLOWED / TC-BE-FILE-004 / 415,
              RULE-FILE-005 / FILE_DOCUMENT_OWNERSHIP_REQUIRED / TC-BE-FILE-009 / 400
    TC-BE-FILE-001, 002, 003, 004, 008, 009, 013"""
    start_suite("FileDocument — upload (API-FILE-001)")

    owner_form = {"ownerId": OWNER_ID, "ownerType": OWNER_TYPE, "moduleCode": MODULE_CODE}

    def upload_under_limit():
        r = c.upload(text_bytes(UNDER_LIMIT_BYTES), f"contract_{RUN_ID}.txt", owner_form)
        if r.status_code in (200, 201):
            fid = field_of(r, "id")
            ctx["file_id"] = fid
            ctx["file_size"] = field_of(r, "fileSize")
            created["FileDocument"].append(fid)
        status = field_of(r, "fileStatusId")
        ok = r.status_code == 201 and status == "ACTIVE"
        return (ok,
                f"HTTP {r.status_code} (want 201, ServiceResult Status.CREATED), "
                f"fileStatusId={status}, id={ctx.get('file_id')}, "
                f"fileSize={ctx.get('file_size')}", snippet(r))

    run("TC-BE-FILE-001/008/013 — upload a 2MB file within the 5MB default limit -> "
        "201, fileStatusId=ACTIVE", upload_under_limit)

    def no_bytes_in_response():
        r = c.get(f"/api/v1/files/{ctx.get('file_id')}")
        body = data_of(r) or {}
        leaked = [k for k in body if k.lower() in ("filecontent", "content", "bytes", "data")]
        return (r.status_code == 200 and not leaked,
                f"HTTP {r.status_code}, byte-bearing fields in the DTO: {leaked or 'none'}",
                snippet(r))

    run("TC-BE-FILE-013/016 — upload/metadata response carries no file bytes (DRV-003)",
        no_bytes_in_response)

    def upload_oversized():
        r = c.upload(text_bytes(OVER_LIMIT_BYTES), f"huge_{RUN_ID}.txt", owner_form)
        if r.status_code in (200, 201):     # should not happen; track so it is torn down
            created["FileDocument"].append(field_of(r, "id"))
        return expect_error(r, 413, "FILE_DOCUMENT_SIZE_EXCEEDED",
                            f"6MB upload against the 5MB default cap "
                            f"({DEFAULT_MAX_CONTENT_BYTES} bytes)")

    run("TC-BE-FILE-002 — oversized upload rejected "
        "(RULE-FILE-001 / FILE_DOCUMENT_SIZE_EXCEEDED / 413)", upload_oversized)

    img_cat = ctx.get("image_category_id")
    if img_cat:
        def upload_png():
            form = dict(owner_form, fileCategoryFk=img_cat)
            r = c.upload(png_bytes(), f"logo_{RUN_ID}.png", form)
            if r.status_code in (200, 201):
                ctx["png_file_id"] = field_of(r, "id")
                created["FileDocument"].append(ctx["png_file_id"])
            ctype = field_of(r, "contentType")
            ftype = field_of(r, "fileTypeId")
            ok = r.status_code == 201 and ctype == "image/png" and ftype == "IMAGE"
            return (ok,
                    f"HTTP {r.status_code}, contentType={ctype} (want image/png, "
                    f"server-detected), fileTypeId={ftype}", snippet(r))

        run("TC-BE-FILE-003 — PNG accepted by an image/png-only category; contentType "
            "auto-detected (RULE-FILE-002 happy)", upload_png)

        def upload_disguised_exe():
            form = dict(owner_form, fileCategoryFk=img_cat)
            r = c.upload(exe_bytes(), f"evil_{RUN_ID}.png", form)
            if r.status_code in (200, 201):
                created["FileDocument"].append(field_of(r, "id"))
            return expect_error(r, 415, "FILE_DOCUMENT_TYPE_NOT_ALLOWED",
                                "PE/EXE bytes named .png into an image/png-only category")

        run("TC-BE-FILE-004 — .exe disguised as .png rejected on server-side MIME detection "
            "(RULE-FILE-002 / FILE_DOCUMENT_TYPE_NOT_ALLOWED / 415)", upload_disguised_exe)
    else:
        blocked("TC-BE-FILE-003", "image/png-only category was not created")
        blocked("TC-BE-FILE-004", "image/png-only category was not created")

    # The governed code ERR-0004 `FILE_DOCUMENT_OWNERSHIP_REQUIRED` is UNREACHABLE over HTTP,
    # and deliberately so: UploadRequest.moduleCode carries @NotBlank, so Spring bean
    # validation refuses the multipart bind at the controller boundary before the domain
    # ownership guard — the throw site of ERR-0004 — is ever entered. The platform's documented
    # mechanism for that refusal is GlobalExceptionHandler.handleValidation: HTTP 400, wire code
    # VALIDATION_ERROR, and a per-field `fieldErrors` entry, which preserves detail the single
    # generic domain code cannot (WHICH ownership field is missing, and all of them at once).
    # Asserting the field name keeps RULE-FILE-005 proven: an upload must still declare its
    # owning module, and the refusal still names moduleCode.
    def upload_missing_module_code():
        r = c.upload(text_bytes(1024), f"noowner_{RUN_ID}.txt",
                     {"ownerId": OWNER_ID, "ownerType": OWNER_TYPE})  # moduleCode omitted
        if r.status_code in (200, 201):
            created["FileDocument"].append(field_of(r, "id"))
        return expect_validation_field(r, "moduleCode", "upload with moduleCode omitted")

    run("TC-BE-FILE-009 — upload without moduleCode rejected -> 400 VALIDATION_ERROR naming "
        "`moduleCode` (RULE-FILE-005; ERR-0004 FILE_DOCUMENT_OWNERSHIP_REQUIRED is "
        "structurally unreachable — @NotBlank refuses first)", upload_missing_module_code)

    # Stage E — the api-docs render the metadata as a NESTED `request` object
    # ("request.ownerId"); the controller binds @ModelAttribute, i.e. flat fields.
    # Which spelling the wire actually accepts is recorded, not asserted.
    def nested_form_spelling():
        r = c.upload(text_bytes(1024), f"nested_{RUN_ID}.txt",
                     {"request.ownerId": OWNER_ID, "request.ownerType": OWNER_TYPE,
                      "request.moduleCode": MODULE_CODE})
        if r.status_code in (200, 201):
            created["FileDocument"].append(field_of(r, "id"))
        return (True,
                f"documented nested spelling (request.ownerId/...) -> HTTP {r.status_code}"
                f"/{err_code(r)}; the flat spelling the controller binds is what succeeds",
                snippet(r))

    run_observation("stage E — api-docs show a nested `request.*` multipart spelling",
                    nested_form_spelling)

    # Stage E — an inactive category is a documented error code (FILE_CATEGORY_INACTIVE,
    # 422) but carries no RULE/TC triple in the manifest; asserted against the api-docs
    # error table, which is a documented source.
    dead = ctx.get("inactive_category_id")
    if dead:
        run("api-docs error table — upload into a deactivated category rejected "
            "(FILE_CATEGORY_INACTIVE / 422)",
            lambda: expect_error(
                c.upload(text_bytes(1024), f"dead_{RUN_ID}.txt",
                         dict(owner_form, fileCategoryFk=dead)),
                422, "FILE_CATEGORY_INACTIVE", "upload into a deactivated category"))

    run("api-docs error table — upload referencing an unknown category 404s "
        "(FILE_CATEGORY_NOT_FOUND)",
        lambda: expect_error(
            c.upload(text_bytes(1024), f"nocat_{RUN_ID}.txt",
                     dict(owner_form, fileCategoryFk=99999999)),
            404, "FILE_CATEGORY_NOT_FOUND", "upload with an unknown fileCategoryFk"))

    # TC-BE-FILE-020 (SQLi half) — a quoted SQL fragment as the file name must be stored
    # literally and must not disturb the database.
    def sqli_file_name():
        evil = "x' OR '1'='1"
        r = c.upload(text_bytes(1024), evil, owner_form)
        if r.status_code in (200, 201):
            fid = field_of(r, "id")
            created["FileDocument"].append(fid)
            m = c.get(f"/api/v1/files/{fid}")
            stored = field_of(m, "fileName")
            ok = stored == evil
            return (ok, f"stored fileName={stored!r} (want the literal {evil!r})", snippet(m))
        return False, f"upload HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run("TC-BE-FILE-020 — SQL-injection file name stored literally (MANDATORY-J-8)",
        sqli_file_name)

    def db_intact_after_sqli():
        r = c.get(f"/api/v1/files/lookups/{LOOKUP_FILE_TYPE}")
        n = len(data_of(r) or [])
        return (r.status_code == 200 and n == len(ctx.get(f"lookup_{LOOKUP_FILE_TYPE}") or []),
                f"lookups still resolve after the injection attempt: HTTP {r.status_code}, "
                f"{n} value(s)", snippet(r))

    run("TC-BE-FILE-020 — database intact after the injection attempt", db_intact_after_sqli)


# ══════════════════════════════════════════════════════════════════
# 3. FileDocument — metadata & list  (API-FILE-004 / API-FILE-005)
# ══════════════════════════════════════════════════════════════════


def test_file_document_read(c: APIClient):
    """Covers: API-FILE-004 (metadata), API-FILE-005 (list by owner) ;
    Negative: (PLATFORM) / FILE_DOCUMENT_NOT_FOUND / TC-BE-FILE-016 / 404
    TC-BE-FILE-016, 017"""
    start_suite("FileDocument — metadata & list")

    fid = ctx.get("file_id")
    if not fid:
        blocked("TC-BE-FILE-016/017", "no uploaded file")
        return

    def metadata():
        r = c.get(f"/api/v1/files/{fid}")
        d = data_of(r) or {}
        ok = (r.status_code == 200 and d.get("id") == fid
              and d.get("ownerId") == OWNER_ID and d.get("moduleCode") == MODULE_CODE)
        return ok, f"HTTP {r.status_code}, id={d.get('id')}, owner={d.get('ownerId')}", snippet(r)

    run("TC-BE-FILE-016 — metadata by id returns this run's own row (API-FILE-004)", metadata)

    run("TC-BE-FILE-016 — unknown file id 404s (FILE_DOCUMENT_NOT_FOUND)",
        lambda: expect_error(c.get("/api/v1/files/99999999"),
                             404, "FILE_DOCUMENT_NOT_FOUND", "metadata for an unknown id"))

    def list_by_owner():
        r = c.get("/api/v1/files", params={"ownerId": OWNER_ID, "ownerType": OWNER_TYPE,
                                           "moduleCode": MODULE_CODE, "page": 0, "size": 50})
        page = data_of(r) or {}
        rows = page.get("content") or []
        mine = [x for x in rows if x.get("id") == fid]
        leaked = [k for x in rows for k in x if k.lower() in ("filecontent", "content", "bytes")]
        ok = r.status_code == 200 and len(mine) == 1 and not leaked
        return (ok,
                f"HTTP {r.status_code}, this run's file present={len(mine)}, "
                f"rows={len(rows)}, byte fields leaked={leaked or 'none'}", snippet(r))

    run("TC-BE-FILE-017 — list by owner returns this run's rows, no bytes (API-FILE-005)",
        list_by_owner)

    def list_paging_envelope():
        r = c.get("/api/v1/files", params={"ownerId": OWNER_ID, "ownerType": OWNER_TYPE,
                                           "moduleCode": MODULE_CODE, "page": 0, "size": 5})
        page = data_of(r) or {}
        documented = ["totalPages", "totalElements", "numberOfElements", "first", "last",
                      "pageable", "sort", "size", "number", "empty", "content"]
        missing = [f for f in documented if f not in page]
        return (r.status_code == 200 and not missing,
                f"HTTP {r.status_code}, missing documented Page fields: {missing or 'none'}",
                snippet(r))

    run("TC-BE-FILE-017 — paging envelope carries the fields index.md documents",
        list_paging_envelope)

    def list_empty_owner():
        r = c.get("/api/v1/files", params={"ownerId": OWNER_ID + 12345,
                                           "ownerType": f"NOBODY_{RUN_ID}",
                                           "moduleCode": MODULE_CODE, "page": 0, "size": 20})
        page = data_of(r) or {}
        ok = r.status_code == 200 and (page.get("content") == [] or page.get("empty") is True)
        return ok, f"HTTP {r.status_code}, empty={page.get('empty')}, " \
                   f"totalElements={page.get('totalElements')}", snippet(r)

    run("TC-BE-FILE-017 — an owner with no files returns 200 empty page (MANDATORY-J-7)",
        list_empty_owner)


# ══════════════════════════════════════════════════════════════════
# 4. Access token & download  (API-FILE-002 / API-FILE-003)
# ══════════════════════════════════════════════════════════════════


def test_access_token_and_download(c: APIClient):
    """Covers: API-FILE-002 (issue token), API-FILE-003 (download) ;
    Negative: RULE-FILE-003 / FILE_ACCESS_TOKEN_INVALID / TC-BE-FILE-006 / 401
    TC-BE-FILE-005, 006, 014, 015"""
    start_suite("FileDocument — access token & download")

    fid = ctx.get("file_id")
    if not fid:
        blocked("TC-BE-FILE-005/006/014/015", "no uploaded file")
        return

    def issue():
        r = c.post(f"/api/v1/files/{fid}/access-token")
        d = data_of(r) or {}
        ctx["dl_token"] = d.get("accessToken")
        ok = r.status_code == 200 and bool(d.get("accessToken")) and bool(d.get("expiresAt"))
        return (ok,
                f"HTTP {r.status_code}, accessToken present={bool(d.get('accessToken'))}, "
                f"expiresAt={d.get('expiresAt')}", snippet(r))

    run("TC-BE-FILE-014 — issue a single-use access token -> 200 {accessToken, expiresAt} "
        "(API-FILE-002)", issue)

    tok = ctx.get("dl_token")
    if not tok:
        blocked("TC-BE-FILE-005/015/006", "no access token issued")
    else:
        def download_once():
            r = c.download(tok)
            length = len(r.content)
            disp = r.headers.get("Content-Disposition", "")
            # Compared against the fileSize the server itself recorded at upload
            # (api-docs FileMetadataResponse.fileSize), not against a local constant.
            want = ctx.get("file_size")
            ok = (r.status_code == 200 and length == want
                  and "attachment" in disp.lower())
            return (ok,
                    f"HTTP {r.status_code}, body={length} bytes (server-recorded "
                    f"fileSize={want}), Content-Type={r.headers.get('Content-Type')}, "
                    f"Content-Disposition={disp[:60]!r}", f"<{length} bytes>")

        run("TC-BE-FILE-005/015 — download with a fresh token -> 200 byte stream, "
            "size matches the upload (API-FILE-003)", download_once)

        def download_reused():
            r = c.download(tok)
            return expect_error(r, 401, "FILE_ACCESS_TOKEN_INVALID",
                                "the same token used a second time")

        run("TC-BE-FILE-006/015 — the SAME token reused is refused "
            "(RULE-FILE-003 / FILE_ACCESS_TOKEN_INVALID / 401) — single-use proven end-to-end",
            download_reused)

    run("TC-BE-FILE-006 — a forged/garbage token is refused (FILE_ACCESS_TOKEN_INVALID / 401)",
        lambda: expect_error(c.download(f"not-a-real-token-{RUN_ID}"),
                             401, "FILE_ACCESS_TOKEN_INVALID", "forged token"))

    run("TC-BE-FILE-016 — access token for an unknown file id 404s (FILE_DOCUMENT_NOT_FOUND)",
        lambda: expect_error(c.post("/api/v1/files/99999999/access-token"),
                             404, "FILE_DOCUMENT_NOT_FOUND", "token for an unknown file"))

    # Stage E — a second token issued while the first is unconsumed. No artifact states
    # whether issuing invalidates the previous grant, so this is observed only.
    def two_live_tokens():
        a = c.post(f"/api/v1/files/{fid}/access-token")
        b = c.post(f"/api/v1/files/{fid}/access-token")
        ta, tb = field_of(a, "accessToken"), field_of(b, "accessToken")
        if not (ta and tb):
            return True, "could not issue two tokens", ""
        r1 = c.download(ta)
        r2 = c.download(tb)
        return (True,
                f"two concurrently-issued tokens: first -> HTTP {r1.status_code}, "
                f"second -> HTTP {r2.status_code} (no artifact states whether issuing a new "
                f"token invalidates an unconsumed one)", "")

    run_observation("stage E — two access tokens issued for the same file", two_live_tokens)

    # TC-BE-FILE-006's expired half: TOKEN_TTL is 10 minutes (FileAccessTokenDomainService),
    # so an expiry test would idle the run for 10 minutes. The reuse half is exercised
    # for real above; expiry is declared a gap rather than faked.
    GAPS.append(
        "TC-BE-FILE-006 (expired half) — the access token TTL is 10 minutes "
        "(FileAccessTokenDomainService.TOKEN_TTL), so proving expiry needs a 10-minute idle "
        "wait inside the run. The REUSED half of the same TC is exercised end-to-end "
        "(issue -> download -> download again -> 401); expiry is NOT executed and is not "
        "claimed as passing.")


# ══════════════════════════════════════════════════════════════════
# 5. FileDocument — lifecycle  (API-FILE-006)
# ══════════════════════════════════════════════════════════════════


def test_file_document_lifecycle(c: APIClient):
    """Covers: API-FILE-006 (archive / soft-delete) ;
    Negative: FILE_DOCUMENT_INVALID_TRANSITION (api-docs error table, 422)
    TC-BE-FILE-010, 018"""
    start_suite("FileDocument — lifecycle (API-FILE-006)")

    owner_form = {"ownerId": OWNER_ID, "ownerType": OWNER_TYPE, "moduleCode": MODULE_CODE}

    def upload_for(label: str) -> Optional[int]:
        r = c.upload(text_bytes(UNDER_LIMIT_BYTES // 64), f"{label}_{RUN_ID}.txt", owner_form)
        if r.status_code in (200, 201):
            fid = field_of(r, "id")
            created["FileDocument"].append(fid)
            return fid
        return None

    # --- archive path (TC-BE-FILE-018) -------------------------------------------
    arch_id = upload_for("archive")
    if not arch_id:
        blocked("TC-BE-FILE-018", "could not upload a file to archive")
    else:
        ctx["archived_id"] = arch_id
        arch_size = field_of(c.get(f"/api/v1/files/{arch_id}"), "fileSize")

        def archive():
            r = c.delete(f"/api/v1/files/{arch_id}", params={"action": "ARCHIVE"})
            status = field_of(r, "fileStatusId")
            ok = r.status_code == 200 and status == "ARCHIVED"
            return ok, f"HTTP {r.status_code}, fileStatusId={status} (want ARCHIVED)", snippet(r)

        run("TC-BE-FILE-018 — archive -> 200, fileStatusId=ARCHIVED (API-FILE-006)", archive)

        def archived_bytes_still_served():
            t = c.post(f"/api/v1/files/{arch_id}/access-token")
            tv = field_of(t, "accessToken")
            if not tv:
                return (False,
                        f"could not issue a token for the archived file: HTTP "
                        f"{t.status_code}/{err_code(t)}", snippet(t))
            d = c.download(tv)
            ok = d.status_code == 200 and len(d.content) == arch_size
            return (ok,
                    f"download of the ARCHIVED file: HTTP {d.status_code}, "
                    f"{len(d.content)} bytes (metadata fileSize={arch_size})",
                    f"<{len(d.content)} bytes>")

        run("TC-BE-FILE-010 — archiving retains the bytes: the archived file still "
            "downloads byte-for-byte (documented read, not storage inspection)",
            archived_bytes_still_served)

    # --- soft-delete path (TC-BE-FILE-010) ---------------------------------------
    del_id = upload_for("softdelete")
    if not del_id:
        blocked("TC-BE-FILE-010 (DELETE half)", "could not upload a file to soft-delete")
        return
    ctx["deleted_id"] = del_id
    pre = c.get(f"/api/v1/files/{del_id}")
    pre_size = field_of(pre, "fileSize")

    def soft_delete():
        r = c.delete(f"/api/v1/files/{del_id}", params={"action": "DELETE"})
        status = field_of(r, "fileStatusId")
        ok = r.status_code == 200 and status == "DELETED"
        return ok, f"HTTP {r.status_code}, fileStatusId={status} (want DELETED)", snippet(r)

    run("TC-BE-FILE-010 — DELETE action=DELETE -> 200, fileStatusId=DELETED (soft)",
        soft_delete)

    def row_and_size_retained():
        r = c.get(f"/api/v1/files/{del_id}")
        size = field_of(r, "fileSize")
        ok = r.status_code == 200 and size == pre_size and size and size > 0
        return (ok,
                f"metadata after soft-delete: HTTP {r.status_code}, fileSize={size} "
                f"(before={pre_size}) — the row and its recorded byte length survive",
                snippet(r))

    run("TC-BE-FILE-010 — the soft-deleted row survives with its byte length intact "
        "(documented read)", row_and_size_retained)

    def deleted_not_downloadable():
        r = c.post(f"/api/v1/files/{del_id}/access-token")
        return (r.status_code == 404,
                f"access token for a DELETED file: HTTP {r.status_code}/{err_code(r)} — "
                f"a soft-deleted file is treated as gone, so the download route cannot "
                f"re-prove byte retention for this path", snippet(r))

    run_observation("stage E — a DELETED file's bytes cannot be re-read over HTTP",
                    deleted_not_downloadable)

    run("api-docs error table — DELETED is terminal; a further transition is refused "
        "(FILE_DOCUMENT_INVALID_TRANSITION / 422)",
        lambda: expect_error(c.delete(f"/api/v1/files/{del_id}", params={"action": "ARCHIVE"}),
                             422, "FILE_DOCUMENT_INVALID_TRANSITION",
                             "ARCHIVE a DELETED file"))

    # Stage E — an action value outside the documented pair. The api-docs describe the
    # `action` query parameter without enumerating its values, so the outcome is observed.
    def unknown_action():
        fid = ctx.get("file_id")
        r = c.delete(f"/api/v1/files/{fid}", params={"action": f"BOGUS_{RUN_ID}"})
        return (True,
                f"undocumented action value -> HTTP {r.status_code}/{err_code(r)} "
                f"(api-docs do not enumerate the allowed `action` values)", snippet(r))

    run_observation("stage E — an undocumented `action` value on DELETE /files/{id}",
                    unknown_action)

    run("TC-BE-FILE-016 — archive/delete on an unknown file id 404s "
        "(FILE_DOCUMENT_NOT_FOUND)",
        lambda: expect_error(c.delete("/api/v1/files/99999999", params={"action": "ARCHIVE"}),
                             404, "FILE_DOCUMENT_NOT_FOUND", "archive an unknown file"))


# ══════════════════════════════════════════════════════════════════
# 6. Lookups  (API-FILE-008)
# ══════════════════════════════════════════════════════════════════


def test_file_lookups(c: APIClient):
    """Covers: API-FILE-008 (lookups) ;
    Negative: FILE_LOOKUP_KEY_UNKNOWN (api-docs error table, 404)
    TC-BE-FILE-020"""
    start_suite("FileLookups (API-FILE-008)")

    def lookup_shape():
        r = c.get(f"/api/v1/files/lookups/{LOOKUP_FILE_TYPE}")
        vals = data_of(r) or []
        shaped = all(set(("code", "labelAr", "labelEn")) <= set(v) for v in vals) if vals else False
        return (r.status_code == 200 and shaped,
                f"HTTP {r.status_code}, {len(vals)} option(s), each carrying "
                f"code/labelAr/labelEn: {shaped}", snippet(r))

    run("TC-BE-FILE-020 — lookups return bilingual code/labelAr/labelEn options",
        lookup_shape)

    run("TC-BE-FILE-020 — a key FILE does not own 404s (FILE_LOOKUP_KEY_UNKNOWN)",
        lambda: expect_error(c.get(f"/api/v1/files/lookups/NOT_A_KEY_{RUN_ID}"),
                             404, "FILE_LOOKUP_KEY_UNKNOWN", "unknown lookup key"))

    run("TC-BE-FILE-020 — an SQL-injection lookup key is refused, not executed "
        "(FILE_LOOKUP_KEY_UNKNOWN / MANDATORY-J-8)",
        lambda: expect_error(c.get("/api/v1/files/lookups/X'%20OR%20'1'='1"),
                             404, "FILE_LOOKUP_KEY_UNKNOWN", "injected lookup key"))

    # Stage E — FILE deliberately fronts only its own two LOVs; an MDL-owned key that
    # exists but belongs elsewhere is expected to be refused the same way, but no
    # artifact states so explicitly.
    def foreign_mdl_key():
        r = c.get("/api/v1/files/lookups/ACCOUNT_TYPE")
        return (True,
                f"a real MDL key FILE does not own -> HTTP {r.status_code}/{err_code(r)} "
                f"(FILE is not a generic MDL pass-through)", snippet(r))

    run_observation("stage E — an MDL key owned by another module", foreign_mdl_key)


# ══════════════════════════════════════════════════════════════════
# 7. Authentication delegation  (RULE-FILE-004)
# ══════════════════════════════════════════════════════════════════


def test_auth_delegation(c: APIClient):
    """Covers: API-FILE-004 under RULE-FILE-004 (auth delegated to the Security filter)
    TC-BE-FILE-007"""
    start_suite("Auth delegation (RULE-FILE-004)")

    fid = ctx.get("file_id") or 1
    anon = requests.Session()

    def no_jwt():
        r = anon.get(f"{BASE_URL}/api/v1/files/{fid}", timeout=30)
        return (r.status_code == 401,
                f"GET /files/{{id}} with NO Authorization header -> HTTP {r.status_code} "
                f"(want 401 from the Security filter)", snippet(r))

    run("TC-BE-FILE-007 — an unauthenticated metadata read is refused by the Security "
        "filter before FILE runs", no_jwt)

    def bad_jwt():
        r = anon.get(f"{BASE_URL}/api/v1/files/{fid}",
                     headers={"Authorization": f"Bearer not.a.jwt.{RUN_ID}"}, timeout=30)
        return (r.status_code == 401,
                f"GET /files/{{id}} with an invalid JWT -> HTTP {r.status_code} (want 401)",
                snippet(r))

    run("TC-BE-FILE-007 — an invalid JWT is refused by the Security filter", bad_jwt)

    def upload_no_jwt():
        r = c.upload(text_bytes(512), f"anon_{RUN_ID}.txt",
                     {"ownerId": OWNER_ID, "ownerType": OWNER_TYPE,
                      "moduleCode": MODULE_CODE}, omit_auth=True)
        if r.status_code in (200, 201):
            created["FileDocument"].append(field_of(r, "id"))
        return (r.status_code == 401,
                f"POST /files with no Authorization header -> HTTP {r.status_code} (want 401)",
                snippet(r))

    run("TC-BE-FILE-007 — an unauthenticated upload is refused", upload_no_jwt)

    # Enabled gap (test defect, not an erp-core change): TC-BE-FILE-019's permission half
    # (MANDATORY-J-5 "no VIEW -> 403") was declared a GAP on the premise that FILE's @PreAuthorize
    # were commented out (`TODO: SEC-PENDING`). That premise was stale: the checks were already
    # live before erp-core (newback initial commit a9ed097, FileService @PreAuthorize on
    # PermissionConstants), and erp-core 1.2.0 keeps them (`PERM_FILE_*`, code-defined by
    # FilePermissions — P1/srs.md addendum §4). So the TC is executed as written: a staff user
    # with NO role is refused with 403. The wire code is the shared handler's ACCESS_DENIED
    # (docs/api-docs/file/index.md, Known Error Codes).
    uname = f"file-noperm-{RUN_ID}"

    def make_noperm_user():
        r = c.post("/api/v1/sec/users",
                   {"username": uname, "email": f"{uname}@t.test", "fullNameAr": "بلا صلاحية",
                    "fullNameEn": "No Permission", "password": NOPERM_PASSWORD})
        if r.status_code == 201:
            ctx["noperm_user_id"] = field_of(r, "userPk")
            created["SecUser"].append(ctx["noperm_user_id"])
        tok = c.login(uname, NOPERM_PASSWORD) if r.status_code == 201 else None
        ctx["noperm_token"] = tok
        return (r.status_code == 201 and bool(tok),
                f"create staff user with no role: HTTP {r.status_code}, login token "
                f"present={bool(tok)}", snippet(r))

    run("TC-BE-FILE-019 (fixture) — a staff user with no role and no FILE permission",
        make_noperm_user)

    ntok = ctx.get("noperm_token")
    if not ntok:
        blocked("TC-BE-FILE-019 (permission half)", "unprivileged user could not log in")
        return
    run("TC-BE-FILE-019 — without PERM_FILE_BROWSER_VIEW, file metadata read is refused (403)",
        lambda: expect_error(c.get(f"/api/v1/files/{fid}", token=ntok),
                             403, "ACCESS_DENIED", "GET /files/{id} as a user with no role"))
    run("TC-BE-FILE-019 — without PERM_FILE_CATEGORIES_VIEW, category search is refused (403)",
        lambda: expect_error(c.post("/api/v1/files/categories/search",
                                    {"page": 0, "size": 5}, token=ntok),
                             403, "ACCESS_DENIED", "POST /files/categories/search as no-role user"))

    def upload_noperm():
        r = c.upload(text_bytes(512), f"noperm_{RUN_ID}.txt",
                     {"ownerId": OWNER_ID, "ownerType": OWNER_TYPE, "moduleCode": MODULE_CODE},
                     token=ntok)
        if r.status_code in (200, 201):
            created["FileDocument"].append(field_of(r, "id"))
        return expect_error(r, 403, "ACCESS_DENIED", "POST /files as a user with no role")

    run("TC-BE-FILE-019 — without PERM_FILE_BROWSER_CREATE, upload is refused (403)",
        upload_noperm)


# ══════════════════════════════════════════════════════════════════
# Stage F — teardown
# ══════════════════════════════════════════════════════════════════


def cleanup(c: APIClient):
    """Reverse of the manifest's DEPENDENCY ORDER (FileDocument, then FileCategory).
    FILE documents NO hard delete for either entity — DELETE /files/{id} sets
    fileStatusId=DELETED and explicitly RETAINS the bytes (RULE-FILE-006), and
    DELETE /files/categories/{id} only clears the active flag. Every row below
    therefore survives and is listed individually, never summarised as 'cleaned up'."""
    print("\n=== CLEANUP (reverse dependency order) ===")

    doc_ids = [i for i in created["FileDocument"] if i]
    for fid in doc_ids:
        try:
            # DELETED is terminal (FileDocumentDomain): re-deleting an already-deleted
            # row is a legitimate 422, not a cleanup failure — skip it instead.
            cur = field_of(c.get(f"/api/v1/files/{fid}"), "fileStatusId")
            if cur == "DELETED":
                print(f"  FileDocument {fid}: already DELETED — skipped")
                continue
            r = c.delete(f"/api/v1/files/{fid}", params={"action": "DELETE"})
            print(f"  soft-delete FileDocument {fid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  soft-delete FileDocument {fid} FAILED: {e}")
    if doc_ids:
        # erp-core 1.2.0: content lives in the configured storage provider (DB by default;
        # FILE_CONTENT is nullable and filled for DB only) — P2/db-script.md "Implementation
        # Addendum — erp-core 1.2.0"; DEVIATIONS [07].
        LEFT_BEHIND.append(
            f"FILE_DOCUMENT rows {doc_ids} — set to fileStatusId=DELETED (soft). FILE "
            f"documents no hard delete, and RULE-FILE-006 RETAINS the bytes; with the default "
            f"DB storage provider the BYTEA FILE_CONTENT column of each of these rows still "
            f"holds this run's uploaded payload (~{UNDER_LIMIT_BYTES // 1024} KB for the "
            f"largest; with LOCAL/S3 the object stays in that store). Purge SQL: "
            f"DELETE FROM FILE_DOCUMENT WHERE ID IN ({', '.join(str(i) for i in doc_ids)});")

    cat_ids = [i for i in created["FileCategory"] if i]
    for cid in cat_ids:
        try:
            r = c.delete(f"/api/v1/files/categories/{cid}")
            print(f"  deactivate FileCategory {cid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate FileCategory {cid} FAILED: {e}")
    if cat_ids:
        LEFT_BEHIND.append(
            f"FILE_CATEGORY rows {cat_ids} (codes CONTRACTS_{RUN_ID}, IMAGES_{RUN_ID}, "
            f"RETIRED_{RUN_ID}) — deactivated (soft); FILE documents no hard delete and no "
            f"activate endpoint. Purge SQL: DELETE FROM FILE_CATEGORY WHERE ID IN "
            f"({', '.join(str(i) for i in cat_ids)});")

    # erp-core 1.2.0: TC-BE-FILE-019's no-role staff user (SEC exposes deactivate, not delete).
    user_ids = [i for i in created["SecUser"] if i]
    for uid in user_ids:
        try:
            r = c.delete(f"/api/v1/sec/users/{uid}")
            print(f"  deactivate SecUser {uid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate SecUser {uid} FAILED: {e}")
    if user_ids:
        LEFT_BEHIND.append(
            f"SEC_USER rows {user_ids} (username file-noperm-{RUN_ID}, tenant PLATFORM, no role) "
            f"— deactivated; SEC exposes no hard delete for users.")

    # FILE writes into no registry or reference table another module's rules read: both of
    # its tables are module-local, and its two LOVs are read from MDL, never written to.
    # Nothing qualifies as permanent residue under stage F.


# ══════════════════════════════════════════════════════════════════
# Report
# ══════════════════════════════════════════════════════════════════


# erp-core 1.2.0 adaptation record — static, embedded in every generated report so the report
# always carries the baseline and the classification the brief requires.
ADAPTATION_DATE = "2026-10-05"
ADAPTATION_TARGET = "erp-core 1.2.0 @ newback main (reference app jar, dev profile, DB storage provider)"
BASELINE_SUMMARY = [
    "**Original script, unmodified** (only BASE_URL pointed at the instance via argv[1]): "
    "**0 passed · 0 failed · 0 run — aborted at login** with `FATAL: could not authenticate — "
    "ENVIRONMENT_FAILURE` (exit 2). `POST /api/v1/sec/auth/login {admin/admin}` without a "
    "tenant header answers 400 `TENANT_REQUIRED`; with `X-Tenant-Code: PLATFORM` it answers 401 "
    "`SEC-401-INVALID-CREDENTIALS` (admin/admin no longer exists).",
    "**Diagnostic run** (original script, login call alone shimmed to send `X-Tenant-Code: "
    "PLATFORM` + the bootstrap password; nothing else changed): **42 passed · 0 failed**, "
    "7 observations. Every behaviour assertion of the legacy suite holds on erp-core 1.2.0.",
]
CLASSIFICATION = [
    # (test / spot, class, reference)
    ("ALL (login, suite aborted before any TC) — 400 TENANT_REQUIRED without tenant header",
     "(a) INTENDED CHANGE",
     "DEVIATIONS [05] TenantResolutionFilter, resolution rule (3); smoke test logs in with "
     "`X-Tenant-Code: PLATFORM`"),
    ("ALL (login) — admin/admin → 401 SEC-401-INVALID-CREDENTIALS",
     "(a) INTENDED CHANGE",
     "DEVIATIONS [04] Task 2 (admin seeded PENDING, password from "
     "`ERP_BOOTSTRAP_ADMIN_PASSWORD`) and [04] admin password in the reference app (admin/admin "
     "asserted 401)"),
    ("Hard-coded BASE_URL / credentials (not a failure; brief hygiene)",
     "(b) TEST-DEFECT",
     "secrets must not be hard-coded; BASE_URL now from env `ERP_BASE_URL`; the fixture user's "
     "password is generated at random per run"),
    ("TC-BE-FILE-019 permission half — was a declared GAP (`TODO: SEC-PENDING`), now executed "
     "(enabled gap; assertions as the TC states them)",
     "(b) TEST-DEFECT (stale gap)",
     "the gap's premise was stale: FILE's @PreAuthorize checks were already live before erp-core "
     "(newback initial commit a9ed097); erp-core 1.2.0 keeps them (`PERM_FILE_*` code-defined by "
     "`FilePermissions`, P1/srs.md addendum §4); 403 wire code `ACCESS_DENIED` per "
     "docs/api-docs/file/index.md"),
    ("Cleanup purge note (FILE_CONTENT always holds the bytes)",
     "(a) INTENDED CHANGE (text only)",
     "P2/db-script.md addendum (`FILE_CONTENT` nullable, DB provider only); DEVIATIONS [07] "
     "provider selection"),
]


def write_report(path: str):
    total_p = sum(s.passed_count for s in SUITES)
    total_f = sum(s.failed_count for s in SUITES)
    fails = [(s, r) for s in SUITES for r in s.results if not r.passed]
    lines = [
        "# FILE — legacy API suite: problems report (erp-core 1.2.0)",
        "",
        f"- Run date: {date.today().isoformat()} · RUN_ID `{RUN_ID}`",
        f"- Target: {ADAPTATION_TARGET} at `{BASE_URL}`",
        f"- Script: `backend/modules/FILE/test-api/test_file_apis.py` (adapted {ADAPTATION_DATE}; "
        f"regenerates this report on every run)",
        "- Sources of truth for intentional changes: newback `docs/DEVIATIONS.md`, "
        "`docs/CHANGELOG.md`, `docs/api-docs/file/**`, and the \"Implementation Addendum — "
        "erp-core 1.2.0\" sections of `analysis/modules/FILE/P0..P2`.",
        "",
        "## Baseline (original script)",
        "",
    ]
    lines += [f"- {b}" for b in BASELINE_SUMMARY]
    lines += [
        "",
        "## Classification of baseline failures and adaptations",
        "",
        "Classes: (a) intended change, (b) test defect, (c) suspected app defect.",
        "",
        "| Test / spot | Class | Reference |",
        "|---|---|---|",
    ]
    for t, k, ref in CLASSIFICATION:
        lines.append(f"| {t} | {k} | {ref} |")
    lines += [
        "",
        "Counts: (a) 3 · (b) 2 · (c) 0. No assertion was weakened; every TC id is kept.",
        "",
        "## Final results (this run)",
        "",
        f"**{total_p} passed · {total_f} failed** across {len(SUITES)} suites · "
        f"{len(OBSERVATIONS)} observation(s), which never affect the totals.",
        "",
        "| Suite | Passed | Failed |",
        "|---|---|---|",
    ]
    for s in SUITES:
        lines.append(f"| {s.entity} | {s.passed_count} | {s.failed_count} |")

    lines += ["", "## Suspected app defects — class (c)", ""]
    if not fails:
        lines.append("_None._ Every remaining assertion passes on erp-core 1.2.0.")
    else:
        lines.append("Every failure below is unexplained by a documented decision until "
                     "triaged; request / expected / observed are in the row.")
        lines.append("")
        lines.append("| Suite | Test | Expected vs observed | Response evidence |")
        lines.append("|---|---|---|---|")
        for s, r in fails:
            det = r.detail.replace("|", "\\|")[:300]
            snip = (r.response_snippet or "").replace("|", "\\|")[:200]
            lines.append(f"| {s.entity} | {r.name} | {det} | `{snip}` |")

    lines += [
        "", "## Findings carried over from the legacy report (not failures)", "",
        "- **TC-BE-FILE-009 — ERR-0004 `FILE_DOCUMENT_OWNERSHIP_REQUIRED` is unreachable "
        "over HTTP** (still true on 1.2.0). `@Valid @ModelAttribute UploadRequest` refuses a "
        "missing `moduleCode` with the platform `VALIDATION_ERROR` (400, `fieldErrors` naming "
        "the field) before the domain guard runs. The test asserts that documented platform "
        "shape, so it passes; whether the plan's ERR-0004 expectation should be narrowed to the "
        "in-process path is an owner decision. Not an erp-core 1.2.0 regression.",
        "- **Upload multipart part names are documented as a nested `request.*` object** in "
        "`docs/api-docs/file/endpoints/file-documents.md`; the controller binds flat fields and "
        "the nested spelling answers 400 `VALIDATION_ERROR` (observation below). Generator "
        "rendering gap.",
        "- **The `action` query parameter on `DELETE /api/v1/files/{id}` is documented without "
        "its allowed values** (`ARCHIVE` default, `DELETE`); any other value answers 400 "
        "`FILE_DOCUMENT_INVALID_TRANSITION`, a code whose documented status is 422.",
        "- **FILE error codes are `FILE_*` SCREAMING_SNAKE**, not the `{MOD}-{http}-{SLUG}` "
        "format of `api-verify-config.md` §3 — Legacy Path convention, flagged for a human "
        "decision.",
        "- Resolved since the legacy report: the api-doc now documents `201 Created` for "
        "`POST /api/v1/files` and `POST /api/v1/files/categories`.",
        "",
        "## Out of scope of this legacy suite",
        "",
        "- erp-core 1.2.0's new FILE capabilities (storage SPI DB/LOCAL/S3, `PATCH "
        "/api/v1/files/{id}/visibility` with `FILE:DOCUMENT:PUBLISH`, category `allowPublic`, "
        "public URLs `/api/v1/public/files/{tenantCode}/{publicSlug}` with the inline allow-list "
        "and `nosniff`/CSP headers, tenant confinement) have no TC in this legacy plan; they are "
        "covered by newback `docs/test-api/core_api_verify.py` (TC-CORE-FILE-*). The new "
        "metadata fields `storageProvider`, `visibility`, `publicUrl` do not disturb any legacy "
        "assertion (none of them carries bytes).",
        "",
        "## Preconditions (stage A0)", ""]
    lines += ([f"- {p}" for p in PRECONDITION_FAILURES] or ["_All preconditions satisfied._"])

    lines += ["", "## Observations (stage E — not pass/fail)", ""]
    lines += ([f"- **{o.name}** — {o.detail}" for o in OBSERVATIONS] or ["_None._"])

    lines += ["", "## Coverage gaps (not executed, not claimed as passing)", ""]
    lines += ([f"- {g}" for g in GAPS] or ["_None._"])

    lines += ["", "## Surviving records", ""]
    lines += ([f"- {n}" for n in LEFT_BEHIND] or ["_None._"])

    lines += ["", "### Permanent residue (reference tables other modules' rules read)", ""]
    lines += ([f"- {n}" for n in PERMANENT_RESIDUE]
              or ["_None. FILE_CATEGORY and FILE_DOCUMENT are module-local; FILE reads "
                  "MDL's lookups but never writes to them._"])

    lines += [
        "", "## Privileges",
        "",
        "No permission grant was created or revoked by this run. The run authenticates as the "
        "PLATFORM bootstrap `admin` (SYS_ADMIN, a super role holding every active catalog "
        "authority — DEVIATIONS [06]). TC-BE-FILE-019's fixture user is created with no role at "
        "all and deactivated by cleanup. No standing privilege was left behind.",
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nReport written: {path}")


# ══════════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════════


def main() -> int:
    global BASE_URL
    if len(sys.argv) > 1:
        BASE_URL = sys.argv[1].rstrip("/")

    c = APIClient(BASE_URL)
    print(f"api-verify — FILE · tier Full · RUN_ID={RUN_ID} · target {BASE_URL}")

    # erp-core 1.2.0: bootstrap admin password from env, tenant PLATFORM — DEVIATIONS [04], [05].
    admin_password = os.environ.get(ADMIN_PASSWORD_ENV, "")
    if not admin_password:
        print(f"FATAL: env {ADMIN_PASSWORD_ENV} is not set — ENVIRONMENT_FAILURE "
              f"(the PLATFORM bootstrap admin password the target was started with)",
              file=sys.stderr)
        return 2
    try:
        tok = c.login(ADMIN_USERNAME, admin_password)
    except requests.RequestException as e:
        print(f"FATAL: cannot reach {BASE_URL} — ENVIRONMENT_FAILURE: {e}", file=sys.stderr)
        return 2
    if not tok:
        print("FATAL: could not authenticate — ENVIRONMENT_FAILURE", file=sys.stderr)
        return 2
    c.token = tok

    try:
        grants(c)
        preflight(c)
        test_file_category(c)
        test_file_document_upload(c)
        test_file_document_read(c)
        test_access_token_and_download(c)
        test_file_document_lifecycle(c)
        test_file_lookups(c)
        test_auth_delegation(c)
    finally:
        try:
            cleanup(c)
        except Exception as e:  # noqa: BLE001
            print(f"cleanup FAILED: {e}")
        write_report(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                  "file_problems_report.md"))

    total_f = sum(s.failed_count for s in SUITES)
    print(f"\nTOTAL: {sum(s.passed_count for s in SUITES)} passed, {total_f} failed")
    return 1 if total_f else 0


if __name__ == "__main__":
    raise SystemExit(main())
