#!/usr/bin/env python3
# Intended for Dev/Test environments only.
"""
api-verify — Post-Implementation API Test Script for the MDL module (Master Data Lookup).

Generated by the `api-verify` skill (.claude/skills/api-verify/SKILL.md) per
.claude/commands/MDL/execute-backend-test.md STEP 1. Plain requests-based script
(not pytest), same shape as governance/modules/SEC/test-api/test_sec_apis.py.

Inputs translated (no derivation — see comments for traceability):
  - governance/modules/MDL/api-docs/index.md + endpoints/*.md   (regenerated this run)
  - governance/modules/MDL/test_gen/test-execution-manifest-mdl.md  (Full tier — DEPENDENCY
    ORDER, RULE -> CODE -> TC triples, ENTITY CRUD CHECKLIST, read verbatim)
  - governance/modules/MDL/test_gen/backend-test-plan-mdl.md  (14 governed TC-MDL-* ids)
  - governance/api-verify-config.md  (base path, envelope shapes, error-code format,
    permission pattern, DELETE=soft semantics)

Tier: FULL (test-execution-manifest-mdl.md is present).

REGENERATION NOTE (2026-09-11): the previous run of this script used ownerModuleCode="FIN"
for TC-MDL-001's create and TC-MDL-013's browse-by-owner assertion, taken verbatim from
backend-test-plan-mdl.md's own Steps/Test-data lines at the time. FIN was never actually
registered in this environment's sec_module_reg table (only MDL, SEC, and TST* rows exist),
so every one of those creates 409'd on RULE-MDL-001 (MDL-409-MODULE-NOT-REGISTERED) — a correct
rejection of a fixture value that pointed at a module that was never real, not an application
defect. backend-test-plan-mdl.md has been corrected (scope line + TC-MDL-001 + TC-MDL-013 now
read "MDL" / "SEC" instead of "FIN" — MDL owning its own test lookup type is a legitimate
self-registration case; SEC is a second, genuinely different, registered module, so TC-MDL-013
still exercises real multi-owner grouping). This regeneration follows that corrected plan
verbatim: every LookupType fixture in this script now registers itself under ownerModuleCode
"MDL" (its own module), except one deliberate additional fixture created specifically for
TC-MDL-013 under ownerModuleCode "SEC" (a real cross-module reference-data registration,
exercising API-MDL-002 the same way, just for a different real owner) so the by-owner browse
has two distinct, real, registered owners to group by.

Tier: FULL (test-execution-manifest-mdl.md is present).

IMPORTANT — precondition gap discovered by this run, handled here as setup/teardown:
  MDL's own V19__mdl_security_seed.sql registers MDL's module/screens/actions into SEC's
  registry but its own inline comment explicitly states it does NOT grant SYS_ADMIN (or
  any role) those new actions — "a future grant/administration step ... not silently
  bundled here." Confirmed live: the bootstrap admin/admin account gets 403 ACCESS_DENIED
  on every single MDL endpoint with zero prior setup. Since api-verify must exercise the
  real HTTP API (not source code, not a hand DB write) and SEC already exposes a real,
  documented grant mechanism for exactly this (RoleGrantService / API-SEC-014/016/017),
  this script's own setup phase (suite "0.") grants SYS_ADMIN the 4 MDL permission codes
  through SEC's live REST API before running any MDL assertion, and — if this run is the
  one that newly created that grant (not a grant that already existed from a prior run) —
  revokes it again in cleanup() so the module-level grant does not outlive this run and
  MDL's original zero-permission bootstrap state (a deliberate design choice per V19's own
  comment) is restored for whoever runs next. This is a live-API precondition-setup step,
  the same category of action as SEC's own test_role_module_grant() granting test roles —
  not an invented business rule and not a source/DB edit.

erp-core 1.2.0 ADAPTATION (2026-10-05) — adapted only for documented, intentional contract changes:
  - Login: staff log in to a tenant (header X-Tenant-Code, default PLATFORM) and admin/admin no
    longer exists; the bootstrap admin password is read from env ERP_BOOTSTRAP_ADMIN_PASSWORD
    (DEVIATIONS [05]; core-test-plan TC-CORE-SEC-001/002). BASE_URL comes from env ERP_BASE_URL.
  - The "precondition gap" above no longer applies: V7__sec_seed.sql now carries the old
    V21__mdl_role_grants (SYS_ADMIN -> MDL grants; docs/steps/04-report.md "Old -> new mapping")
    and SYS_ADMIN is a super role holding every catalog authority (docs/steps/06-report.md;
    CHANGELOG). Suite 0 is kept unchanged as an idempotent precondition check — it now records
    SEC-409-GRANT-DUP ("already granted") for every grant and therefore never revokes anything.
  - Lookups are tenant-scoped (unique key per tenant, unique code per tenant+type — V10; MDL P1
    addendum): every fixture here is created and read in the same tenant (PLATFORM), so the
    governed assertions are unchanged.
  - The run report is written only when env MDL_RUN_REPORT is set (mdl_problems_report.md is the
    curated 1.2.0 report and is no longer overwritten).

Run: ERP_BASE_URL=http://localhost:7272 ERP_BOOTSTRAP_ADMIN_PASSWORD=... python test_mdl_apis.py
"""

from __future__ import annotations

import json
import os
import sys
import time
from dataclasses import dataclass, field
from typing import Any, Optional

import requests

# erp-core 1.2.0: base URL from env, admin/admin no longer exists (bootstrap admin password comes
# from env ERP_BOOTSTRAP_ADMIN_PASSWORD; staff log in to a tenant) — DEVIATIONS [05] (tenant filter,
# BootstrapAdminPasswordRunner); docs/test-api/core-test-plan.md TC-CORE-SEC-001/002.
BASE_URL = os.environ.get("ERP_BASE_URL", "http://localhost:7272").rstrip("/")
ADMIN_USERNAME = os.environ.get("ERP_ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.environ.get("ERP_BOOTSTRAP_ADMIN_PASSWORD")
TENANT_CODE = os.environ.get("ERP_TENANT_CODE", "PLATFORM")

# Run-scoped suffix so re-running this script doesn't collide with unique constraints
# (LookupType.key, LookupValue.code-within-type) left behind by a prior run.
RUN_ID = str(int(time.time()))[-6:]

# ══════════════════════════════════════════════════════════════════
# Result plumbing (identical shape to test_sec_apis.py)
# ══════════════════════════════════════════════════════════════════

@dataclass
class TestResult:
    name: str
    passed: bool
    detail: str
    response_snippet: str = ""


@dataclass
class TestSuite:
    entity: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.passed)


@dataclass
class Observation:
    name: str
    detail: str
    response_snippet: str = ""


SUITES: list[TestSuite] = []
OBSERVATIONS: list[Observation] = []
_current_suite: Optional[TestSuite] = None


def start_suite(entity: str) -> TestSuite:
    global _current_suite
    s = TestSuite(entity=entity)
    SUITES.append(s)
    _current_suite = s
    print(f"\n=== {entity} ===")
    return s


def run(name: str, fn):
    assert _current_suite is not None, "run() called before start_suite()"
    try:
        ok, detail, snippet = fn()
    except AssertionError as e:
        ok, detail, snippet = False, f"AssertionError: {e}", ""
    except Exception as e:  # noqa: BLE001
        ok, detail, snippet = False, f"EXCEPTION: {type(e).__name__}: {e}", ""
    result = TestResult(name=name, passed=ok, detail=detail, response_snippet=snippet)
    _current_suite.results.append(result)
    mark = "PASS" if ok else "FAIL"
    print(f"  [{mark}] {name} — {detail}")
    return result


def run_observation(name: str, fn):
    try:
        _, detail, snippet = fn()
    except Exception as e:  # noqa: BLE001
        detail, snippet = f"EXCEPTION: {type(e).__name__}: {e}", ""
    obs = Observation(name=name, detail=detail, response_snippet=snippet)
    OBSERVATIONS.append(obs)
    print(f"  [OBS ] {name} — {detail}")
    return obs


# ══════════════════════════════════════════════════════════════════
# API client
# ══════════════════════════════════════════════════════════════════

class APIClient:
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.token: Optional[str] = None
        self.session = requests.Session()

    def _headers(self, extra_token: Optional[str] = None) -> dict:
        # erp-core 1.2.0: the staff tenant comes from X-Tenant-Code (TenantResolutionFilter) —
        # DEVIATIONS [05] Task 1. Sent on every call (the token's tid wins; the header cannot switch tenant).
        h = {"Content-Type": "application/json", "X-Tenant-Code": TENANT_CODE}
        tok = extra_token if extra_token is not None else self.token
        if tok:
            h["Authorization"] = f"Bearer {tok}"
        return h

    def _make(self, method: str, path: str, json_body=None, params=None,
              token: Optional[str] = None, timeout: int = 15) -> requests.Response:
        url = f"{self.base_url}{path}"
        return self.session.request(
            method, url, json=json_body, params=params,
            headers=self._headers(token), timeout=timeout,
        )

    def get(self, path: str, params=None, token=None):
        return self._make("GET", path, params=params, token=token)

    def post(self, path: str, json_body=None, token=None):
        return self._make("POST", path, json_body=json_body, token=token)

    def put(self, path: str, json_body=None, token=None):
        return self._make("PUT", path, json_body=json_body, token=token)

    def patch(self, path: str, json_body=None, token=None):
        return self._make("PATCH", path, json_body=json_body, token=token)

    def delete(self, path: str, token=None):
        return self._make("DELETE", path, token=token)

    def login(self, username: str, password: str) -> Optional[str]:
        resp = self.post("/api/v1/sec/auth/login", {"username": username, "password": password})
        if resp.status_code == 200:
            return extract_token(resp)
        return None


def extract_token(resp: requests.Response) -> Optional[str]:
    try:
        data = resp.json().get("data") or {}
        return data.get("accessToken")
    except Exception:  # noqa: BLE001
        return None


def extract_id(resp: requests.Response, key: str) -> Optional[Any]:
    try:
        data = resp.json().get("data") or {}
        return data.get(key)
    except Exception:  # noqa: BLE001
        return None


def extract_error_code(resp: requests.Response) -> Optional[str]:
    try:
        return (resp.json().get("error") or {}).get("code")
    except Exception:  # noqa: BLE001
        return None


def extract_list(resp: requests.Response, content_key: Optional[str] = None):
    """Page envelope -> data.content ; plain array envelope -> data itself."""
    try:
        data = resp.json().get("data")
        if content_key and isinstance(data, dict):
            return data.get(content_key)
        return data
    except Exception:  # noqa: BLE001
        return None


def snippet(resp: requests.Response, limit: int = 500) -> str:
    try:
        return json.dumps(resp.json())[:limit]
    except Exception:  # noqa: BLE001
        return (resp.text or "")[:limit]


# ══════════════════════════════════════════════════════════════════
# Stage F — created-entity tracking + cleanup (reverse dependency order)
# ══════════════════════════════════════════════════════════════════

created_ids: dict[str, list[int]] = {
    "LookupType": [],
    "LookupValue": [],
}

LEFT_BEHIND_NOTES: list[str] = []


def cleanup(client: APIClient, grant_ctx: dict):
    """Stage F teardown — reverse of the manifest's DEPENDENCY ORDER (LookupType, then
    LookupValue) means cleanup order is LookupValue first, then LookupType. Both entities
    have a real deactivate (soft) endpoint per the ENTITY CRUD CHECKLIST — no hard delete
    used, matching api-verify-config.md's DELETE=soft convention.

    Also reverses the setup-phase permission grant (see module docstring) IF this run is
    the one that newly created it — never touches a grant that already existed before this
    run started, so a concurrent session's own setup is left alone.
    """
    print("\n=== CLEANUP (reverse dependency order) ===")

    for value_id in created_ids["LookupValue"]:
        try:
            r = client.delete(f"/api/v1/mdl/lookup-values/{value_id}")
            print(f"  deactivate LookupValue {value_id}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate LookupValue {value_id} FAILED: {e}")

    for type_id in created_ids["LookupType"]:
        try:
            r = client.delete(f"/api/v1/mdl/lookup-types/{type_id}")
            print(f"  deactivate LookupType {type_id}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate LookupType {type_id} FAILED: {e}")

    if grant_ctx.get("newly_granted_module") and grant_ctx.get("role_id") and grant_ctx.get("module_id"):
        try:
            r = client.delete(f"/api/v1/sec/roles/{grant_ctx['role_id']}/modules/{grant_ctx['module_id']}")
            print(f"  revoke temporary MDL module grant from SYS_ADMIN: {r.status_code} "
                  "(cascades the 2 screen + 4 action grants this run added)")
        except Exception as e:  # noqa: BLE001
            print(f"  revoke temporary MDL module grant FAILED: {e}")
    elif grant_ctx.get("granted"):
        LEFT_BEHIND_NOTES.append(
            "MDL module/screen/action grant on SYS_ADMIN already existed before this run "
            "(not newly created by it) — left in place, not revoked."
        )

    if LEFT_BEHIND_NOTES:
        print("\n  Notes:")
        for note in LEFT_BEHIND_NOTES:
            print(f"    - {note}")


# ══════════════════════════════════════════════════════════════════
# Suite 0 — Setup: grant SYS_ADMIN the 4 MDL permission codes (see module docstring)
# ══════════════════════════════════════════════════════════════════

def setup_grant_mdl_permissions(client: APIClient) -> dict:
    """Not a governed TC — infrastructure precondition setup via SEC's own real, documented
    grant endpoints (API-SEC-014 module grant, API-SEC-016 screen grant, API-SEC-017 action
    grant), required because V19__mdl_security_seed.sql deliberately left SYS_ADMIN without
    the MDL permissions it registered (see its own inline comment). Tolerates
    SEC-409-GRANT-DUP as "already granted" (idempotent across re-runs).

    # erp-core 1.2.0: SYS_ADMIN already holds the MDL grants (V7__sec_seed.sql, ex-V21) and is a
    # super role — docs/steps/04-report.md, docs/steps/06-report.md. Every grant below is
    # expected to answer SEC-409-GRANT-DUP; the suite stays as an idempotent precondition check."""
    start_suite("0. Setup — grant MDL permissions to SYS_ADMIN role")
    ctx: dict = {"granted": False, "newly_granted_module": False}

    def _find_role():
        r = client.post("/api/v1/sec/roles/search", {"page": 0, "size": 200})
        if r.status_code != 200:
            return False, f"HTTP {r.status_code} searching roles", snippet(r)
        content = extract_list(r, "content") or []
        match = next((row for row in content if row.get("code") == "SYS_ADMIN"), None)
        if not match:
            return False, "no role with code=SYS_ADMIN found", snippet(r)
        ctx["role_id"] = match.get("rolePk")
        return True, f"SYS_ADMIN rolePk={ctx['role_id']}", snippet(r)
    if not run("locate SYS_ADMIN role", _find_role).passed:
        return ctx

    def _find_registry():
        r = client.post("/api/v1/sec/registry/search", {"page": 0, "size": 200})
        if r.status_code != 200:
            return False, f"HTTP {r.status_code} searching registry", snippet(r)
        content = extract_list(r, "content") or []
        mdl = next((row for row in content if row.get("code") == "MDL"), None)
        if not mdl:
            return False, "no module with code=MDL found in registry", snippet(r)
        ctx["module_id"] = mdl.get("moduleRegPk")
        screen_ids = {}
        action_ids = {}
        for screen in mdl.get("screens", []):
            screen_ids[screen.get("pageCode")] = screen.get("screenRegPk")
            for action in screen.get("actions", []):
                action_ids[action.get("permissionCode")] = action.get("actionRegPk")
        ctx["screen_ids"] = screen_ids
        ctx["action_ids"] = action_ids
        needed_actions = {"PERM_MDL_LOOKUPS_VIEW", "PERM_MDL_LOOKUPS_CREATE",
                           "PERM_MDL_LOOKUPS_UPDATE", "PERM_MDL_TYPE_REGISTRY_VIEW"}
        missing = needed_actions - action_ids.keys()
        if missing:
            return False, f"registry missing action rows: {missing}", snippet(r)
        return True, (f"module_id={ctx['module_id']}, screens={screen_ids}, "
                       f"actions={list(action_ids.keys())}"), snippet(r)
    if not run("locate MDL module/screens/actions in SEC registry", _find_registry).passed:
        return ctx

    role_id = ctx["role_id"]
    module_id = ctx["module_id"]

    def _grant_module():
        r = client.post(f"/api/v1/sec/roles/{role_id}/modules", {"moduleId": module_id})
        if r.status_code in (200, 201):
            ctx["newly_granted_module"] = True
            return True, f"HTTP {r.status_code} (newly granted)", snippet(r)
        if r.status_code == 409 and extract_error_code(r) == "SEC-409-GRANT-DUP":
            return True, "HTTP 409 SEC-409-GRANT-DUP (already granted)", snippet(r)
        return False, f"HTTP {r.status_code}, error.code={extract_error_code(r)}", snippet(r)
    if not run("grant MDL module to SYS_ADMIN", _grant_module).passed:
        return ctx

    for page_code in ("MDL_LOOKUPS", "MDL_TYPE_REGISTRY"):
        screen_id = ctx["screen_ids"].get(page_code)

        def _grant_screen(sid=screen_id, pc=page_code):
            r = client.post(f"/api/v1/sec/roles/{role_id}/screens", {"screenId": sid})
            if r.status_code in (200, 201):
                return True, f"HTTP {r.status_code} (newly granted, {pc})", snippet(r)
            if r.status_code == 409 and extract_error_code(r) == "SEC-409-GRANT-DUP":
                return True, f"HTTP 409 SEC-409-GRANT-DUP (already granted, {pc})", snippet(r)
            return False, f"HTTP {r.status_code}, error.code={extract_error_code(r)}", snippet(r)
        if not run(f"grant screen {page_code} to SYS_ADMIN", _grant_screen).passed:
            return ctx

    for perm_code in ("PERM_MDL_LOOKUPS_VIEW", "PERM_MDL_LOOKUPS_CREATE",
                      "PERM_MDL_LOOKUPS_UPDATE", "PERM_MDL_TYPE_REGISTRY_VIEW"):
        action_id = ctx["action_ids"].get(perm_code)

        def _grant_action(aid=action_id, pc=perm_code):
            r = client.post(f"/api/v1/sec/roles/{role_id}/actions", {"actionId": aid})
            if r.status_code in (200, 201):
                return True, f"HTTP {r.status_code} (newly granted, {pc})", snippet(r)
            if r.status_code == 409 and extract_error_code(r) == "SEC-409-GRANT-DUP":
                return True, f"HTTP 409 SEC-409-GRANT-DUP (already granted, {pc})", snippet(r)
            return False, f"HTTP {r.status_code}, error.code={extract_error_code(r)}", snippet(r)
        if not run(f"grant action {perm_code} to SYS_ADMIN", _grant_action).passed:
            return ctx

    ctx["granted"] = True
    return ctx


# ══════════════════════════════════════════════════════════════════
# Entity 1 — LookupType
# ══════════════════════════════════════════════════════════════════

def test_lookup_type(client: APIClient) -> dict:
    """Covers: API-MDL-001/002/003/004/010 ; TC-MDL-001, TC-MDL-003, TC-MDL-013.
    Negative: RULE-MDL-001 / MDL-409-MODULE-NOT-REGISTERED / TC-MDL-002.
    Also creates the LookupType fixtures TC-MDL-004/005/010/011/012 (implemented in
    test_lookup_value, since they need child LookupValue rows first) depend on.
    Per the corrected backend-test-plan-mdl.md, every fixture below registers itself under
    ownerModuleCode "MDL" (a legitimate self-registration case), except the dedicated
    TC-MDL-013 fixture which registers under "SEC" (a second, genuinely different, real
    registered module) so the by-owner browse test exercises real multi-owner grouping."""
    start_suite("1. LookupType")
    ctx: dict = {}
    key_main = f"TEST_TYPE_{RUN_ID}"
    key_deact = f"TEST_DEACT_{RUN_ID}"
    key_payment = f"PAYMENT_METHOD_{RUN_ID}"
    key_reorder = f"TEST_REORDER_{RUN_ID}"
    key_search = f"TEST_SEARCH_{RUN_ID}"
    key_sec_owned = f"TEST_SEC_OWNED_{RUN_ID}"

    # Covers: API-MDL-002, TC-MDL-001 — create a lookup type (HAPPY). ownerModuleCode "MDL":
    # MDL owning its own test lookup type is a legitimate self-registration case (mirrors how
    # a module owning its own reference data is a real scenario, not a contrived one).
    def _create_main():
        r = client.post("/api/v1/mdl/lookup-types", {
            "key": key_main, "ownerModuleCode": "MDL",
            "nameAr": "نوع اختبار", "nameEn": "Test type",
        })
        ok = r.status_code in (200, 201)
        tid = extract_id(r, "lookupTypePk")
        active = extract_id(r, "isActiveFl")
        if ok and tid:
            created_ids["LookupType"].append(tid)
            ctx["main_id"] = tid
            ctx["main_key"] = key_main
        ok = ok and tid is not None and active is True
        return ok, f"HTTP {r.status_code}, id={tid}, isActiveFl={active}", snippet(r)
    run("create LookupType main (TC-MDL-001)", _create_main)

    # Negative: RULE-MDL-001 -> MDL-409-MODULE-NOT-REGISTERED / TC-MDL-002
    def _unregistered_owner():
        r = client.post("/api/v1/mdl/lookup-types", {
            "key": f"TEST_BADOWNER_{RUN_ID}", "ownerModuleCode": "ZZZ",
            "nameAr": "x", "nameEn": "y",
        })
        code = extract_error_code(r)
        ok = r.status_code == 409 and code == "MDL-409-MODULE-NOT-REGISTERED"
        return ok, f"HTTP {r.status_code}, error.code={code}", snippet(r)
    run("create LookupType with unregistered owner module rejected (RULE-MDL-001/TC-MDL-002)", _unregistered_owner)

    # Covers: API-MDL-003, TC-MDL-003 — key is immutable after creation
    def _update_main():
        main_id = ctx.get("main_id")
        if not main_id:
            return False, "no main_id", ""
        r = client.put(f"/api/v1/mdl/lookup-types/{main_id}", {
            "nameAr": "نوع اختبار محدث", "nameEn": "Test type updated",
        })
        ok = r.status_code == 200
        returned_key = extract_id(r, "key")
        ok = ok and returned_key == key_main
        return ok, f"HTTP {r.status_code}, key={returned_key} (expect unchanged {key_main})", snippet(r)
    run("update LookupType main — names change, key unchanged (TC-MDL-003 step 1)", _update_main)

    # TC-MDL-003 step 2 — attempt to also pass a `key` value; DTO has no such field at all
    def _update_main_with_key_field():
        main_id = ctx.get("main_id")
        if not main_id:
            return False, "no main_id", ""
        r = client.put(f"/api/v1/mdl/lookup-types/{main_id}", {
            "nameAr": "نوع اختبار محدث 2", "nameEn": "Test type updated 2", "key": "HACKED_KEY",
        })
        returned_key = extract_id(r, "key")
        # Either outcome is acceptable per the manifest's own wording — record which one this
        # implementation exhibits rather than asserting a single expected status.
        ok = (r.status_code == 400) or (r.status_code == 200 and returned_key == key_main)
        return ok, f"HTTP {r.status_code}, key={returned_key} (expect key never changes)", snippet(r)
    run("update LookupType main with an extra `key` field is ignored or rejected, never applied (TC-MDL-003 step 2)",
        _update_main_with_key_field)

    # Fixtures for LookupValue-dependent TCs (created here, entity order LookupType-first)
    def _create_fixture(key, key_field, owner_module_code="MDL"):
        def _fn():
            r = client.post("/api/v1/mdl/lookup-types", {
                "key": key, "ownerModuleCode": owner_module_code, "nameAr": "نوع اختبار", "nameEn": "Test type",
            })
            ok = r.status_code in (200, 201)
            tid = extract_id(r, "lookupTypePk")
            if ok and tid:
                created_ids["LookupType"].append(tid)
                ctx[key_field] = tid
                ctx[key_field.replace("_id", "_key")] = key
            return ok and tid is not None, f"HTTP {r.status_code}, id={tid}", snippet(r)
        return _fn
    run("create LookupType fixture: deactivation test (TC-MDL-004 setup)", _create_fixture(key_deact, "deact_id"))
    run("create LookupType fixture: payment method (TC-MDL-011 setup)", _create_fixture(key_payment, "payment_id"))
    run("create LookupType fixture: reorder (TC-MDL-010 setup)", _create_fixture(key_reorder, "reorder_id"))
    run("create LookupType fixture: search (TC-MDL-005 setup)", _create_fixture(key_search, "search_id"))
    # Dedicated second-owner fixture for TC-MDL-013 — SEC is a real, distinct, registered
    # module (unlike the former "FIN" fixture value), so this genuinely exercises a second
    # owner group, not a self-registration.
    run("create LookupType fixture: SEC-owned type (TC-MDL-013 setup)",
        _create_fixture(key_sec_owned, "sec_owned_id", owner_module_code="SEC"))

    # Covers: API-MDL-001 — search lookup types (general CRUD checklist, no dedicated TC number)
    def _search():
        r = client.post("/api/v1/mdl/lookup-types/search", {
            "page": 0, "size": 20,
            "filters": [{"field": "key", "operator": "LIKE", "value": key_main}],
        })
        ok = r.status_code == 200
        content = extract_list(r, "content")
        found = ok and isinstance(content, list) and any(row.get("key") == key_main for row in content)
        return found, f"HTTP {r.status_code}, content len={len(content) if isinstance(content, list) else 'n/a'}", snippet(r)
    run("search lookup types by key (API-MDL-001)", _search)

    # Covers: API-MDL-010, TC-MDL-013 — browse the type registry grouped by owner. Per the
    # corrected plan, this exercises two real, distinct, registered owners: MDL (key_main,
    # self-registered) and SEC (key_sec_owned, the dedicated fixture above) — no filter is
    # passed so the endpoint returns every active owner group, and both must be present.
    def _browse_by_owner():
        r = client.post("/api/v1/mdl/lookup-types/by-owner/search", {})
        ok = r.status_code == 200
        groups = r.json().get("data") if ok else None
        mdl_group = None
        sec_group = None
        if isinstance(groups, list):
            mdl_group = next((g for g in groups if g.get("ownerModuleCode") == "MDL"), None)
            sec_group = next((g for g in groups if g.get("ownerModuleCode") == "SEC"), None)
        found_mdl = bool(mdl_group) and any(t.get("key") == key_main for t in mdl_group.get("types", []))
        found_sec = bool(sec_group) and any(t.get("key") == key_sec_owned for t in sec_group.get("types", []))
        return (ok and found_mdl and found_sec), (
            f"HTTP {r.status_code}, groups={len(groups) if isinstance(groups, list) else 'n/a'}, "
            f"MDL group contains {key_main}={found_mdl}, SEC group contains {key_sec_owned}={found_sec}"), snippet(r)
    run("browse lookup-type registry grouped by owner=MDL/SEC (TC-MDL-013)", _browse_by_owner)

    # Stage E — duplicate key (Known Error Code MDL-409-TYPE-DUP, not tied to a RULE/TC row)
    def _dup_key():
        r = client.post("/api/v1/mdl/lookup-types", {
            "key": key_main, "ownerModuleCode": "MDL", "nameAr": "x", "nameEn": "y",
        })
        code = extract_error_code(r)
        return None, f"HTTP {r.status_code}, error.code={code} (duplicate key candidate MDL-409-TYPE-DUP)", snippet(r)
    run_observation("create LookupType with duplicate key", _dup_key)

    # Stage E — required-field omission (key Required=Yes)
    def _omit_key():
        r = client.post("/api/v1/mdl/lookup-types", {
            "ownerModuleCode": "MDL", "nameAr": "x", "nameEn": "y",
        })
        return None, f"HTTP {r.status_code} (key omitted)", snippet(r)
    run_observation("create LookupType with key omitted (Required=Yes field)", _omit_key)

    # Stage E — constraint boundary: key maxLength 80, one over
    def _over_length_key():
        r = client.post("/api/v1/mdl/lookup-types", {
            "key": "K" * 81, "ownerModuleCode": "MDL", "nameAr": "x", "nameEn": "y",
        })
        return None, f"HTTP {r.status_code} (key 81 chars, maxLength=80)", snippet(r)
    run_observation("create LookupType with key one char over maxLength(80)", _over_length_key)

    return ctx


# ══════════════════════════════════════════════════════════════════
# Entity 2 — LookupValue (FK -> LookupType)
# ══════════════════════════════════════════════════════════════════

def test_lookup_value(client: APIClient, type_ctx: dict) -> dict:
    """Covers: API-MDL-005/006/007/008/009/011 ; TC-MDL-004, TC-MDL-005, TC-MDL-006, TC-MDL-008,
    TC-MDL-009, TC-MDL-010, TC-MDL-011. Negative: RULE-MDL-002 / MDL-409-VALUE-DUP / TC-MDL-007;
    RULE-MDL-004 / MDL-404-TYPE-KEY / TC-MDL-012."""
    start_suite("2. LookupValue")
    ctx: dict = {}
    main_id = type_ctx.get("main_id")
    main_key = type_ctx.get("main_key")
    deact_id = type_ctx.get("deact_id")
    deact_key = type_ctx.get("deact_key")
    payment_id = type_ctx.get("payment_id")
    payment_key = type_ctx.get("payment_key")
    reorder_id = type_ctx.get("reorder_id")
    reorder_key = type_ctx.get("reorder_key")
    search_id = type_ctx.get("search_id")

    dup_code = f"DUPCODE_{RUN_ID}"

    # Covers: API-MDL-006, TC-MDL-006 — create a lookup value (HAPPY)
    def _create_main_value():
        if not main_id:
            return False, "no main_id", ""
        r = client.post(f"/api/v1/mdl/lookup-types/{main_id}/values", {
            "code": dup_code, "nameAr": "قيمة اختبار", "nameEn": "Test value", "sortOrder": 1,
        })
        ok = r.status_code in (200, 201)
        vid = extract_id(r, "lookupValuePk")
        active = extract_id(r, "isActiveFl")
        if ok and vid:
            created_ids["LookupValue"].append(vid)
            ctx["main_value_id"] = vid
        ok = ok and vid is not None and active is True
        return ok, f"HTTP {r.status_code}, id={vid}, isActiveFl={active}", snippet(r)
    run("create LookupValue under main type (TC-MDL-006)", _create_main_value)

    # Negative: RULE-MDL-002 -> MDL-409-VALUE-DUP / TC-MDL-007
    def _dup_value_code():
        if not main_id:
            return False, "no main_id", ""
        r = client.post(f"/api/v1/mdl/lookup-types/{main_id}/values", {
            "code": dup_code, "nameAr": "x", "nameEn": "y", "sortOrder": 2,
        })
        code = extract_error_code(r)
        ok = r.status_code == 409 and code == "MDL-409-VALUE-DUP"
        return ok, f"HTTP {r.status_code}, error.code={code}", snippet(r)
    run("create LookupValue with duplicate code under same type rejected (RULE-MDL-002/TC-MDL-007)", _dup_value_code)

    # Covers: API-MDL-007, TC-MDL-008 — edit a lookup value
    def _update_value():
        vid = ctx.get("main_value_id")
        if not vid:
            return False, "no main_value_id", ""
        r = client.put(f"/api/v1/mdl/lookup-values/{vid}", {
            "nameAr": "قيمة محدثة", "nameEn": "Updated value", "sortOrder": 5,
        })
        ok = r.status_code == 200
        code_unchanged = extract_id(r, "code") == dup_code
        type_unchanged = extract_id(r, "lookupTypeId") == main_id
        ok = ok and code_unchanged and type_unchanged
        return ok, (f"HTTP {r.status_code}, code unchanged={code_unchanged}, "
                     f"lookupTypeId unchanged={type_unchanged}"), snippet(r)
    run("update LookupValue — names/sortOrder change, code+lookupTypeId unchanged (TC-MDL-008)", _update_value)

    # Covers: API-MDL-005, TC-MDL-005 — select a type and list its values (3 values, ordered)
    def _search_values():
        if not search_id:
            return False, "no search_id", ""
        codes = [f"SV1_{RUN_ID}", f"SV2_{RUN_ID}", f"SV3_{RUN_ID}"]
        created = []
        for i, code in enumerate(codes, start=1):
            r = client.post(f"/api/v1/mdl/lookup-types/{search_id}/values", {
                "code": code, "nameAr": "قيمة", "nameEn": "Value", "sortOrder": i,
            })
            vid = extract_id(r, "lookupValuePk")
            if r.status_code in (200, 201) and vid:
                created_ids["LookupValue"].append(vid)
                created.append(vid)
        if len(created) != 3:
            return False, f"only created {len(created)}/3 fixture values", ""
        r = client.post("/api/v1/mdl/lookup-types/values/search", {
            "page": 0, "size": 20,
            "filters": [{"field": "lookupTypeId", "operator": "EQUALS", "value": search_id}],
        })
        ok = r.status_code == 200
        content = extract_list(r, "content")
        ok = ok and isinstance(content, list) and len(content) == 3
        ordered = ok and [row.get("code") for row in content] == codes
        return ordered, (f"HTTP {r.status_code}, content len={len(content) if isinstance(content, list) else 'n/a'}, "
                          f"ordered by sortOrder={ordered}"), snippet(r)
    run("search values of a type — 3 values, ordered by sortOrder (TC-MDL-005)", _search_values)

    # Covers: API-MDL-009, TC-MDL-010 — reorder lookup values
    def _reorder():
        if not reorder_id:
            return False, "no reorder_id", ""
        codes = {"RV1": f"RV1_{RUN_ID}", "RV2": f"RV2_{RUN_ID}", "RV3": f"RV3_{RUN_ID}"}
        ids = {}
        for label, code in codes.items():
            r = client.post(f"/api/v1/mdl/lookup-types/{reorder_id}/values", {
                "code": code, "nameAr": "قيمة", "nameEn": "Value",
                "sortOrder": {"RV1": 1, "RV2": 2, "RV3": 3}[label],
            })
            vid = extract_id(r, "lookupValuePk")
            if r.status_code in (200, 201) and vid:
                created_ids["LookupValue"].append(vid)
                ids[label] = vid
        if len(ids) != 3:
            return False, f"only created {len(ids)}/3 fixture values", ""
        r = client.patch(f"/api/v1/mdl/lookup-types/{reorder_id}/values/reorder", {
            "orderedValueIds": [ids["RV3"], ids["RV1"], ids["RV2"]],
        })
        ok = r.status_code == 200
        # The manifest's literal "sortOrder persisted as 3,1,2" does not match this
        # implementation's own documented formula (LookupValueService#reorder assigns
        # sortOrder = 0-based list position) — treated as a test-plan wording mismatch, not
        # asserted literally here (see mdl_problems_report.md). The behavioral guarantee the
        # TC actually cares about — a subsequent API-MDL-011 read returns them in the new
        # order — is what this asserts, via the consumer API below.
        r2 = client.get("/api/v1/mdl/lookups", params={"type": reorder_key})
        ok2 = r2.status_code == 200
        values2 = r2.json().get("data") if ok2 else None
        got_order = [v.get("code") for v in values2] if isinstance(values2, list) else None
        expect_order = [codes["RV3"], codes["RV1"], codes["RV2"]]
        ordered_ok = got_order == expect_order
        return (ok and ordered_ok), (
            f"HTTP {r.status_code}; consumer read order={got_order} (expect {expect_order})"), snippet(r)
    run("reorder lookup values — consumer read reflects new order (TC-MDL-010)", _reorder)

    # Covers: API-MDL-008, TC-MDL-009 — deactivate a lookup value
    def _deactivate_value():
        vid = ctx.get("main_value_id")
        if not vid or not main_key:
            return False, "no main_value_id/main_key", ""
        r = client.delete(f"/api/v1/mdl/lookup-values/{vid}")
        ok = r.status_code == 200
        active = extract_id(r, "isActiveFl")
        ok = ok and active is False
        return ok, f"HTTP {r.status_code}, isActiveFl={active}", snippet(r)
    run("deactivate LookupValue (TC-MDL-009 step 1)", _deactivate_value)

    def _confirm_excluded_after_value_deactivate():
        if not main_key:
            return False, "no main_key", ""
        r = client.get("/api/v1/mdl/lookups", params={"type": main_key})
        ok = r.status_code == 200
        values = r.json().get("data") if ok else None
        excluded = isinstance(values, list) and all(v.get("code") != dup_code for v in values)
        return (ok and excluded), f"HTTP {r.status_code}, deactivated value excluded={excluded}", snippet(r)
    run("consumer read no longer returns the deactivated value (TC-MDL-009 step 2)",
        _confirm_excluded_after_value_deactivate)

    # Covers: API-MDL-011, TC-MDL-011 — read active values by key, ordered (2 active, 1 inactive)
    def _consumer_active_ordered():
        if not payment_id or not payment_key:
            return False, "no payment_id/payment_key", ""
        codes = [f"PM1_{RUN_ID}", f"PM2_{RUN_ID}", f"PM3_{RUN_ID}"]
        ids = []
        for i, code in enumerate(codes, start=1):
            r = client.post(f"/api/v1/mdl/lookup-types/{payment_id}/values", {
                "code": code, "nameAr": "طريقة دفع", "nameEn": "Payment method", "sortOrder": i,
            })
            vid = extract_id(r, "lookupValuePk")
            if r.status_code in (200, 201) and vid:
                created_ids["LookupValue"].append(vid)
                ids.append(vid)
        if len(ids) != 3:
            return False, f"only created {len(ids)}/3 fixture values", ""
        # deactivate the 3rd (inactive precondition)
        client.delete(f"/api/v1/mdl/lookup-values/{ids[2]}")
        r = client.get("/api/v1/mdl/lookups", params={"type": payment_key})
        ok = r.status_code == 200
        values = r.json().get("data") if ok else None
        got_codes = [v.get("code") for v in values] if isinstance(values, list) else None
        expect_codes = codes[:2]
        return (ok and got_codes == expect_codes), (
            f"HTTP {r.status_code}, codes={got_codes} (expect exactly the 2 active, ordered: {expect_codes})"
        ), snippet(r)
    run("read active values by key, ordered — 2 active + 1 inactive (TC-MDL-011)", _consumer_active_ordered)

    # Negative: RULE-MDL-004 -> MDL-404-TYPE-KEY / TC-MDL-012
    def _unknown_type_key():
        r = client.get("/api/v1/mdl/lookups", params={"type": f"NOT_A_REAL_KEY_{RUN_ID}"})
        code = extract_error_code(r)
        ok = r.status_code == 404 and code == "MDL-404-TYPE-KEY"
        return ok, f"HTTP {r.status_code}, error.code={code}", snippet(r)
    run("read lookups by unknown type key rejected (RULE-MDL-004/TC-MDL-012)", _unknown_type_key)

    # Covers: API-MDL-004, TC-MDL-004 — deactivating a type excludes its values from reads
    def _type_deactivation_excludes_values():
        if not deact_id or not deact_key:
            return False, "no deact_id/deact_key", ""
        for i, code in enumerate([f"DV1_{RUN_ID}", f"DV2_{RUN_ID}"], start=1):
            r = client.post(f"/api/v1/mdl/lookup-types/{deact_id}/values", {
                "code": code, "nameAr": "قيمة", "nameEn": "Value", "sortOrder": i,
            })
            vid = extract_id(r, "lookupValuePk")
            if r.status_code in (200, 201) and vid:
                created_ids["LookupValue"].append(vid)
        r_deact = client.delete(f"/api/v1/mdl/lookup-types/{deact_id}")
        deact_ok = r_deact.status_code == 200 and extract_id(r_deact, "isActiveFl") is False
        r_read = client.get("/api/v1/mdl/lookups", params={"type": deact_key})
        code = extract_error_code(r_read)
        # LookupConsumerService#readByKey resolves an inactive-type key through the SAME
        # 404 MDL-404-TYPE-KEY path as an unknown key (source-confirmed) — not a 200 with an
        # empty array, which the manifest's looser "returns no values" wording could also be
        # read as. Asserted against the actual implementation, noted in the problems report.
        read_ok = r_read.status_code == 404 and code == "MDL-404-TYPE-KEY"
        return (deact_ok and read_ok), (
            f"deactivate: HTTP {r_deact.status_code}; "
            f"consumer read after deactivate: HTTP {r_read.status_code}, error.code={code} "
            "(excluded via 404, not an empty 200 list)"), snippet(r_read)
    run("deactivating a type excludes its values from consumer reads (TC-MDL-004)",
        _type_deactivation_excludes_values)

    # Stage E — required-field omission (code Required=Yes)
    def _omit_code():
        if not main_id:
            return False, "no main_id", ""
        r = client.post(f"/api/v1/mdl/lookup-types/{main_id}/values", {
            "nameAr": "x", "nameEn": "y", "sortOrder": 99,
        })
        return None, f"HTTP {r.status_code} (code omitted)", snippet(r)
    run_observation("create LookupValue with code omitted (Required=Yes field)", _omit_code)

    # Stage E — invalid FK reference: create a value under a non-existent type id
    def _invalid_type_fk():
        r = client.post("/api/v1/mdl/lookup-types/999999999/values", {
            "code": f"ORPHAN_{RUN_ID}", "nameAr": "x", "nameEn": "y", "sortOrder": 1,
        })
        code = extract_error_code(r)
        return None, f"HTTP {r.status_code}, error.code={code} (non-existent parent type id)", snippet(r)
    run_observation("create LookupValue under a non-existent LookupType id", _invalid_type_fk)

    # Stage E — reorder membership mismatch (an id not belonging to the type)
    def _reorder_mismatch():
        vid = ctx.get("main_value_id")
        if not reorder_id or not vid:
            return False, "no reorder_id/main_value_id", ""
        r = client.patch(f"/api/v1/mdl/lookup-types/{reorder_id}/values/reorder", {
            "orderedValueIds": [vid],  # belongs to main_id, not reorder_id
        })
        code = extract_error_code(r)
        return None, f"HTTP {r.status_code}, error.code={code} (id from a different parent type)", snippet(r)
    run_observation("reorder with a value id that does not belong to the target type", _reorder_mismatch)

    return ctx


# ══════════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════════

def report_markdown() -> str:
    lines = ["# MDL api-verify problems report", "", f"Run: {RUN_ID}  ·  Tier: FULL", ""]
    total_pass = sum(s.passed_count for s in SUITES)
    total_fail = sum(s.failed_count for s in SUITES)
    lines.append(f"**Totals: {total_pass} PASS / {total_fail} FAIL** (observations excluded)")
    lines.append("")
    lines.append("## Suites")
    for s in SUITES:
        lines.append(f"### {s.entity} — {s.passed_count} pass / {s.failed_count} fail")
        for r in s.results:
            mark = "PASS" if r.passed else "FAIL"
            lines.append(f"- [{mark}] {r.name} — {r.detail}")
    lines.append("")
    lines.append("## Observations (Stage E, never pass/fail)")
    for o in OBSERVATIONS:
        lines.append(f"- {o.name} — {o.detail}")
    lines.append("")
    lines.append("## Problems (bucketed)")
    likely_bug, mismatch, infra = [], [], []
    for s in SUITES:
        for r in s.results:
            if r.passed:
                continue
            entry = f"{s.entity} :: {r.name} — {r.detail}"
            if "EXCEPTION" in r.detail and ("Connection" in r.detail or "Timeout" in r.detail):
                infra.append(entry)
            else:
                likely_bug.append(entry)
    lines.append("### Likely real bug")
    lines.extend(f"- {x}" for x in likely_bug) if likely_bug else lines.append("- none")
    lines.append("### Test assumption mismatch")
    lines.append("- TC-MDL-010: manifest text says \"sortOrder persisted as 3,1,2\"; actual "
                 "implementation (LookupValueService#reorder) assigns 0-based list position — "
                 "not asserted literally, the behavioral read-order check is asserted instead.")
    lines.append("- TC-MDL-004/009 step 2: manifest text says the deactivated/excluded value(s) "
                 "\"no longer returned\" / \"returns no values\"; for a deactivated TYPE this "
                 "surfaces as 404 MDL-404-TYPE-KEY (same path as an unknown key), not a 200 "
                 "empty array — asserted against the actual source-confirmed behavior.")
    lines.append("### Infrastructure")
    lines.extend(f"- {x}" for x in infra) if infra else lines.append("- none")
    lines.append("")
    lines.append("## TC-MDL-014 (INT-XM) — not exercised, documented reason")
    lines.append(
        "XM-MDL-001 (MDL -> SEC module-registry check) is implemented as a direct in-process "
        "Spring bean injection (`SecModuleRegistryApi`), confirmed in "
        "`LookupTypeService` — not a network call. There is no HTTP-level way for this script "
        "to make 'SEC unreachable' true; that would require a unit/integration test that mocks "
        "the injected bean, which is outside api-verify's real-HTTP-only scope. This matches "
        "the pre-existing `api_doc_gaps[]` entry in execution-state.json recorded during the "
        "DOC/INT-C phases. TC-MDL-014 is reported as a GAP, not a fabricated PASS."
    )
    return "\n".join(lines)


def _write_run_report() -> None:
    # erp-core 1.2.0 adaptation: the auto-generated run report no longer overwrites the curated
    # mdl_problems_report.md (which now holds the 1.2.0 classification); it is written only when
    # env MDL_RUN_REPORT names a path. — legacy-test brief, step 5
    path = os.environ.get("MDL_RUN_REPORT")
    if not path:
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(report_markdown())
    print(f"Run report written to {path}")


def main() -> int:
    print(f"MDL api-verify run — RUN_ID={RUN_ID}, tier=FULL, base={BASE_URL}, tenant={TENANT_CODE}")
    client = APIClient()

    if not ADMIN_PASSWORD:
        print("FATAL: env ERP_BOOTSTRAP_ADMIN_PASSWORD is not set (the bootstrap admin password) — aborting.")
        return 2
    token = client.login(ADMIN_USERNAME, ADMIN_PASSWORD)
    if not token:
        print(f"FATAL: could not log in as {ADMIN_USERNAME} (tenant {TENANT_CODE}) — aborting.")
        return 2
    client.token = token
    print(f"Logged in as {ADMIN_USERNAME}.")

    grant_ctx = setup_grant_mdl_permissions(client)
    if not grant_ctx.get("granted"):
        print("FATAL: could not establish MDL permissions for the admin caller — every "
              "subsequent MDL call would 403. Aborting without exercising any MDL entity.")
        _write_run_report()
        return 2

    try:
        type_ctx = test_lookup_type(client)
        test_lookup_value(client, type_ctx)
    finally:
        cleanup(client, grant_ctx)

    total_pass = sum(s.passed_count for s in SUITES)
    total_fail = sum(s.failed_count for s in SUITES)
    print(f"\n=== SUMMARY: {total_pass} PASS / {total_fail} FAIL / {len(OBSERVATIONS)} observations ===")
    _write_run_report()

    return 0 if total_fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
