#!/usr/bin/env python3
# Intended for Dev/Test environments only.
"""
api-verify — Post-Implementation API Verification Script for the NOTIF module.

Generated by the `api-verify` skill (.claude/skills/api-verify/SKILL.md), Full tier
(api-docs + P3_5_BE/test-execution-manifest.md both present).

Translation, not derivation: every path, payload value, error code and dependency edge
below is traceable to one of the inputs named here. Nothing is invented.

Inputs translated:
  - governance/modules/NOTIF/api-docs/index.md + endpoints/*.md   (regenerated this run)
  - governance/modules/NOTIF/P3_5_BE/test-execution-manifest.md
        -> DEPENDENCY ORDER (stage B), RULE -> ERR -> TC triples (stage C),
           ENTITY CRUD CHECKLIST
  - governance/modules/NOTIF/P3_5_BE/backend-test-plan.md   (TC-BE-NOTIF-001..016)
  - governance/api-verify-config.md                          (stack conventions)

Concurrency: two sibling verification runs (CU, FILE) share this database. Every value this
run writes carries the RUN_ID suffix, and no assertion reads a global count or "the first row" —
log assertions filter on this run's own `referenceType`.

erp-core 1.2.0 adaptation (2026-10-05): the suite was re-run against erp-core 1.2.0 and adapted
ONLY for documented, intentional contract changes; every adapted spot carries a comment
`# erp-core 1.2.0: <change> — <reference>`. References are the erp-core repo's docs/DEVIATIONS.md
entries ([NN] = step) and the "Implementation Addendum — erp-core 1.2.0" sections of
analysis/modules/NOTIF/P0/business-policies-notif.md (BP#n) and P1/srs.md (SRS §n).
Results and classification: notif_problems_report.md (hand-maintained, not written by this script).

Run:  ERP_BOOTSTRAP_ADMIN_PASSWORD=<pw> python test_notif_apis.py [BASE_URL]
Env:  ERP_BASE_URL (default http://localhost:7272), ERP_BOOTSTRAP_ADMIN_PASSWORD (required),
      ERP_ADMIN_USERNAME (default admin), ERP_TENANT_CODE (default PLATFORM),
      NOTIF_FINAL_STATUS_TIMEOUT_S (default 60), NOTIF_RUN_REPORT (optional path for a per-run
      markdown report; nothing is written when unset).
Requires the `requests` package.
"""

from __future__ import annotations

import json
import os
import secrets
import sys
import time
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Optional

import requests

# erp-core 1.2.0: base URL from env ERP_BASE_URL (owner rerun convention).
BASE_URL = os.environ.get("ERP_BASE_URL", "http://localhost:7272").rstrip("/")
# erp-core 1.2.0: admin/admin no longer exists; the bootstrap admin's password is set by
# erp.core.security.bootstrap-admin-password and read here from env, never hard-coded —
# docs/test-api/core-test-plan.md TC-CORE-SEC-001/002 (BootstrapAdminPasswordRunner).
ADMIN_USERNAME = os.environ.get("ERP_ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.environ.get("ERP_BOOTSTRAP_ADMIN_PASSWORD")
# erp-core 1.2.0: staff login needs the tenant in X-Tenant-Code; the bootstrap admin lives in
# PLATFORM — DEVIATIONS [05] (multi-tenancy, TenantResolutionFilter), BP#1.
TENANT_CODE = os.environ.get("ERP_TENANT_CODE", "PLATFORM")
# erp-core 1.2.0: delivery is asynchronous (QUEUED -> SENT/FAILED/SKIPPED_NO_PROVIDER), so a
# log's outcome is read by polling until it leaves PENDING/QUEUED — DEVIATIONS [08], BP#2, SRS §3.
# 60 s covers the default retry schedule (waits 2+4+8+16 s = 30 s) with margin.
FINAL_STATUS_TIMEOUT_S = float(os.environ.get("NOTIF_FINAL_STATUS_TIMEOUT_S", "60"))
NON_FINAL_STATUSES = ("PENDING", "QUEUED")

# Run-scoped suffix. NOTIF documents no hard-delete endpoint for any entity
# (ENTITY CRUD CHECKLIST: template = soft "(flag)", channel = enable/disable, log = read-only),
# so rows from a prior run persist and would collide on the unique templateCode constraint.
# Only uniqueness is appended; every business value itself comes from an api-docs Example.
RUN_ID = str(int(time.time()))[-6:]
# erp-core 1.2.0: fixture SEC users (inactive recipient, no-permission caller) get a random
# per-run password — no credential is hard-coded or printed.
FIXTURE_PASSWORD = "Nv1!" + secrets.token_urlsafe(12)

# api-docs examples, run-scoped where a unique constraint or a run-scoped query needs it.
TEMPLATE_CODE = f"USER_WELCOME_{RUN_ID}"          # example: USER_WELCOME
TEMPLATE_CODE_INACTIVE = f"USER_WELCOME_X_{RUN_ID}"
CHANNEL_TYPE_ENABLED = "SMS"                       # example: channelHint ["EMAIL", "SMS"]
# NOTIF_CHANNEL_CONFIG.CHANNEL_TYPE_ID is UNIQUE and the module documents no hard delete, so the
# channel type a previous run created still exists (disabled). This run will not mutate a record
# it did not create, so it falls back through the remaining LOV-NOTIF-001 values — all verified
# active in preflight, none invented — until it finds one it can own. EMAIL is excluded on
# purpose: it is seeded, and it is the one channel backed by a real SMTP provider.
CHANNEL_TYPE_CANDIDATES = ["SMS", "WHATSAPP", "PUSH", "INTERNAL"]
CHANNEL_TYPE_EMAIL = "EMAIL"                       # example: channelTypeId EMAIL
# erp-core 1.2.0: IN_APP is a new seeded, enabled channel with a real core provider (writes the
# recipient's inbox); it is now the only provider-backed channel that needs no mail server —
# DEVIATIONS [08] (provider resolution, LOV-NOTIF-001 + IN_APP), BP#4, SRS §6.
CHANNEL_TYPE_IN_APP = "IN_APP"
MODULE_CODE = "SEC"                                # example: moduleCode SEC
REFERENCE_TYPE = f"USER_ACCOUNT_{RUN_ID}"          # example: USER_ACCOUNT — run-scoped so the
                                                   # log search only ever sees this run's rows
REFERENCE_ID = 1001                                # example: referenceId 1001
SQLI_MODULE_CODE = "x' OR '1'='1"                  # TC-BE-NOTIF-016, verbatim from the test plan

# Documented lookup keys (NOTIF_CHANNEL = LOV-NOTIF-001, NOTIF_STATUS = LOV-NOTIF-002);
# both named in the api-docs response field descriptions for channelTypeId / notificationStatusId.
LOOKUP_CHANNEL = "NOTIF_CHANNEL"
LOOKUP_STATUS = "NOTIF_STATUS"

# ══════════════════════════════════════════════════════════════════
# Result plumbing
# ══════════════════════════════════════════════════════════════════


@dataclass
class TestResult:
    name: str
    passed: bool
    detail: str
    response_snippet: str = ""


@dataclass
class TestSuite:
    entity: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.passed)


@dataclass
class Observation:
    name: str
    detail: str
    response_snippet: str = ""


SUITES: list[TestSuite] = []
OBSERVATIONS: list[Observation] = []
PRECONDITION_FAILURES: list[str] = []
_current_suite: Optional[TestSuite] = None


def start_suite(entity: str) -> TestSuite:
    global _current_suite
    s = TestSuite(entity=entity)
    SUITES.append(s)
    _current_suite = s
    print(f"\n=== {entity} ===")
    return s


def run(name: str, fn):
    """Executes fn(); records pass/fail. fn returns (bool, detail, snippet)."""
    assert _current_suite is not None, "run() called before start_suite()"
    try:
        ok, detail, snip = fn()
    except AssertionError as e:
        ok, detail, snip = False, f"AssertionError: {e}", ""
    except Exception as e:  # noqa: BLE001
        ok, detail, snip = False, f"EXCEPTION: {type(e).__name__}: {e}", ""
    r = TestResult(name=name, passed=ok, detail=detail, response_snippet=snip)
    _current_suite.results.append(r)
    print(f"  [{'PASS' if ok else 'FAIL'}] {name} — {detail}")
    return r


def run_observation(name: str, fn):
    """Stage E — outcome not governed by a RULE + code. Never affects totals."""
    try:
        _, detail, snip = fn()
    except Exception as e:  # noqa: BLE001
        detail, snip = f"EXCEPTION: {type(e).__name__}: {e}", ""
    o = Observation(name=name, detail=detail, response_snippet=snip)
    OBSERVATIONS.append(o)
    print(f"  [OBS ] {name} — {detail}")
    return o


def blocked(name: str, why: str):
    """Records a test that could not run because a precondition failed."""
    assert _current_suite is not None
    r = TestResult(name=name, passed=False, detail=f"BLOCKED-ON-PRECONDITION: {why}")
    _current_suite.results.append(r)
    print(f"  [BLK ] {name} — {why}")
    return r


# ══════════════════════════════════════════════════════════════════
# API client — ApiResponse<T> envelope per api-verify-config.md §3
# ══════════════════════════════════════════════════════════════════


class APIClient:
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.token: Optional[str] = None
        self.session = requests.Session()

    def _headers(self, token: Optional[str] = None, lang: Optional[str] = None,
                 anonymous: bool = False) -> dict:
        h = {"Content-Type": "application/json"}
        tok = None if anonymous else (token if token is not None else self.token)
        if tok:
            h["Authorization"] = f"Bearer {tok}"
        if lang:
            h["Accept-Language"] = lang
        return h

    def _make(self, method, path, json_body=None, params=None, token=None,
              lang=None, anonymous=False, timeout=60, extra_headers=None):
        headers = self._headers(token, lang, anonymous)
        if extra_headers:
            headers.update(extra_headers)
        return self.session.request(
            method, f"{self.base_url}{path}", json=json_body, params=params,
            headers=headers, timeout=timeout,
        )

    def get(self, path, params=None, token=None, lang=None, anonymous=False):
        return self._make("GET", path, params=params, token=token, lang=lang, anonymous=anonymous)

    def post(self, path, json_body=None, token=None, lang=None, anonymous=False):
        return self._make("POST", path, json_body=json_body, token=token, lang=lang,
                          anonymous=anonymous)

    def put(self, path, json_body=None, token=None, lang=None):
        return self._make("PUT", path, json_body=json_body, token=token, lang=lang)

    def delete(self, path, token=None):
        return self._make("DELETE", path, token=token)

    def login(self, username: str, password: str) -> Optional[str]:
        # erp-core 1.2.0: staff login is tenant-scoped — X-Tenant-Code is mandatory on the public
        # staff paths (400 TENANT_REQUIRED without it); the JWT then carries tid/realm=STAFF and
        # no later request needs the header — DEVIATIONS [05], [06]; core-test-plan TC-CORE-TENANT-001.
        r = self._make("POST", "/api/v1/sec/auth/login",
                       json_body={"username": username, "password": password},
                       anonymous=True, extra_headers={"X-Tenant-Code": TENANT_CODE})
        if r.status_code == 200:
            return ((r.json().get("data")) or {}).get("accessToken")
        return None


def data_of(resp) -> Any:
    try:
        return resp.json().get("data")
    except Exception:  # noqa: BLE001
        return None


def field_of(resp, key) -> Any:
    d = data_of(resp)
    return d.get(key) if isinstance(d, dict) else None


def err_code(resp) -> Optional[str]:
    try:
        return (resp.json().get("error") or {}).get("code")
    except Exception:  # noqa: BLE001
        return None


def snippet(resp, limit: int = 300) -> str:
    try:
        return json.dumps(resp.json(), ensure_ascii=False)[:limit]
    except Exception:  # noqa: BLE001
        return (resp.text or "")[:limit]


def jwt_claim(token: str, key: str):
    """Reads one claim from a JWT payload (no verification — the server already issued it)."""
    import base64
    try:
        part = token.split(".")[1]
        part += "=" * (-len(part) % 4)
        return json.loads(base64.urlsafe_b64decode(part)).get(key)
    except Exception:  # noqa: BLE001
        return None


def expect_status(resp, want: int, what: str):
    return (resp.status_code == want,
            f"{what}: HTTP {resp.status_code} (want {want})", snippet(resp))


def expect_error(resp, want_status: int, want_code: str, what: str):
    got = err_code(resp)
    ok = resp.status_code == want_status and got == want_code
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got} (want {want_status}/{want_code})",
            snippet(resp))


def field_errors(resp) -> list:
    """The `error.fieldErrors` array of the platform validation envelope (may be absent/null)."""
    try:
        return (resp.json().get("error") or {}).get("fieldErrors") or []
    except Exception:  # noqa: BLE001
        return []


def expect_validation_field(resp, want_field: str, what: str):
    """Assert the platform's deliberate bean-validation refusal: HTTP 400, wire code
    `VALIDATION_ERROR`, and a `fieldErrors` entry naming `want_field`.

    This is GlobalExceptionHandler.handleValidation's documented shape. Asserting the field
    name (not just the status) is what keeps such a test meaningful: it still proves the rule
    is enforced AND on which field, which the generic per-module business code cannot express
    because it carries no per-field detail and reports only one failure at a time.
    """
    got = err_code(resp)
    fields = [fe.get("field") for fe in field_errors(resp)]
    ok = (resp.status_code == 400
          and got == "VALIDATION_ERROR"
          and want_field in fields)
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got}, fieldErrors={fields} "
            f"(want 400/VALIDATION_ERROR naming '{want_field}')",
            snippet(resp))


def wait_final_log(c: "APIClient", log_id, timeout: float = None):
    """erp-core 1.2.0: dispatch only persists QUEUED rows and returns; delivery runs after commit
    on a worker, so the outcome is read by polling GET logs/{id} until the row leaves
    PENDING/QUEUED — DEVIATIONS [08] (state machine), [15] (claim/lease), BP#2, SRS §3.
    Returns the last GET response (final, or still QUEUED when the timeout expired)."""
    deadline = time.time() + (FINAL_STATUS_TIMEOUT_S if timeout is None else timeout)
    while True:
        g = c.get(f"/api/v1/notifications/logs/{log_id}")
        status = field_of(g, "notificationStatusId")
        if g.status_code != 200 or status not in NON_FINAL_STATUSES or time.time() >= deadline:
            return g
        time.sleep(0.3)


# ══════════════════════════════════════════════════════════════════
# Stage F — created-entity tracking
# ══════════════════════════════════════════════════════════════════

created: dict[str, list] = {
    "NotificationTemplate": [],     # soft deactivate only (DELETE = flip isActiveFl)
    "NotificationChannelConfig": [],  # soft disable only (DELETE = flip isEnabledFl)
    "NotificationLog": [],          # no delete or deactivate surface at all — read-only screen
    # erp-core 1.2.0: SEC staff fixtures this run creates (inactive recipient, no-permission
    # caller); SEC soft-disables on DELETE — see preflight().
    "SecUser": [],
}

LEFT_BEHIND: list[str] = []
PERMANENT_RESIDUE: list[str] = []

# Shared context threaded between suites (FK ids and ids read back from a create, never literals).
ctx: dict[str, Any] = {}


# ══════════════════════════════════════════════════════════════════
# Stage I — permission preconditions
# ══════════════════════════════════════════════════════════════════


def grants(c: APIClient):
    """Stage I — no grant is needed, and none is written.

    erp-core 1.2.0: the NOTIF services' authority checks are live again
    (`@PreAuthorize(hasAuthority(T(com.erp.notif.permission.NotifPermissions)...))` on templates,
    channels and logs; dispatch, lookups and the inbox stay `isAuthenticated()`) — SRS §1 / §5
    (exact authority strings), DEVIATIONS [06] (XxxPermissions SPI). The run authenticates as the
    PLATFORM bootstrap admin, whose super role holds every catalog permission, so nothing has to be
    granted; the permission half of TC-BE-NOTIF-014 is exercised with a fixture user that holds
    no role at all (see preflight / test_authorization). No standing privilege is left behind.
    """
    return


# ══════════════════════════════════════════════════════════════════
# Stage A0 — preconditions
# ══════════════════════════════════════════════════════════════════


def preflight(c: APIClient):
    """Every externally-owned value the payloads reference is verified present and active
    before the suites that need it. Order is grants -> preconditions -> suites; this run
    needs no grant (see grants())."""
    start_suite("PREFLIGHT (stage A0)")

    def channel_lov():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        vals = data_of(r) or []
        codes = [v.get("code") for v in vals] if isinstance(vals, list) else []
        ctx["channel_codes"] = codes
        # erp-core 1.2.0: IN_APP joined LOV-NOTIF-001 — DEVIATIONS [08], SRS §6.
        missing = [x for x in (CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_ENABLED, CHANNEL_TYPE_IN_APP)
                   if x not in codes]
        if missing:
            PRECONDITION_FAILURES.append(
                f"{LOOKUP_CHANNEL}: missing active value(s) {missing} — the dispatch api-docs "
                f"example channelHint ['EMAIL','SMS'] references them")
        return (r.status_code == 200 and not missing,
                f"{LOOKUP_CHANNEL}: {len(codes)} active value(s); missing={missing or 'none'}",
                ",".join(codes))

    run(f"MDL-owned lookup '{LOOKUP_CHANNEL}' resolves via NOTIF (XM: MdlLookupApi)", channel_lov)

    def status_lov():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_STATUS}")
        vals = data_of(r) or []
        codes = [v.get("code") for v in vals] if isinstance(vals, list) else []
        ctx["status_codes"] = codes
        # The four statuses the api-docs' own notificationStatusId description and the test plan
        # name: PENDING (initial), SENT, FAILED, CHANNEL_DISABLED.
        wanted = ["PENDING", "SENT", "FAILED", "CHANNEL_DISABLED",
                  # erp-core 1.2.0: + QUEUED, SKIPPED_NO_PROVIDER — DEVIATIONS [08], SRS §6.
                  "QUEUED", "SKIPPED_NO_PROVIDER"]
        missing = [x for x in wanted if x not in codes]
        if missing:
            PRECONDITION_FAILURES.append(
                f"{LOOKUP_STATUS}: missing active value(s) {missing} — dispatch writes them as "
                f"notificationStatusId")
        return (r.status_code == 200 and not missing,
                f"{LOOKUP_STATUS}: {len(codes)} active value(s); missing={missing or 'none'}",
                ",".join(codes))

    run(f"MDL-owned lookup '{LOOKUP_STATUS}' resolves via NOTIF (XM: MdlLookupApi)", status_lov)

    def recipient():
        """recipientId is an externally-owned SEC UserAccount id. The api-docs example is 42;
        NOTIF documents no endpoint to verify it, so it is resolved through SEC's own documented
        search endpoint instead of being trusted as a literal (SKILL.md §3-A0)."""
        r = c.post("/api/v1/sec/users/search", {"page": 0, "size": 200})
        content = (data_of(r) or {}).get("content") or []
        active = [u for u in content if u.get("isActiveFl") is True]
        inactive = [u for u in content if u.get("isActiveFl") is False]
        # erp-core 1.2.0: prefer the caller itself (JWT `uid` claim) as the recipient, so the
        # IN_APP delivery can be verified in the caller's own inbox (an inbox is readable only by
        # its owner) — DEVIATIONS [08] (inbox scoped to the caller's own SEC_USER id).
        me = ctx.get("caller_user_id")
        mine = [u for u in active if u.get("userPk") == me]
        if mine or active:
            ctx["recipient_id"] = (mine or active)[0].get("userPk")
        if inactive:
            ctx["inactive_recipient_id"] = inactive[0].get("userPk")
        if not active:
            PRECONDITION_FAILURES.append(
                "no ACTIVE SEC user account found — dispatch suites cannot bind a real recipientId")
        return (bool(active),
                f"recipientId resolved from SEC: active={ctx.get('recipient_id')}, "
                f"inactive={ctx.get('inactive_recipient_id')} "
                f"(api-docs example 42 not used as a literal)",
                snippet(r, 120))

    run("recipientId (SEC UserAccount, XM-NOTIF-001) resolved and verified active", recipient)

    # erp-core 1.2.0: RULE-NOTIF-007 is implemented (XM-NOTIF-001 no longer DEFERRED: NOTIF reads
    # SEC through RecipientDirectory/SecUserDirectoryApi), so TC-BE-NOTIF-010 can be asserted. A
    # fresh tenant has no inactive user, so the run creates one STAFF user and disables it through
    # SEC's documented DELETE — BP#7, SRS §2 (RULE-NOTIF-007), DEVIATIONS [06], [08];
    # core-test-plan TC-CORE-NOTIF-011 uses the same arrangement.
    def inactive_recipient_fixture():
        if ctx.get("inactive_recipient_id"):
            return True, f"pre-existing inactive SEC user {ctx['inactive_recipient_id']} reused", ""
        uname = f"notif-inact-{RUN_ID}"
        r = c.post("/api/v1/sec/users", {
            "username": uname, "email": f"{uname}@notif-verify.test",
            "fullNameAr": "مستخدم معطل", "fullNameEn": "Inactive Recipient",
            "password": FIXTURE_PASSWORD})
        uid = field_of(r, "userPk")
        if r.status_code != 201 or not uid:
            PRECONDITION_FAILURES.append(f"could not create the inactive-recipient fixture: "
                                         f"HTTP {r.status_code}/{err_code(r)}")
            return False, f"create user HTTP {r.status_code}/{err_code(r)}", snippet(r)
        created["SecUser"].append(uid)
        d = c.delete(f"/api/v1/sec/users/{uid}")
        status = field_of(d, "statusCode")
        if d.status_code == 200 and status == "DISABLED":
            ctx["inactive_recipient_id"] = uid
        return (d.status_code == 200 and status == "DISABLED",
                f"user {uid} created (201) and disabled: HTTP {d.status_code}, statusCode={status} "
                f"(want 200/DISABLED)", snippet(d, 150))

    run("inactive SEC recipient fixture (TC-BE-NOTIF-010 precondition)", inactive_recipient_fixture)

    # erp-core 1.2.0: the PERM_NOTIF_* checks are live (SRS §5), so the permission half of
    # TC-BE-NOTIF-014 is arrangeable: a STAFF user created with no role logs in and holds none.
    def no_permission_caller_fixture():
        uname = f"notif-noperm-{RUN_ID}"
        r = c.post("/api/v1/sec/users", {
            "username": uname, "email": f"{uname}@notif-verify.test",
            "fullNameAr": "بلا صلاحيات", "fullNameEn": "No Permission",
            "password": FIXTURE_PASSWORD})
        uid = field_of(r, "userPk")
        if r.status_code != 201 or not uid:
            return False, f"create user HTTP {r.status_code}/{err_code(r)}", snippet(r)
        created["SecUser"].append(uid)
        ctx["noperm_user_id"] = uid
        tok = APIClient(c.base_url).login(uname, FIXTURE_PASSWORD)
        ctx["noperm_token"] = tok
        return (bool(tok), f"user {uid} (no role) created and logged in: token={'yes' if tok else 'no'}",
                snippet(r, 150))

    run("no-permission SEC caller fixture (TC-BE-NOTIF-014 permission half)",
        no_permission_caller_fixture)

    def in_app_channel_state():
        """erp-core 1.2.0: IN_APP is seeded enabled for every tenant (DEVIATIONS [08], V13);
        read only, never mutated — it is the SENT path's channel (see test_dispatch)."""
        r = c.post("/api/v1/notifications/channels/search",
                   {"filters": [{"field": "channelTypeId", "operator": "EQUALS",
                                 "value": CHANNEL_TYPE_IN_APP}], "page": 0, "size": 50})
        content = (data_of(r) or {}).get("content") or []
        mine = [x for x in content if x.get("channelTypeId") == CHANNEL_TYPE_IN_APP]
        enabled = bool(mine) and mine[0].get("isEnabledFl") is True
        ctx["in_app_channel_enabled"] = enabled
        if not enabled:
            PRECONDITION_FAILURES.append("seeded IN_APP channel config missing or disabled — the "
                                         "SENT-path dispatch check cannot run")
        return (r.status_code == 200 and enabled,
                f"seeded IN_APP channel config: present={bool(mine)}, enabled={enabled} "
                f"(read-only, never mutated here)", snippet(r, 200))

    run("pre-existing IN_APP channel config read (not mutated)", in_app_channel_state)

    def email_channel_state():
        """The EMAIL channel config is pre-existing seed data (id 1) this run must not mutate.
        Its enabled state decides what an EMAIL dispatch does, so it is read, never written."""
        r = c.post("/api/v1/notifications/channels/search",
                   {"filters": [{"field": "channelTypeId", "operator": "EQUALS",
                                 "value": CHANNEL_TYPE_EMAIL}], "page": 0, "size": 50})
        content = (data_of(r) or {}).get("content") or []
        mine = [x for x in content if x.get("channelTypeId") == CHANNEL_TYPE_EMAIL]
        if mine:
            ctx["email_channel_enabled"] = mine[0].get("isEnabledFl")
            ctx["email_channel_id"] = mine[0].get("id")
        return (r.status_code == 200,
                f"pre-existing EMAIL channel config: id={ctx.get('email_channel_id')}, "
                f"isEnabledFl={ctx.get('email_channel_enabled')} (read-only, never mutated here)",
                snippet(r, 200))

    run("pre-existing EMAIL channel config read (not mutated)", email_channel_state)


# ══════════════════════════════════════════════════════════════════
# 1. NotificationTemplate  (manifest DEPENDENCY ORDER #1 — parent, independent)
# ══════════════════════════════════════════════════════════════════


def test_template(c: APIClient):
    """Covers: API-NOTIF-004 (templates CRUD + search)
    Negative: RULE-NOTIF-004 / NOTIF_TEMPLATE_BILINGUAL_REQUIRED / TC-BE-NOTIF-006 ;
              RULE-NOTIF-006 / NOTIF_TEMPLATE_CODE_DUPLICATE / TC-BE-NOTIF-009 (template half) ;
              (PLATFORM) / NOTIF_TEMPLATE_NOT_FOUND / TC-BE-NOTIF-013 (404 shape)
    Also: TC-BE-NOTIF-005 (bilingual accepted), TC-BE-NOTIF-008 (unique code accepted),
          TC-BE-NOTIF-014 (CRUD happy)."""
    start_suite("NotificationTemplate")

    body = {
        "templateCode": TEMPLATE_CODE,
        "nameAr": "ترحيب بالمستخدم",
        "nameEn": "User Welcome",
        "subjectAr": "مرحبًا بك",
        "subjectEn": "Welcome",
        "bodyAr": "أهلًا {0}",
        "bodyEn": "Hello {0}",
        "isActiveFl": True,
    }
    # attachmentFileId (api-docs example 1001) is deliberately omitted: it is optional, the FILE
    # cross-module validation is XM-NOTIF-002 DEFERRED, and 1001 is not a verified FILE_DOCUMENT id.

    def create():
        r = c.post("/api/v1/notifications/templates", body)
        tid = field_of(r, "id")
        if tid:
            created["NotificationTemplate"].append(tid)
            ctx["template_id"] = tid
        # ENTITY CRUD CHECKLIST + ServiceResult Status.CREATED -> 201 per the shared
        # Status->HTTP table in api-docs/index.md (the api-docs' own "Response 200" block is
        # springdoc's default, not a declared contract).
        ok = r.status_code in (200, 201) and field_of(r, "templateCode") == TEMPLATE_CODE
        return ok, f"TC-BE-NOTIF-005/008: HTTP {r.status_code}, id={tid}", snippet(r)

    run("TC-BE-NOTIF-005/008 — create template with both bodies and a unique code", create)

    tid = ctx.get("template_id")
    if not tid:
        blocked("TC-BE-NOTIF-014 template CRUD", "create returned no id")
        return

    run("TC-BE-NOTIF-014 — get template by id",
        lambda: expect_status(c.get(f"/api/v1/notifications/templates/{tid}"), 200, "getById"))

    run("TC-BE-NOTIF-013 — unknown template id -> 404 NOTIF_TEMPLATE_NOT_FOUND",
        lambda: expect_error(c.get("/api/v1/notifications/templates/99999999"),
                             404, "NOTIF_TEMPLATE_NOT_FOUND", "getById unknown"))

    def update():
        upd = {k: v for k, v in body.items() if k != "templateCode"}
        upd["nameEn"] = "User Welcome Updated"
        r = c.put(f"/api/v1/notifications/templates/{tid}", upd)
        return (r.status_code == 200 and field_of(r, "nameEn") == "User Welcome Updated",
                f"update: HTTP {r.status_code}", snippet(r))

    run("TC-BE-NOTIF-014 — update template", update)

    def search():
        r = c.post("/api/v1/notifications/templates/search",
                   {"filters": [{"field": "templateCode", "operator": "EQUALS",
                                 "value": TEMPLATE_CODE}], "page": 0, "size": 20})
        d = data_of(r) or {}
        codes = [x.get("templateCode") for x in (d.get("content") or [])]
        return (r.status_code == 200 and TEMPLATE_CODE in codes,
                f"search by this run's own templateCode: HTTP {r.status_code}, "
                f"found={TEMPLATE_CODE in codes}, totalElements={d.get('totalElements')}",
                snippet(r, 200))

    run("TC-BE-NOTIF-014 — search finds this run's template", search)

    # Stage C — RULE-NOTIF-006 / ERR-0002 / TC-BE-NOTIF-009 (template half), 409.
    run("TC-BE-NOTIF-009 — duplicate templateCode -> 409 NOTIF_TEMPLATE_CODE_DUPLICATE",
        lambda: expect_error(c.post("/api/v1/notifications/templates", body),
                             409, "NOTIF_TEMPLATE_CODE_DUPLICATE", "duplicate code"))

    # Stage C — RULE-NOTIF-004 / TC-BE-NOTIF-006, 400, on CREATE and on UPDATE.
    # The governed code ERR-0001 `NOTIF_TEMPLATE_BILINGUAL_REQUIRED` is UNREACHABLE over HTTP,
    # and deliberately so: TemplateCreateRequest/TemplateUpdateRequest both carry @NotBlank on
    # bodyAr and bodyEn, so Spring bean validation refuses at the controller boundary before
    # NotificationTemplateDomain — the throw site of ERR-0001 — is ever entered. The platform's
    # documented mechanism for that refusal is GlobalExceptionHandler.handleValidation: HTTP
    # 400, wire code VALIDATION_ERROR, and a per-field `fieldErrors` entry, which preserves
    # detail the single generic domain code cannot (WHICH body is missing, and every failing
    # field reported at once). Asserting the field name keeps RULE-NOTIF-004 proven: both
    # language bodies are still mandatory, and the refusal still names the missing one.
    def missing_body_en():
        payload = dict(body)
        payload["templateCode"] = f"MISSING_EN_{RUN_ID}"
        payload.pop("bodyEn")
        r = c.post("/api/v1/notifications/templates", payload)
        if r.status_code in (200, 201):
            tid2 = field_of(r, "id")
            if tid2:
                created["NotificationTemplate"].append(tid2)
        return expect_validation_field(r, "bodyEn", "missing bodyEn")

    run("TC-BE-NOTIF-006 (create) — template without bodyEn -> 400 VALIDATION_ERROR naming "
        "`bodyEn` (RULE-NOTIF-004; ERR-0001 NOTIF_TEMPLATE_BILINGUAL_REQUIRED is structurally "
        "unreachable — @NotBlank refuses first)",
        missing_body_en)

    # Same rule on UPDATE — same structural reason, the mirrored @NotBlank on
    # TemplateUpdateRequest.bodyAr, so the Domain re-validation in
    # NotificationTemplateService.update is likewise never reached from HTTP.
    def update_missing_body_ar():
        upd = {k: v for k, v in body.items() if k != "templateCode"}
        upd.pop("bodyAr")
        return expect_validation_field(
            c.put(f"/api/v1/notifications/templates/{tid}", upd),
            "bodyAr", "update without bodyAr")

    run("TC-BE-NOTIF-006 (update) — update dropping bodyAr -> 400 VALIDATION_ERROR naming "
        "`bodyAr` (RULE-NOTIF-004; ERR-0001 NOTIF_TEMPLATE_BILINGUAL_REQUIRED is structurally "
        "unreachable — @NotBlank refuses first)",
        update_missing_body_ar)

    # A second template, deactivated on purpose, so the dispatch suite can exercise the
    # documented NOTIF_TEMPLATE_INACTIVE path without retiring the main fixture.
    def create_inactive_fixture():
        payload = dict(body)
        payload["templateCode"] = TEMPLATE_CODE_INACTIVE
        r = c.post("/api/v1/notifications/templates", payload)
        tid2 = field_of(r, "id")
        if tid2:
            created["NotificationTemplate"].append(tid2)
            ctx["template_inactive_id"] = tid2
            d = c.delete(f"/api/v1/notifications/templates/{tid2}")
            ctx["template_inactive_deactivated"] = d.status_code == 204
            return (r.status_code in (200, 201) and d.status_code == 204,
                    f"create HTTP {r.status_code}, deactivate HTTP {d.status_code} (want 204)",
                    snippet(d))
        return False, f"create failed HTTP {r.status_code}", snippet(r)

    run("TC-BE-NOTIF-014 — deactivate template returns 204 (soft, isActiveFl flipped)",
        create_inactive_fixture)

    def deactivated_is_readable():
        tid2 = ctx.get("template_inactive_id")
        r = c.get(f"/api/v1/notifications/templates/{tid2}")
        return (r.status_code == 200 and field_of(r, "isActiveFl") is False,
                f"deactivated template still readable with isActiveFl="
                f"{field_of(r, 'isActiveFl')} (soft delete per api-verify-config.md §3)",
                snippet(r))

    if ctx.get("template_inactive_id"):
        run("TC-BE-NOTIF-014 — DELETE is soft: the row survives with isActiveFl=false",
            deactivated_is_readable)

    # ── Stage E observations (required/constrained fields only) ──
    def over_length_code():
        payload = dict(body)
        payload["templateCode"] = ("C" * 81)          # maxLength 80
        r = c.post("/api/v1/notifications/templates", payload)
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationTemplate"].append(field_of(r, "id"))
        return True, f"templateCode at 81 chars (max 80) -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run_observation("stage E — templateCode one over its documented maxLength(80)", over_length_code)

    def deactivate_twice():
        tid2 = ctx.get("template_inactive_id")
        r = c.delete(f"/api/v1/notifications/templates/{tid2}")
        return True, f"second DELETE on an already-deactivated template -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    if ctx.get("template_inactive_id"):
        run_observation("stage E — DELETE idempotency on an already-deactivated template",
                        deactivate_twice)

    def unknown_sort_field():
        r = c.post("/api/v1/notifications/templates/search",
                   {"sortField": "notASortableField", "sortDirection": "ASC",
                    "page": 0, "size": 5})
        return True, f"unknown sortField -> HTTP {r.status_code}/{err_code(r)}", snippet(r, 200)

    run_observation("stage E — an undocumented sortField on template search", unknown_sort_field)

    def over_max_page_size():
        r = c.post("/api/v1/notifications/templates/search", {"page": 0, "size": 201})
        d = data_of(r) or {}
        return True, (f"size=201 (PageableBuilder max 200) -> HTTP {r.status_code}, "
                      f"returned size={d.get('size')}"), snippet(r, 150)

    run_observation("stage E — page size one over the documented maximum (200)", over_max_page_size)


# ══════════════════════════════════════════════════════════════════
# 2. NotificationChannelConfig  (manifest DEPENDENCY ORDER #2 — parent, independent)
# ══════════════════════════════════════════════════════════════════


def test_channel(c: APIClient):
    """Covers: API-NOTIF-005 (channels CRUD / enable-disable / search)
    Negative: RULE-NOTIF-006 / NOTIF_CHANNEL_CONFIG_DUPLICATE / TC-BE-NOTIF-009 (channel half) ;
              (PLATFORM) / NOTIF_CHANNEL_CONFIG_NOT_FOUND / TC-BE-NOTIF-013 (404 shape)
    Also: TC-BE-NOTIF-008 (unique channelTypeId accepted), TC-BE-NOTIF-015 (CRUD/enable)."""
    start_suite("NotificationChannelConfig")

    def create():
        global CHANNEL_TYPE_ENABLED
        taken = []
        for candidate in CHANNEL_TYPE_CANDIDATES:
            if candidate not in (ctx.get("channel_codes") or []):
                continue                      # not an active LOV-NOTIF-001 value on this target
            r = c.post("/api/v1/notifications/channels",
                       {"channelTypeId": candidate, "isEnabledFl": True})
            cid = field_of(r, "id")
            if r.status_code in (200, 201) and cid:
                CHANNEL_TYPE_ENABLED = candidate
                created["NotificationChannelConfig"].append(cid)
                ctx["channel_id"] = cid
                ctx["channel_created_by_this_run"] = True
                return (True,
                        f"TC-BE-NOTIF-008: HTTP {r.status_code}, id={cid}, "
                        f"channelTypeId={candidate}"
                        + (f" (skipped {taken}, already present from an earlier run)" if taken else ""),
                        snippet(r))
            if r.status_code == 409:
                taken.append(candidate)       # a previous run owns it; never mutated here
                continue
            return False, f"{candidate}: HTTP {r.status_code}/{err_code(r)}", snippet(r)
        PRECONDITION_FAILURES.append(
            f"every documented LOV-NOTIF-001 channel type {taken} already has a config row left "
            f"behind by an earlier run; this run will not mutate a record it did not create, so "
            f"the SENT-path dispatch checks are blocked. Purge them "
            f"(DELETE FROM NOTIF_CHANNEL_CONFIG WHERE CHANNEL_TYPE_ID IN ...) and rerun.")
        return False, f"no ownable channel type left (409 on {taken})", ""

    run("TC-BE-NOTIF-008 — create a channel config this run owns (enabled)", create)

    cid = ctx.get("channel_id")

    # Stage C — RULE-NOTIF-006 / ERR-0003 / TC-BE-NOTIF-009 (channel half), 409.
    # Uses the pre-existing seeded EMAIL config as the duplicate subject — a read-only collision,
    # nothing is written.
    run("TC-BE-NOTIF-009 — duplicate channelTypeId -> 409 NOTIF_CHANNEL_CONFIG_DUPLICATE",
        lambda: expect_error(
            c.post("/api/v1/notifications/channels",
                   {"channelTypeId": CHANNEL_TYPE_EMAIL, "isEnabledFl": True}),
            409, "NOTIF_CHANNEL_CONFIG_DUPLICATE", "duplicate channelTypeId"))

    run("TC-BE-NOTIF-013 — unknown channel id -> 404 NOTIF_CHANNEL_CONFIG_NOT_FOUND",
        lambda: expect_error(c.get("/api/v1/notifications/channels/99999999"),
                             404, "NOTIF_CHANNEL_CONFIG_NOT_FOUND", "getById unknown"))

    if not cid:
        blocked("TC-BE-NOTIF-015 channel CRUD", "no channel config created by this run")
        return

    run("TC-BE-NOTIF-015 — get channel config by id",
        lambda: expect_status(c.get(f"/api/v1/notifications/channels/{cid}"), 200, "getById"))

    def update():
        r = c.put(f"/api/v1/notifications/channels/{cid}",
                  {"isEnabledFl": True, "configJson": '{"provider":"stub"}'})
        return (r.status_code == 200 and field_of(r, "isEnabledFl") is True,
                f"update configJson: HTTP {r.status_code}, isEnabledFl={field_of(r, 'isEnabledFl')}",
                snippet(r))

    run("TC-BE-NOTIF-015 — update channel config", update)

    def search():
        r = c.post("/api/v1/notifications/channels/search",
                   {"filters": [{"field": "channelTypeId", "operator": "EQUALS",
                                 "value": CHANNEL_TYPE_ENABLED}], "page": 0, "size": 20})
        d = data_of(r) or {}
        ids = [x.get("id") for x in (d.get("content") or [])]
        return (r.status_code == 200 and cid in ids,
                f"search by this run's own channelTypeId: HTTP {r.status_code}, found={cid in ids}",
                snippet(r, 200))

    run("TC-BE-NOTIF-015 — search finds this run's channel config", search)

    # ── Stage E observations ──
    def over_length_channel_type():
        r = c.post("/api/v1/notifications/channels",
                   {"channelTypeId": "C" * 21, "isEnabledFl": True})   # maxLength 20
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationChannelConfig"].append(field_of(r, "id"))
        return True, f"channelTypeId at 21 chars (max 20) -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run_observation("stage E — channelTypeId one over its documented maxLength(20)",
                    over_length_channel_type)

    def missing_channel_type():
        r = c.post("/api/v1/notifications/channels", {"isEnabledFl": True})
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationChannelConfig"].append(field_of(r, "id"))
        return True, (f"required channelTypeId omitted -> HTTP {r.status_code}/{err_code(r)} "
                      f"(NOTIF_CHANNEL_TYPE_REQUIRED is the module's own code for this)"), snippet(r)

    run_observation("stage E — required channelTypeId omitted on create", missing_channel_type)

    def undocumented_channel_value():
        # An LOV-NOTIF-001 value that the NOTIF_CHANNEL lookup does not carry.
        code = f"ZZ{RUN_ID}"
        r = c.post("/api/v1/notifications/channels", {"channelTypeId": code, "isEnabledFl": False})
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationChannelConfig"].append(field_of(r, "id"))
            ctx["undocumented_channel_code"] = code
        return True, (f"channelTypeId '{code}' is not an active NOTIF_CHANNEL lookup value -> "
                      f"HTTP {r.status_code}/{err_code(r)}"), snippet(r)

    run_observation("stage E — a channelTypeId outside the NOTIF_CHANNEL lookup",
                    undocumented_channel_value)


# ══════════════════════════════════════════════════════════════════
# 3. Dispatch + NotificationLog  (manifest DEPENDENCY ORDER #3 — FK TEMPLATE_FK)
# ══════════════════════════════════════════════════════════════════


def test_dispatch(c: APIClient):
    """Covers: API-NOTIF-001 (dispatch)
    Negative/behavioural: RULE-NOTIF-001 (fan-out) TC-BE-NOTIF-001 ;
                          RULE-NOTIF-003 (CHANNEL_DISABLED) TC-BE-NOTIF-004 ;
                          (PLATFORM) NOTIF_TEMPLATE_NOT_FOUND TC-BE-NOTIF-013 ;
                          TC-BE-NOTIF-011 (202/{logIds}), TC-BE-NOTIF-015 (toggle affects dispatch),
                          TC-BE-NOTIF-016 (SQLi stored literal).
    Retry cases TC-BE-NOTIF-002/003 are recorded as observations — see the report."""
    start_suite("Dispatch")

    tid = ctx.get("template_id")
    rid = ctx.get("recipient_id")
    if not tid or not rid:
        blocked("TC-BE-NOTIF-001/011", "no active template or no verified recipient")
        return

    base = {
        "recipientId": rid,
        "templateCode": TEMPLATE_CODE,
        "moduleCode": MODULE_CODE,
        "referenceId": REFERENCE_ID,
        "referenceType": REFERENCE_TYPE,
        # erp-core 1.2.0: an EMAIL without `variables.email` is now addressed to the recipient's
        # account e-mail (DEVIATIONS [14], BP#6), so omitting `variables` no longer keeps this run
        # from mailing a real address on a mail-enabled target. The documented override is used
        # instead, with a reserved never-deliverable domain (RFC 2606 `.invalid`), which keeps the
        # original intent: this run never sends mail to a real mailbox.
        "variables": {"email": f"notif-verify-{RUN_ID}@example.invalid"},
    }

    def fan_out():
        """TC-BE-NOTIF-001 — exactly one NOTIF_LOG per requested channel."""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        ctx["fanout_log_ids"] = ids
        # The test plan states 202; the api-docs (and the shared Status->HTTP table) state 200.
        # Asserted against the api-docs, which api-verify-config.md §1 makes authoritative.
        return (r.status_code == 200 and len(ids) == 2,
                f"HTTP {r.status_code} (test plan says 202, api-docs say 200), "
                f"logIds={ids} (want exactly 2, one per requested channel)", snippet(r))

    run("TC-BE-NOTIF-001/011 — dispatch fans out one log per channelHint entry", fan_out)

    # erp-core 1.2.0: "the enabled channel this run created must reach SENT" no longer holds by
    # design — core ships real providers only for EMAIL (with a mail sender) and IN_APP; any other
    # enabled channel without an application ChannelProvider ends SKIPPED_NO_PROVIDER (reason
    # NOTIF_CHANNEL_UNAVAILABLE) instead of faking success — DEVIATIONS [08] (LoggingChannelProvider,
    # EmailChannelProvider entries), BP#4, PRD addendum US-NOTIF-004; core-test-plan TC-CORE-NOTIF-004.
    # TC-BE-NOTIF-015's intent (an enabled, provider-backed channel delivers) is therefore checked on
    # the seeded IN_APP channel, and the run-owned enabled channel's new outcome is asserted on its own.
    def sent_path():
        """An enabled, provider-backed channel (IN_APP) reaches SENT, polled to its final status."""
        if not ctx.get("in_app_channel_enabled"):
            return False, "BLOCKED: the seeded IN_APP channel is missing or disabled", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_IN_APP]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        ctx["sent_log_id"] = ids[0] if ids else None
        if not ids:
            return False, f"HTTP {r.status_code}, no logIds returned", snippet(r)
        g = wait_final_log(c, ids[0])
        status = field_of(g, "notificationStatusId")
        return (r.status_code == 200 and status == "SENT" and field_of(g, "sentAt") is not None,
                f"log {ids[0]} notificationStatusId={status} (want SENT), attempts="
                f"{field_of(g, 'attempts')}, retryCount={field_of(g, 'retryCount')}, "
                f"sentAt={field_of(g, 'sentAt')}", snippet(g))

    run("TC-BE-NOTIF-015 — dispatch over an enabled, provider-backed channel (IN_APP) reaches SENT",
        sent_path)

    # erp-core 1.2.0: the IN_APP provider's delivery is the recipient's inbox item; the recipient
    # is the caller (preflight), so the item must be in the caller's own inbox — DEVIATIONS [08]
    # (inbox entries), SRS §1; core-test-plan TC-CORE-NOTIF-007.
    def sent_path_inbox():
        lid = ctx.get("sent_log_id")
        if not lid:
            return False, "BLOCKED: no IN_APP log from the SENT-path dispatch", ""
        if ctx.get("recipient_id") != ctx.get("caller_user_id"):
            return False, "BLOCKED: the recipient is not the caller, its inbox is not readable", ""
        r = c.get("/api/v1/notif/inbox", params={"unreadOnly": "true", "page": 0, "size": 100})
        items = (data_of(r) or {}).get("content") or []
        mine = [x for x in items if x.get("referenceType") == REFERENCE_TYPE
                and x.get("recipientUserId") == ctx.get("recipient_id")]
        return (r.status_code == 200 and len(mine) >= 1,
                f"HTTP {r.status_code}, unread inbox items with this run's referenceType="
                f"{len(mine)} (want >= 1)", snippet(r, 250))

    run("TC-BE-NOTIF-015 — the IN_APP SENT row is in the recipient's inbox", sent_path_inbox)

    def enabled_without_provider():
        """The run-owned enabled channel (no provider in core) ends SKIPPED_NO_PROVIDER."""
        if not ctx.get("channel_created_by_this_run"):
            return False, "BLOCKED: this run created no enabled channel config", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return False, f"HTTP {r.status_code}, no logIds returned", snippet(r)
        g = wait_final_log(c, ids[0])
        status = field_of(g, "notificationStatusId")
        last_error = field_of(g, "lastError")
        return (r.status_code == 200 and status == "SKIPPED_NO_PROVIDER"
                and last_error == "NOTIF_CHANNEL_UNAVAILABLE",
                f"{CHANNEL_TYPE_ENABLED} log {ids[0]} notificationStatusId={status} (want "
                f"SKIPPED_NO_PROVIDER), lastError={last_error!r} (want 'NOTIF_CHANNEL_UNAVAILABLE'), "
                f"attempts={field_of(g, 'attempts')}", snippet(g))

    if ctx.get("channel_created_by_this_run"):
        run("TC-BE-NOTIF-015 — dispatch over an enabled channel with no provider ends "
            "SKIPPED_NO_PROVIDER", enabled_without_provider)
    else:
        blocked("TC-BE-NOTIF-015 — dispatch over an enabled channel with no provider ends "
                "SKIPPED_NO_PROVIDER", "no enabled channel config owned by this run")

    def disabled_channel():
        """TC-BE-NOTIF-004 / TC-BE-NOTIF-015 — flipping isEnabledFl changes the dispatch outcome."""
        cid = ctx.get("channel_id")
        if not cid:
            return False, "BLOCKED: no channel config owned by this run", ""
        d = c.delete(f"/api/v1/notifications/channels/{cid}")      # documented "disable"
        if d.status_code != 204:
            return False, f"disable endpoint returned HTTP {d.status_code}", snippet(d)
        ctx["channel_disabled"] = True
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return False, f"HTTP {r.status_code}, no logIds returned", snippet(r)
        # CHANNEL_DISABLED is decided synchronously at dispatch and is final, so it is read at
        # once (no polling) — that also proves the row was never QUEUED.
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        status = field_of(g, "notificationStatusId")
        retry = field_of(g, "retryCount")
        # erp-core 1.2.0: + `attempts` (V13) — a CHANNEL_DISABLED row is never queued, so 0
        # attempts — DEVIATIONS [08] (state machine, Task 1 columns); core-test-plan TC-CORE-NOTIF-005.
        attempts = field_of(g, "attempts")
        return (status == "CHANNEL_DISABLED" and retry == 0 and attempts == 0,
                f"log {ids[0]} notificationStatusId={status} (want CHANNEL_DISABLED), "
                f"retryCount={retry}, attempts={attempts} (want 0/0 — no retry, no provider call)",
                snippet(g))

    run("TC-BE-NOTIF-004/015 — a disabled channel yields CHANNEL_DISABLED with no retry",
        disabled_channel)

    run("TC-BE-NOTIF-013 — dispatch with an unknown templateCode -> 404 NOTIF_TEMPLATE_NOT_FOUND",
        lambda: expect_error(
            c.post("/api/v1/notifications/dispatch",
                   dict(base, templateCode=f"NO_SUCH_TEMPLATE_{RUN_ID}",
                        channelHint=[CHANNEL_TYPE_ENABLED])),
            404, "NOTIF_TEMPLATE_NOT_FOUND", "unknown templateCode"))

    def inactive_template():
        """NOTIF_TEMPLATE_INACTIVE — 422 BUSINESS_RULE_VIOLATION per api-docs Known Error Codes."""
        if not ctx.get("template_inactive_deactivated"):
            return False, "BLOCKED: no deactivated template fixture", ""
        return expect_error(
            c.post("/api/v1/notifications/dispatch",
                   dict(base, templateCode=TEMPLATE_CODE_INACTIVE,
                        channelHint=[CHANNEL_TYPE_ENABLED])),
            422, "NOTIF_TEMPLATE_INACTIVE", "dispatch on a deactivated template")

    run("TC-BE-NOTIF-014 — dispatch on a deactivated template -> 422 NOTIF_TEMPLATE_INACTIVE",
        inactive_template)

    def sqli_module_code():
        """TC-BE-NOTIF-016 — the SQLi string is stored as a literal and the DB stays intact."""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, moduleCode=SQLI_MODULE_CODE, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return False, f"HTTP {r.status_code}/{err_code(r)}, no logIds", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        stored = field_of(g, "moduleCode")
        # DB intact: the lookup endpoint still resolves its five channel values afterwards.
        lk = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        intact = lk.status_code == 200 and len(data_of(lk) or []) == len(ctx.get("channel_codes") or [])
        return (stored == SQLI_MODULE_CODE and intact,
                f"moduleCode stored as {stored!r} (literal); lookups still resolve "
                f"{len(data_of(lk) or [])} values -> DB intact={intact}", snippet(g, 200))

    run("TC-BE-NOTIF-016 — SQLi moduleCode stored as a literal, DB intact", sqli_module_code)

    # ── Retry behaviour — TC-BE-NOTIF-002 / TC-BE-NOTIF-003 ──
    # The HTTP surface exposes no documented way to make a provider fail a chosen number of times,
    # so neither "fails twice then succeeds" (TC-002) nor "fails 6 times" (TC-003) can be arranged
    # as written. Recorded, never asserted.
    # erp-core 1.2.0: the old arrangement (EMAIL with no address -> FAILED after retries) is gone by
    # design — an absent `variables.email` falls back to the recipient's account e-mail, which SEC
    # makes mandatory, and an EMAIL with no address at all is now REJECTED -> FAILED after ONE
    # attempt, never retried (DEVIATIONS [14], BP#6); without a mail sender EMAIL ends
    # SKIPPED_NO_PROVIDER (DEVIATIONS [08]). The observation now records the EMAIL row's final
    # status (polled), whatever the target's mail configuration makes it.
    def failed_branch():
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_EMAIL]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return True, f"HTTP {r.status_code}/{err_code(r)}, no logIds", snippet(r)
        g = wait_final_log(c, ids[0])
        return True, (f"EMAIL dispatch (override address @example.invalid) -> log {ids[0]} final "
                      f"notificationStatusId={field_of(g, 'notificationStatusId')}, "
                      f"attempts={field_of(g, 'attempts')}, retryCount={field_of(g, 'retryCount')}, "
                      f"lastError={field_of(g, 'lastError')!r}, "
                      f"errorMessage={field_of(g, 'errorMessage')!r}"), snippet(g, 250)

    run_observation("stage E — EMAIL final status (TC-BE-NOTIF-003 is not arrangeable as written)",
                    failed_branch)

    # erp-core 1.2.0: upgraded from an observation to an assertion — RULE-NOTIF-007 is implemented
    # (the recipient-active check reads SEC through RecipientDirectory; XM-NOTIF-001 is no longer
    # DEFERRED), so a dispatch to a DISABLED account creates no log — BP#7, SRS §2, DEVIATIONS [06],
    # [08]; core-test-plan TC-CORE-NOTIF-011.
    def inactive_recipient():
        """TC-BE-NOTIF-010 — RULE-NOTIF-007: no log for an inactive recipient."""
        bad = ctx.get("inactive_recipient_id")
        if not bad:
            return False, "BLOCKED: no inactive SEC user fixture", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, recipientId=bad, channelHint=[CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_IN_APP]))
        ids = (data_of(r) or {}).get("logIds")
        created["NotificationLog"].extend(ids or [])
        s_ = c.post("/api/v1/notifications/logs/search",
                    {"filters": [{"field": "recipientId", "operator": "EQUALS", "value": bad}],
                     "page": 0, "size": 20})
        rows = (data_of(s_) or {}).get("content")
        return (r.status_code == 200 and ids == [] and s_.status_code == 200 and rows == [],
                f"dispatch to inactive SEC user {bad} -> HTTP {r.status_code}, logIds={ids} "
                f"(want []); log search by recipientId -> {len(rows or [])} row(s) (want 0)",
                snippet(r))

    run("TC-BE-NOTIF-010 — dispatch to an inactive recipient creates no log (RULE-NOTIF-007)",
        inactive_recipient)

    def unconfigured_channel():
        other = next((x for x in (ctx.get("channel_codes") or [])
                      if x not in (CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_ENABLED)), None)
        if not other:
            return True, "no other LOV-NOTIF-001 value available to try", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[other]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return True, f"HTTP {r.status_code}/{err_code(r)}, no logIds", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        return True, (f"{other}: a valid NOTIF_CHANNEL value with no channel config row of its own -> "
                      f"notificationStatusId={field_of(g, 'notificationStatusId')}"), snippet(g, 200)

    run_observation("stage E — dispatch over a lookup-valid but unconfigured channel",
                    unconfigured_channel)

    def unknown_channel_hint():
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[f"NOPE{RUN_ID}"]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, (f"channelHint value outside the NOTIF_CHANNEL lookup -> "
                      f"HTTP {r.status_code}/{err_code(r)}, logIds={ids}"), snippet(r)

    run_observation("stage E — channelHint value that is not an LOV-NOTIF-001 code",
                    unknown_channel_hint)

    def empty_channel_hint():
        r = c.post("/api/v1/notifications/dispatch", dict(base, channelHint=[]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, (f"required channelHint sent empty -> HTTP {r.status_code}/{err_code(r)}, "
                      f"logIds={ids}"), snippet(r)

    run_observation("stage E — required channelHint present but empty", empty_channel_hint)

    def missing_recipient():
        payload = dict(base, channelHint=[CHANNEL_TYPE_ENABLED])
        payload.pop("recipientId")
        r = c.post("/api/v1/notifications/dispatch", payload)
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, f"required recipientId omitted -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run_observation("stage E — required recipientId omitted", missing_recipient)


# ══════════════════════════════════════════════════════════════════
# 4. NotificationLog queries  (read-only screen — API-NOTIF-002 / 003)
# ══════════════════════════════════════════════════════════════════


def test_logs(c: APIClient):
    """Covers: API-NOTIF-002 (search), API-NOTIF-003 (get by id)
    Negative: (PLATFORM) / NOTIF_LOG_NOT_FOUND / TC-BE-NOTIF-013
    Also: TC-BE-NOTIF-012 (happy + empty page)."""
    start_suite("NotificationLog")

    def search_own():
        """Run-scoped: filters on this run's own referenceType, never a global count."""
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "referenceType", "operator": "EQUALS",
                                 "value": REFERENCE_TYPE}],
                    "sortField": "createdAt", "sortDirection": "DESC", "page": 0, "size": 200})
        d = data_of(r) or {}
        content = d.get("content") or []
        mine = {x.get("id") for x in content}
        expected = {i for i in created["NotificationLog"] if i}
        missing = expected - mine
        return (r.status_code == 200 and not missing,
                f"HTTP {r.status_code}, totalElements={d.get('totalElements')} for this run's "
                f"referenceType; {len(expected)} log(s) created, missing from search={missing or 'none'}",
                snippet(r, 200))

    run("TC-BE-NOTIF-012 — log search returns every log this run created", search_own)

    def paging_envelope():
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "referenceType", "operator": "EQUALS",
                                 "value": REFERENCE_TYPE}], "page": 0, "size": 20})
        d = data_of(r) or {}
        documented = ["totalPages", "totalElements", "numberOfElements", "first", "last",
                      "pageable", "sort", "size", "number", "empty", "content"]
        missing = [f for f in documented if f not in d]
        return (r.status_code == 200 and not missing,
                f"paging envelope fields missing={missing or 'none'} "
                f"(documented in api-docs/index.md 'Pagination Envelope')", snippet(r, 200))

    run("TC-BE-NOTIF-012 — the paging envelope carries every documented field", paging_envelope)

    def empty_page():
        """MANDATORY-J-7 — a filter matching nothing is a 200 empty page, never a 404."""
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "referenceType", "operator": "EQUALS",
                                 "value": f"NO_SUCH_REFERENCE_{RUN_ID}"}], "page": 0, "size": 20})
        d = data_of(r) or {}
        return (r.status_code == 200 and d.get("content") == [] and d.get("empty") is True,
                f"HTTP {r.status_code}, content={d.get('content')}, empty={d.get('empty')} "
                f"(want 200 / [] / true)", snippet(r, 200))

    run("TC-BE-NOTIF-012 — a filter matching nothing returns a 200 empty page", empty_page)

    def get_by_id():
        """TC-BE-NOTIF-013 — the response carries errorMessage and retryCount."""
        lid = next((i for i in created["NotificationLog"] if i), None)
        if not lid:
            return False, "BLOCKED: this run created no log", ""
        r = c.get(f"/api/v1/notifications/logs/{lid}")
        d = data_of(r) or {}
        required = ["id", "recipientId", "channelTypeId", "notificationStatusId", "moduleCode",
                    "retryCount", "errorMessage", "templateId",
                    # erp-core 1.2.0: responses gain attempts / nextAttemptAt / lastError —
                    # SRS §1 (API-NOTIF-002/003 CHANGED), DEVIATIONS [08] (Task 1 columns).
                    "attempts", "nextAttemptAt", "lastError"]
        missing = [f for f in required if f not in d]
        # erp-core 1.2.0: the dispatch variables (may carry single-use link tokens) are never
        # exposed by the API — BP#8, SRS §2, DEVIATIONS [08] (VARIABLES_JSON entry).
        leaked = [f for f in ("variables", "variablesJson") if f in d]
        return (r.status_code == 200 and not missing and not leaked,
                f"HTTP {r.status_code} for log {lid}; documented fields missing={missing or 'none'}; "
                f"variables exposed={leaked or 'none'}",
                snippet(r, 250))

    run("TC-BE-NOTIF-013 — get log by id returns the documented shape (incl. retryCount, errorMessage)",
        get_by_id)

    run("TC-BE-NOTIF-013 — unknown log id -> 404 NOTIF_LOG_NOT_FOUND",
        lambda: expect_error(c.get("/api/v1/notifications/logs/99999999"),
                             404, "NOTIF_LOG_NOT_FOUND", "getById unknown"))

    # ── Stage E observations ──
    def sqli_filter_value():
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "moduleCode", "operator": "EQUALS",
                                 "value": SQLI_MODULE_CODE}], "page": 0, "size": 20})
        d = data_of(r) or {}
        return True, (f"SQLi string as a filter value -> HTTP {r.status_code}, "
                      f"totalElements={d.get('totalElements')} (parameterised, not executed)"), snippet(r, 150)

    run_observation("stage E — SQLi payload used as a log-search filter value", sqli_filter_value)

    def undocumented_filter_field():
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "errorMessage", "operator": "LIKE", "value": "x"}],
                    "page": 0, "size": 5})
        d = data_of(r) or {}
        return True, (f"a response field that is not in the filter whitelist -> "
                      f"HTTP {r.status_code}/{err_code(r)}, totalElements={d.get('totalElements')}"), snippet(r, 150)

    run_observation("stage E — filtering on an undocumented (non-whitelisted) field",
                    undocumented_filter_field)


# ══════════════════════════════════════════════════════════════════
# 5. Lookups  (API-NOTIF-006)
# ══════════════════════════════════════════════════════════════════


def test_lookups(c: APIClient):
    """Covers: API-NOTIF-006
    Negative: (PLATFORM) / NOTIF_LOOKUP_KEY_UNKNOWN / TC-BE-NOTIF-013 (ERR-0004 shape)
    Also: TC-BE-NOTIF-016 (lookups happy + SQLi)."""
    start_suite("Lookups")

    def channel_lookup():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        vals = data_of(r) or []
        shaped = all(set(v) >= {"code", "labelAr", "labelEn"} for v in vals) if vals else False
        return (r.status_code == 200 and shaped,
                f"HTTP {r.status_code}, {len(vals)} option(s), every option carries "
                f"code/labelAr/labelEn = {shaped}", snippet(r, 200))

    run(f"TC-BE-NOTIF-016 — GET lookups/{LOOKUP_CHANNEL} returns bilingual options", channel_lookup)

    def status_lookup():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_STATUS}")
        vals = data_of(r) or []
        return (r.status_code == 200 and len(vals) > 0,
                f"HTTP {r.status_code}, {len(vals)} option(s)", snippet(r, 200))

    run(f"TC-BE-NOTIF-016 — GET lookups/{LOOKUP_STATUS} returns bilingual options", status_lookup)

    run("TC-BE-NOTIF-013 — unknown lookupKey -> 404 NOTIF_LOOKUP_KEY_UNKNOWN",
        lambda: expect_error(c.get(f"/api/v1/notifications/lookups/NO_SUCH_KEY_{RUN_ID}"),
                             404, "NOTIF_LOOKUP_KEY_UNKNOWN", "unknown lookupKey"))

    def sqli_lookup_key():
        r = c.get("/api/v1/notifications/lookups/" + requests.utils.quote(SQLI_MODULE_CODE, safe=""))
        after = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        intact = after.status_code == 200 and len(data_of(after) or []) == len(ctx.get("channel_codes") or [])
        return (r.status_code == 404 and intact,
                f"SQLi as the lookupKey -> HTTP {r.status_code}/{err_code(r)} "
                f"(want 404, the module rejects keys it does not own); DB intact={intact}",
                snippet(r, 200))

    run("TC-BE-NOTIF-016 — SQLi as lookupKey is rejected and the lookup data stays intact",
        sqli_lookup_key)


# ══════════════════════════════════════════════════════════════════
# 6. Authorization  (RULE-NOTIF-005 — delegated to the Security filter)
# ══════════════════════════════════════════════════════════════════


def test_authorization(c: APIClient):
    """Covers: TC-BE-NOTIF-007 (no/invalid JWT -> 401 from the Security filter),
    and the permission half of TC-BE-NOTIF-014."""
    start_suite("Authorization (RULE-NOTIF-005)")

    run("TC-BE-NOTIF-007 — log search with no JWT -> 401",
        lambda: expect_status(
            c.post("/api/v1/notifications/logs/search", {"page": 0, "size": 5}, anonymous=True),
            401, "anonymous log search"))

    run("TC-BE-NOTIF-007 — log search with an invalid JWT -> 401",
        lambda: expect_status(
            c.post("/api/v1/notifications/logs/search", {"page": 0, "size": 5},
                   token="not.a.valid.token"),
            401, "invalid-JWT log search"))

    run("TC-BE-NOTIF-007 — dispatch with no JWT -> 401",
        lambda: expect_status(
            c.post("/api/v1/notifications/dispatch", {}, anonymous=True), 401, "anonymous dispatch"))

    run("TC-BE-NOTIF-007 — lookups with no JWT -> 401",
        lambda: expect_status(
            c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}", anonymous=True),
            401, "anonymous lookup"))

    run("TC-BE-NOTIF-007 — templates with no JWT -> 401",
        lambda: expect_status(
            c.get("/api/v1/notifications/templates/1", anonymous=True), 401, "anonymous template read"))

    # erp-core 1.2.0: the permission half of TC-BE-NOTIF-014 (a GAP before: every PERM_NOTIF_* check
    # was commented out as SEC-PENDING) is now live — templates/channels/logs require
    # PERM_NOTIF_TEMPLATES_VIEW / PERM_NOTIF_CHANNELS_VIEW / PERM_NOTIF_LOG_VIEW, refused by the
    # shared handler as 403 ACCESS_DENIED — SRS §1 / §5, DEVIATIONS [06]; docs/api-docs/notif/index.md
    # (Known Error Codes: ACCESS_DENIED 403).
    tok = ctx.get("noperm_token")
    tid = ctx.get("template_id") or 1
    for label, method, path in (
            ("template read", "GET", f"/api/v1/notifications/templates/{tid}"),
            ("template search", "POST", "/api/v1/notifications/templates/search"),
            ("channel search", "POST", "/api/v1/notifications/channels/search"),
            ("log search", "POST", "/api/v1/notifications/logs/search")):
        name = f"TC-BE-NOTIF-014 — {label} by a user without PERM_NOTIF_* -> 403 ACCESS_DENIED"
        if not tok:
            blocked(name, "no no-permission caller token (fixture failed)")
            continue
        if method == "GET":
            run(name, lambda p=path, w=label: expect_error(c.get(p, token=tok), 403, "ACCESS_DENIED", w))
        else:
            run(name, lambda p=path, w=label: expect_error(
                c.post(p, {"page": 0, "size": 5}, token=tok), 403, "ACCESS_DENIED", w))


# ══════════════════════════════════════════════════════════════════
# Stage F — teardown
# ══════════════════════════════════════════════════════════════════


def cleanup(c: APIClient):
    """Reverse of the manifest's DEPENDENCY ORDER (log -> channel -> template).
    NOTIF documents NO hard-delete endpoint for any entity, so every call below is the
    documented soft deactivate/disable and the rows survive — listed individually in the
    report, never summarised as 'cleaned up'."""
    print("\n=== CLEANUP (reverse dependency order) ===")

    log_ids = [i for i in created["NotificationLog"] if i]
    if log_ids:
        LEFT_BEHIND.append(
            f"NotificationLog: {len(log_ids)} row(s) {log_ids} — the ENTITY CRUD CHECKLIST marks "
            f"NOTIF_LOG a read-only screen with no delete and no deactivate endpoint, so they "
            f"survive. All carry referenceType='{REFERENCE_TYPE}'. "
            f"Cleanup SQL: DELETE FROM NOTIF_LOG WHERE REFERENCE_TYPE = '{REFERENCE_TYPE}';")

    for cid in [i for i in created["NotificationChannelConfig"] if i]:
        try:
            r = c.delete(f"/api/v1/notifications/channels/{cid}")
            print(f"  disable channel {cid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  disable channel {cid} FAILED: {e}")
    if [i for i in created["NotificationChannelConfig"] if i]:
        PERMANENT_RESIDUE.append(
            f"NOTIF_CHANNEL_CONFIG rows {[i for i in created['NotificationChannelConfig'] if i]} "
            f"(channelTypeId "
            f"{[CHANNEL_TYPE_ENABLED, ctx.get('undocumented_channel_code')]}) — disabled via the "
            f"documented DELETE, but the rows persist and CHANNEL_TYPE_ID is UNIQUE, so a later "
            f"run creating the same channel type gets 409. This table is read by dispatch for "
            f"every module that sends a notification. "
            f"Cleanup SQL: DELETE FROM NOTIF_CHANNEL_CONFIG WHERE CHANNEL_TYPE_ID IN "
            f"('{CHANNEL_TYPE_ENABLED}', '{ctx.get('undocumented_channel_code')}');")

    # erp-core 1.2.0: SEC fixture users created by preflight — disabled via SEC's documented
    # DELETE (soft: status DISABLED); the inactive-recipient fixture is already disabled.
    sec_users = [i for i in created["SecUser"] if i]
    for uid in sec_users:
        if uid == ctx.get("inactive_recipient_id"):
            continue
        try:
            r = c.delete(f"/api/v1/sec/users/{uid}")
            print(f"  disable SEC user {uid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  disable SEC user {uid} FAILED: {e}")
    if sec_users:
        LEFT_BEHIND.append(
            f"SecUser: {sec_users} (usernames 'notif-inact-{RUN_ID}' / 'notif-noperm-{RUN_ID}') — "
            f"disabled (soft); SEC documents no hard delete.")

    for tid in [i for i in created["NotificationTemplate"] if i]:
        try:
            r = c.delete(f"/api/v1/notifications/templates/{tid}")
            print(f"  deactivate template {tid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate template {tid} FAILED: {e}")
    if [i for i in created["NotificationTemplate"] if i]:
        LEFT_BEHIND.append(
            f"NotificationTemplate: {[i for i in created['NotificationTemplate'] if i]} — "
            f"deactivated (soft, isActiveFl=false); NOTIF documents no hard delete. Codes are "
            f"RUN_ID-suffixed ('%_{RUN_ID}'). "
            f"Cleanup SQL: DELETE FROM NOTIF_TEMPLATE WHERE TEMPLATE_CODE LIKE '%\\_{RUN_ID}';")


# ══════════════════════════════════════════════════════════════════
# Report
# ══════════════════════════════════════════════════════════════════


def write_report(path: str):
    """Per-run results only (written when NOTIF_RUN_REPORT is set).

    erp-core 1.2.0: the static classification prose that used to be embedded here described the
    pre-1.2.0 code (SEC-PENDING permissions, XM-NOTIF-001 stub, synchronous FAILED branch) and is
    superseded; the maintained analysis is notif_problems_report.md, which this script never
    overwrites."""
    total_p = sum(s.passed_count for s in SUITES)
    total_f = sum(s.failed_count for s in SUITES)
    lines = [
        "# NOTIF — legacy API suite, single-run results",
        "",
        f"Generated: {date.today().isoformat()} · RUN_ID `{RUN_ID}` · target `{BASE_URL}` "
        f"(tenant `{TENANT_CODE}`)",
        "",
        f"**{total_p} passed · {total_f} failed** across {len(SUITES)} suites · "
        f"{len(OBSERVATIONS)} observation(s), which never affect the totals.",
        "",
        "Classification of failures: see notif_problems_report.md.",
        "",
        "## Suites",
        "",
        "| Suite | Passed | Failed |",
        "|---|---|---|",
    ]
    for s in SUITES:
        lines.append(f"| {s.entity} | {s.passed_count} | {s.failed_count} |")

    lines += ["", "## Failures", ""]
    fails = [(s, r) for s in SUITES for r in s.results if not r.passed]
    if not fails:
        lines.append("_None._")
    else:
        lines.append("| Suite | Test | Detail | Response |")
        lines.append("|---|---|---|---|")
        for s, r in fails:
            det = r.detail.replace("|", "\\|")[:300]
            snip = (r.response_snippet or "").replace("|", "\\|")[:200]
            lines.append(f"| {s.entity} | {r.name} | {det} | `{snip}` |")

    lines += ["", "## Preconditions (stage A0)", ""]
    lines += ([f"- {p}" for p in PRECONDITION_FAILURES] or ["_All preconditions satisfied._"])
    lines += ["", "## Observations (stage E — not pass/fail)", ""]
    lines += ([f"- **{o.name}** — {o.detail}" for o in OBSERVATIONS] or ["_None._"])
    lines += ["", "## Surviving records", ""]
    lines += ([f"- {n}" for n in LEFT_BEHIND] or ["_None._"])
    lines += ["", "### Permanent residue", ""]
    lines += ([f"- {n}" for n in PERMANENT_RESIDUE] or ["_None._"])
    lines.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nReport written: {path}")


# ══════════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════════


def main() -> int:
    global BASE_URL
    if len(sys.argv) > 1:
        BASE_URL = sys.argv[1].rstrip("/")
    if not ADMIN_PASSWORD:
        print("FATAL: set ERP_BOOTSTRAP_ADMIN_PASSWORD (the bootstrap admin's password) — "
              "ENVIRONMENT_FAILURE", file=sys.stderr)
        return 2

    c = APIClient(BASE_URL)
    print(f"api-verify — NOTIF · legacy suite adapted to erp-core 1.2.0 · RUN_ID={RUN_ID} · "
          f"target {BASE_URL} · tenant {TENANT_CODE}")

    tok = c.login(ADMIN_USERNAME, ADMIN_PASSWORD)
    if not tok:
        print("FATAL: could not authenticate — ENVIRONMENT_FAILURE", file=sys.stderr)
        return 2
    c.token = tok
    # erp-core 1.2.0: the JWT carries the caller's SEC_USER id as `uid` (with `tid`, `realm`) —
    # DEVIATIONS [05], [06]; used to pick the caller as the IN_APP recipient (see preflight).
    ctx["caller_user_id"] = jwt_claim(tok, "uid")

    try:
        grants(c)
        preflight(c)
        test_template(c)      # DEPENDENCY ORDER 1
        test_channel(c)       # DEPENDENCY ORDER 2
        test_dispatch(c)      # DEPENDENCY ORDER 3 (creates NOTIF_LOG via fan-out)
        test_logs(c)
        test_lookups(c)
        test_authorization(c)
    finally:
        try:
            cleanup(c)
        except Exception as e:  # noqa: BLE001
            print(f"cleanup FAILED: {e}")
        # erp-core 1.2.0: the per-run report is opt-in (NOTIF_RUN_REPORT) so a run never
        # overwrites the maintained notif_problems_report.md.
        if os.environ.get("NOTIF_RUN_REPORT"):
            write_report(os.environ["NOTIF_RUN_REPORT"])

    total_f = sum(s.failed_count for s in SUITES)
    print(f"\nTOTAL: {sum(s.passed_count for s in SUITES)} passed, {total_f} failed")
    return 1 if total_f else 0


if __name__ == "__main__":
    raise SystemExit(main())
