-- ============================================================
-- V10 — Tenant (row-level multi-tenancy, shared schema) — erp-core step 05
-- Target: POSTGRESQL_16 | after V2..V9
--
-- What this script does:
--   1. CORE_TENANT (global, no TENANT_ID) + its sequence; seeds the PLATFORM tenant (ID 1).
--   2. Every tenant-scoped core table gets TENANT_ID BIGINT NOT NULL (backfilled with 1 = PLATFORM,
--      FK to CORE_TENANT, indexed) and VERSION BIGINT NOT NULL DEFAULT 0 (optimistic locking).
--   3. The three global permission-catalog tables (SEC_MODULE_REG / SEC_SCREEN_REG /
--      SEC_ACTION_REG) get VERSION only — the catalog is code-defined and the same for all tenants.
--   4. The eight SEC tables that had no audit columns get nullable CREATED_BY / CREATED_AT /
--      UPDATED_BY / UPDATED_AT (backfilled from their own lifecycle columns), so every tenant-scoped
--      entity extends AuditableEntity (step 04 report, "Schema conventions check").
--   5. Every UNIQUE constraint on a tenant-scoped table becomes composite with TENANT_ID (the
--      constraint names are kept, so the JPA @UniqueConstraint names stay verbatim).
--   6. Seeds the PLATFORM module / PLATFORM_TENANTS screen / its VIEW + PLATFORM_TENANT_MANAGE actions
--      and grants them to the PLATFORM tenant's SYS_ADMIN role (the bootstrap admin's role).
--
-- Additive-only rule (README.md): everything here is additive EXCEPT two changes the step-05 plan
-- itself sanctions inside this script (recorded in docs/DEVIATIONS.md as plan-sanctioned):
--   (a) ALTER COLUMN TENANT_ID DROP DEFAULT after the backfill, so the application must always
--       supply the tenant (Hibernate @TenantId does);
--   (b) DROP + re-ADD of each unique constraint as its composite (TENANT_ID, ...) form.
-- ============================================================

-- ============================================================
-- 1. CORE_TENANT
-- ============================================================
CREATE SEQUENCE SEQ_CORE_TENANT START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;

CREATE TABLE CORE_TENANT (
  ID           BIGINT        NOT NULL,
  CODE         VARCHAR(32)   NOT NULL,
  NAME_AR      VARCHAR(200)  NOT NULL,
  NAME_EN      VARCHAR(200)  NOT NULL,
  STATUS_CODE  VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
  CREATED_BY   VARCHAR(100)  NOT NULL,
  CREATED_AT   TIMESTAMPTZ   NOT NULL DEFAULT now(),
  UPDATED_BY   VARCHAR(100),
  UPDATED_AT   TIMESTAMPTZ,
  VERSION      BIGINT        NOT NULL DEFAULT 0
);

COMMENT ON TABLE CORE_TENANT IS 'Tenant registry (global — the one core table without TENANT_ID). ID 1 = PLATFORM.';
COMMENT ON COLUMN CORE_TENANT.CODE IS 'Tenant code, ^[A-Z0-9_]{3,32}$, unique; sent by clients as X-Tenant-Code.';
COMMENT ON COLUMN CORE_TENANT.STATUS_CODE IS 'ACTIVE | SUSPENDED — a suspended tenant cannot log in or call any endpoint.';

ALTER TABLE CORE_TENANT ADD CONSTRAINT PK_CORE_TENANT PRIMARY KEY (ID);
ALTER TABLE CORE_TENANT ADD CONSTRAINT UQ_CORE_TENANT_CODE UNIQUE (CODE);
ALTER TABLE CORE_TENANT ADD CONSTRAINT CHK_CORE_TENANT_STATUS CHECK (STATUS_CODE IN ('ACTIVE','SUSPENDED'));
ALTER TABLE CORE_TENANT ADD CONSTRAINT CHK_CORE_TENANT_CODE CHECK (CODE ~ '^[A-Z0-9_]{3,32}$');

-- The PLATFORM tenant: owns every row that existed before this script (the backfill below), the
-- bootstrap admin, and the platform-level operations (/api/v1/platform/**).
INSERT INTO CORE_TENANT (ID, CODE, NAME_AR, NAME_EN, STATUS_CODE, CREATED_BY, CREATED_AT)
VALUES (1, 'PLATFORM', 'المنصة', 'Platform', 'ACTIVE', 'SYSTEM', CURRENT_TIMESTAMP);
SELECT setval('SEQ_CORE_TENANT', 1, true);

-- ============================================================
-- 2. TENANT_ID + VERSION on every tenant-scoped table (18 tables)
--    ADD ... DEFAULT 1 backfills every existing row into PLATFORM in one statement.
-- ============================================================
ALTER TABLE CU_APP_CONFIGURATION  ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE MDL_LOOKUP_TYPE       ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE MDL_LOOKUP_VALUE      ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_USER              ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_ROLE              ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_USER_ROLE         ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_ROLE_MODULE_GRANT ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_ROLE_SCREEN_GRANT ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_ROLE_ACTION_GRANT ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_ACTIVE_SESSION    ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_AUDIT_LOG         ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_PWD_RESET_TOKEN   ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_SIGNUP_REQUEST    ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE FILE_CATEGORY         ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE FILE_DOCUMENT         ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE NOTIF_TEMPLATE        ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE NOTIF_CHANNEL_CONFIG  ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE NOTIF_LOG             ADD COLUMN TENANT_ID BIGINT NOT NULL DEFAULT 1, ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;

-- Plan-sanctioned exception (a): no default — the application must always supply the tenant.
ALTER TABLE CU_APP_CONFIGURATION  ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE MDL_LOOKUP_TYPE       ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE MDL_LOOKUP_VALUE      ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_USER              ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_ROLE              ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_USER_ROLE         ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_ROLE_MODULE_GRANT ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_ROLE_SCREEN_GRANT ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_ROLE_ACTION_GRANT ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_ACTIVE_SESSION    ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_AUDIT_LOG         ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_PWD_RESET_TOKEN   ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE SEC_SIGNUP_REQUEST    ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE FILE_CATEGORY         ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE FILE_DOCUMENT         ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE NOTIF_TEMPLATE        ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE NOTIF_CHANNEL_CONFIG  ALTER COLUMN TENANT_ID DROP DEFAULT;
ALTER TABLE NOTIF_LOG             ALTER COLUMN TENANT_ID DROP DEFAULT;

ALTER TABLE CU_APP_CONFIGURATION  ADD CONSTRAINT FK_CU_APP_CONFIGURATION_TENANT  FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE MDL_LOOKUP_TYPE       ADD CONSTRAINT FK_MDL_LOOKUP_TYPE_TENANT       FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE MDL_LOOKUP_VALUE      ADD CONSTRAINT FK_MDL_LOOKUP_VALUE_TENANT      FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_USER              ADD CONSTRAINT FK_SEC_USER_TENANT              FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_ROLE              ADD CONSTRAINT FK_SEC_ROLE_TENANT              FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_USER_ROLE         ADD CONSTRAINT FK_SEC_USER_ROLE_TENANT         FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_ROLE_MODULE_GRANT ADD CONSTRAINT FK_SEC_ROLE_MODULE_GRANT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_ROLE_SCREEN_GRANT ADD CONSTRAINT FK_SEC_ROLE_SCREEN_GRANT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_ROLE_ACTION_GRANT ADD CONSTRAINT FK_SEC_ROLE_ACTION_GRANT_TENANT FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_ACTIVE_SESSION    ADD CONSTRAINT FK_SEC_ACTIVE_SESSION_TENANT    FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_AUDIT_LOG         ADD CONSTRAINT FK_SEC_AUDIT_LOG_TENANT         FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_PWD_RESET_TOKEN   ADD CONSTRAINT FK_SEC_PWD_RESET_TOKEN_TENANT   FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE SEC_SIGNUP_REQUEST    ADD CONSTRAINT FK_SEC_SIGNUP_REQUEST_TENANT    FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE FILE_CATEGORY         ADD CONSTRAINT FK_FILE_CATEGORY_TENANT         FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE FILE_DOCUMENT         ADD CONSTRAINT FK_FILE_DOCUMENT_TENANT         FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE NOTIF_TEMPLATE        ADD CONSTRAINT FK_NOTIF_TEMPLATE_TENANT        FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE NOTIF_CHANNEL_CONFIG  ADD CONSTRAINT FK_NOTIF_CHANNEL_CONFIG_TENANT  FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);
ALTER TABLE NOTIF_LOG             ADD CONSTRAINT FK_NOTIF_LOG_TENANT             FOREIGN KEY (TENANT_ID) REFERENCES CORE_TENANT (ID);

CREATE INDEX IDX_CU_APP_CONFIGURATION_TENANT  ON CU_APP_CONFIGURATION (TENANT_ID);
CREATE INDEX IDX_MDL_LOOKUP_TYPE_TENANT       ON MDL_LOOKUP_TYPE (TENANT_ID);
CREATE INDEX IDX_MDL_LOOKUP_VALUE_TENANT      ON MDL_LOOKUP_VALUE (TENANT_ID);
CREATE INDEX IDX_SEC_USER_TENANT              ON SEC_USER (TENANT_ID);
CREATE INDEX IDX_SEC_ROLE_TENANT              ON SEC_ROLE (TENANT_ID);
CREATE INDEX IDX_SEC_USER_ROLE_TENANT         ON SEC_USER_ROLE (TENANT_ID);
CREATE INDEX IDX_SEC_ROLE_MODULE_GRANT_TENANT ON SEC_ROLE_MODULE_GRANT (TENANT_ID);
CREATE INDEX IDX_SEC_ROLE_SCREEN_GRANT_TENANT ON SEC_ROLE_SCREEN_GRANT (TENANT_ID);
CREATE INDEX IDX_SEC_ROLE_ACTION_GRANT_TENANT ON SEC_ROLE_ACTION_GRANT (TENANT_ID);
CREATE INDEX IDX_SEC_ACTIVE_SESSION_TENANT    ON SEC_ACTIVE_SESSION (TENANT_ID);
CREATE INDEX IDX_SEC_AUDIT_LOG_TENANT         ON SEC_AUDIT_LOG (TENANT_ID);
CREATE INDEX IDX_SEC_PWD_RESET_TOKEN_TENANT   ON SEC_PWD_RESET_TOKEN (TENANT_ID);
CREATE INDEX IDX_SEC_SIGNUP_REQUEST_TENANT    ON SEC_SIGNUP_REQUEST (TENANT_ID);
CREATE INDEX IDX_FILE_CATEGORY_TENANT         ON FILE_CATEGORY (TENANT_ID);
CREATE INDEX IDX_FILE_DOCUMENT_TENANT         ON FILE_DOCUMENT (TENANT_ID);
CREATE INDEX IDX_NOTIF_TEMPLATE_TENANT        ON NOTIF_TEMPLATE (TENANT_ID);
CREATE INDEX IDX_NOTIF_CHANNEL_CONFIG_TENANT  ON NOTIF_CHANNEL_CONFIG (TENANT_ID);
CREATE INDEX IDX_NOTIF_LOG_TENANT             ON NOTIF_LOG (TENANT_ID);

COMMENT ON COLUMN SEC_USER.TENANT_ID IS 'Owning tenant (CORE_TENANT.ID); set by Hibernate @TenantId, never by a client.';

-- ============================================================
-- 3. VERSION on the global permission catalog (no TENANT_ID: same for all tenants)
-- ============================================================
ALTER TABLE SEC_MODULE_REG ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_SCREEN_REG ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;
ALTER TABLE SEC_ACTION_REG ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0;

-- ============================================================
-- 4. Audit columns on the eight SEC tables that lacked them (nullable: additive), backfilled from
--    each table's own lifecycle columns. Same types as the other SEC audit columns.
-- ============================================================
ALTER TABLE SEC_USER_ROLE         ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_ROLE_MODULE_GRANT ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_ROLE_SCREEN_GRANT ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_ROLE_ACTION_GRANT ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_ACTIVE_SESSION    ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_AUDIT_LOG         ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_PWD_RESET_TOKEN   ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;
ALTER TABLE SEC_SIGNUP_REQUEST    ADD COLUMN CREATED_BY VARCHAR(100), ADD COLUMN CREATED_AT TIMESTAMPTZ, ADD COLUMN UPDATED_BY VARCHAR(100), ADD COLUMN UPDATED_AT TIMESTAMPTZ;

UPDATE SEC_USER_ROLE         SET CREATED_BY = ASSIGNED_BY, CREATED_AT = ASSIGNED_AT;
UPDATE SEC_ROLE_MODULE_GRANT SET CREATED_BY = GRANTED_BY,  CREATED_AT = GRANTED_AT;
UPDATE SEC_ROLE_SCREEN_GRANT SET CREATED_BY = GRANTED_BY,  CREATED_AT = GRANTED_AT;
UPDATE SEC_ROLE_ACTION_GRANT SET CREATED_BY = GRANTED_BY,  CREATED_AT = GRANTED_AT;
UPDATE SEC_ACTIVE_SESSION    SET CREATED_BY = 'SYSTEM',    CREATED_AT = STARTED_AT;
UPDATE SEC_AUDIT_LOG         SET CREATED_BY = 'SYSTEM',    CREATED_AT = OCCURRED_AT;
UPDATE SEC_PWD_RESET_TOKEN   SET CREATED_BY = 'SYSTEM',    CREATED_AT = REQUESTED_AT;
UPDATE SEC_SIGNUP_REQUEST    SET CREATED_BY = 'SYSTEM',    CREATED_AT = SUBMITTED_AT;

-- ============================================================
-- 5. Composite uniqueness (plan-sanctioned exception (b)): same names, TENANT_ID first.
-- ============================================================
ALTER TABLE CU_APP_CONFIGURATION DROP CONSTRAINT UQ_CU_APP_CONFIG_CONFIG_KEY;
ALTER TABLE CU_APP_CONFIGURATION ADD  CONSTRAINT UQ_CU_APP_CONFIG_CONFIG_KEY UNIQUE (TENANT_ID, CONFIG_KEY);

ALTER TABLE MDL_LOOKUP_TYPE  DROP CONSTRAINT UQ_MDL_LOOKUP_TYPE_KEY;
ALTER TABLE MDL_LOOKUP_TYPE  ADD  CONSTRAINT UQ_MDL_LOOKUP_TYPE_KEY UNIQUE (TENANT_ID, key);
ALTER TABLE MDL_LOOKUP_VALUE DROP CONSTRAINT UQ_MDL_LOOKUP_VALUE_TYPE_CODE;
ALTER TABLE MDL_LOOKUP_VALUE ADD  CONSTRAINT UQ_MDL_LOOKUP_VALUE_TYPE_CODE UNIQUE (TENANT_ID, lookup_type_id, code);

ALTER TABLE SEC_USER DROP CONSTRAINT UQ_SEC_USER_USERNAME;
ALTER TABLE SEC_USER ADD  CONSTRAINT UQ_SEC_USER_USERNAME UNIQUE (TENANT_ID, username);
ALTER TABLE SEC_USER DROP CONSTRAINT UQ_SEC_USER_EMAIL;
ALTER TABLE SEC_USER ADD  CONSTRAINT UQ_SEC_USER_EMAIL UNIQUE (TENANT_ID, email);
ALTER TABLE SEC_ROLE DROP CONSTRAINT UQ_SEC_ROLE_CODE;
ALTER TABLE SEC_ROLE ADD  CONSTRAINT UQ_SEC_ROLE_CODE UNIQUE (TENANT_ID, code);
ALTER TABLE SEC_USER_ROLE DROP CONSTRAINT UQ_SEC_USER_ROLE_USER_ROLE;
ALTER TABLE SEC_USER_ROLE ADD  CONSTRAINT UQ_SEC_USER_ROLE_USER_ROLE UNIQUE (TENANT_ID, user_id, role_id);
ALTER TABLE SEC_ROLE_MODULE_GRANT DROP CONSTRAINT UQ_SEC_ROLE_MODULE_GRANT_ROLE_MODULE;
ALTER TABLE SEC_ROLE_MODULE_GRANT ADD  CONSTRAINT UQ_SEC_ROLE_MODULE_GRANT_ROLE_MODULE UNIQUE (TENANT_ID, role_id, module_id);
ALTER TABLE SEC_ROLE_SCREEN_GRANT DROP CONSTRAINT UQ_SEC_ROLE_SCREEN_GRANT_ROLE_SCREEN;
ALTER TABLE SEC_ROLE_SCREEN_GRANT ADD  CONSTRAINT UQ_SEC_ROLE_SCREEN_GRANT_ROLE_SCREEN UNIQUE (TENANT_ID, role_id, screen_id);
ALTER TABLE SEC_ROLE_ACTION_GRANT DROP CONSTRAINT UQ_SEC_ROLE_ACTION_GRANT_ROLE_ACTION;
ALTER TABLE SEC_ROLE_ACTION_GRANT ADD  CONSTRAINT UQ_SEC_ROLE_ACTION_GRANT_ROLE_ACTION UNIQUE (TENANT_ID, role_id, action_id);

ALTER TABLE FILE_CATEGORY DROP CONSTRAINT UQ_FILE_CATEGORY_CATEGORY_CODE;
ALTER TABLE FILE_CATEGORY ADD  CONSTRAINT UQ_FILE_CATEGORY_CATEGORY_CODE UNIQUE (TENANT_ID, CATEGORY_CODE);

ALTER TABLE NOTIF_TEMPLATE       DROP CONSTRAINT UQ_NOTIF_TEMPLATE_CODE;
ALTER TABLE NOTIF_TEMPLATE       ADD  CONSTRAINT UQ_NOTIF_TEMPLATE_CODE UNIQUE (TENANT_ID, TEMPLATE_CODE);
ALTER TABLE NOTIF_CHANNEL_CONFIG DROP CONSTRAINT UQ_NOTIF_CHANNEL_CONFIG_TYPE;
ALTER TABLE NOTIF_CHANNEL_CONFIG ADD  CONSTRAINT UQ_NOTIF_CHANNEL_CONFIG_TYPE UNIQUE (TENANT_ID, CHANNEL_TYPE_ID);

-- ============================================================
-- 6. PLATFORM_TENANT_MANAGE — registry rows (global) + grants to the PLATFORM tenant's SYS_ADMIN.
--    The code is the step-05 plan's literal (like CU's CONFIG_* codes, not PERM_<PAGE>_<ACTION>).
--    RULE-SEC-007 (MenuService.effectiveAuthorityCodes): a screen's non-VIEW actions are effective
--    only together with that screen's VIEW (gateway) action, so the screen also carries
--    PERM_PLATFORM_TENANTS_VIEW, granted alongside. Module/screen/action follow V7's natural-key
--    style; TENANT_ID is supplied explicitly (no default any more).
-- ============================================================
INSERT INTO SEC_MODULE_REG (MODULE_REG_PK, CODE, NAME_AR, NAME_EN, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_MODULE_REG'), 'PLATFORM', 'إدارة المنصة', 'Platform Administration', TRUE, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO SEC_SCREEN_REG (SCREEN_REG_PK, PAGE_CODE, MODULE_ID, NAME_AR, NAME_EN, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
SELECT nextval('SEQ_SEC_SCREEN_REG'), 'PLATFORM_TENANTS', m.MODULE_REG_PK, 'المستأجرون', 'Tenants', TRUE, 'SYSTEM', CURRENT_TIMESTAMP
FROM SEC_MODULE_REG m WHERE m.CODE = 'PLATFORM';

INSERT INTO SEC_ACTION_REG (ACTION_REG_PK, PERMISSION_CODE, SCREEN_ID, ACTION_CODE, NAME_AR, NAME_EN, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
SELECT nextval('SEQ_SEC_ACTION_REG'), v.permission_code, s.SCREEN_REG_PK, v.action_code,
       s.NAME_AR || ' - ' || v.action_ar, s.NAME_EN || ' - ' || v.action_code, TRUE, 'SYSTEM', CURRENT_TIMESTAMP
FROM (VALUES
    (1, 'VIEW',   'عرض',  'PERM_PLATFORM_TENANTS_VIEW'),
    (2, 'MANAGE', 'إدارة', 'PLATFORM_TENANT_MANAGE')
) AS v(ord, action_code, action_ar, permission_code)
JOIN SEC_SCREEN_REG s ON s.PAGE_CODE = 'PLATFORM_TENANTS'
ORDER BY v.ord;

INSERT INTO SEC_ROLE_MODULE_GRANT (ROLE_MODULE_GRANT_PK, TENANT_ID, ROLE_ID, MODULE_ID, GRANTED_BY, GRANTED_AT, CREATED_BY, CREATED_AT)
SELECT nextval('SEQ_SEC_ROLE_MODULE_GRANT'), 1, r.ROLE_PK, m.MODULE_REG_PK, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP
FROM SEC_ROLE r JOIN SEC_MODULE_REG m ON m.CODE = 'PLATFORM'
WHERE r.TENANT_ID = 1 AND r.CODE = 'SYS_ADMIN';

INSERT INTO SEC_ROLE_SCREEN_GRANT (ROLE_SCREEN_GRANT_PK, TENANT_ID, ROLE_ID, SCREEN_ID, GRANTED_BY, GRANTED_AT, CREATED_BY, CREATED_AT)
SELECT nextval('SEQ_SEC_ROLE_SCREEN_GRANT'), 1, r.ROLE_PK, s.SCREEN_REG_PK, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP
FROM SEC_ROLE r JOIN SEC_SCREEN_REG s ON s.PAGE_CODE = 'PLATFORM_TENANTS'
WHERE r.TENANT_ID = 1 AND r.CODE = 'SYS_ADMIN';

INSERT INTO SEC_ROLE_ACTION_GRANT (ROLE_ACTION_GRANT_PK, TENANT_ID, ROLE_ID, ACTION_ID, GRANTED_BY, GRANTED_AT, CREATED_BY, CREATED_AT)
SELECT nextval('SEQ_SEC_ROLE_ACTION_GRANT'), 1, r.ROLE_PK, a.ACTION_REG_PK, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP
FROM SEC_ROLE r JOIN SEC_ACTION_REG a ON a.PERMISSION_CODE IN ('PERM_PLATFORM_TENANTS_VIEW', 'PLATFORM_TENANT_MANAGE')
WHERE r.TENANT_ID = 1 AND r.CODE = 'SYS_ADMIN'
ORDER BY a.ACTION_REG_PK;
