-- ============================================================
-- V2 — Security (SEC) — full module schema
-- Source: governance/modules/SEC/P2/db-script.md SECTION 4 (FULL_DATABASE_SCRIPT), DBS-SEC-001 v1.1
-- Target: POSTGRESQL_16 | 11 tables (8 base + 3 join), 8 sequences | two-tier RBAC (Tier-1 Module/RoleModule)
-- v1.3 additions marked "-- [v1.3]" (Module + RoleModule + Page.MODULE_FK). No seed data (SEC-BE phase owns seed).
-- ============================================================

-- ============================================================
-- BLOCK 1: SEQUENCES
-- ============================================================
CREATE SEQUENCE SEQ_SEC_USER_ACCOUNT             START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_ROLE                     START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_PERMISSION               START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_PAGE                     START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_REFRESH_TOKEN            START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_PASSWORD_RESET_TOKEN     START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_ACCOUNT_ACTIVATION_TOKEN START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE SEQ_SEC_MODULE                   START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE;  -- [v1.3]

-- ============================================================
-- BLOCK 2: PARENT TABLES (no intra-module FK dependencies)
-- ============================================================
CREATE TABLE SEC_USER_ACCOUNT (
  ID                 BIGINT        NOT NULL,
  USERNAME           VARCHAR(100)  NOT NULL,
  PASSWORD_HASH      VARCHAR(255)  NOT NULL,
  EMAIL              VARCHAR(255)  NOT NULL,
  PHONE              VARCHAR(30),
  FULL_NAME          VARCHAR(200)  NOT NULL,
  PREFERRED_LANG_ID  VARCHAR(10)   NOT NULL,
  USER_STATUS_ID     VARCHAR(50)   NOT NULL,
  FAILED_LOGIN_COUNT SMALLINT      DEFAULT 0 NOT NULL,
  LOCKED_UNTIL       TIMESTAMP,
  IS_ACTIVE_FL       SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_BY         VARCHAR(255),
  CREATED_AT         TIMESTAMP,
  UPDATED_BY         VARCHAR(255),
  UPDATED_AT         TIMESTAMP
);

CREATE TABLE SEC_ROLE (
  ID           BIGINT        NOT NULL,
  ROLE_CODE    VARCHAR(50)   NOT NULL,
  NAME_AR      VARCHAR(200)  NOT NULL,
  NAME_EN      VARCHAR(100)  NOT NULL,
  IS_ACTIVE_FL SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_BY   VARCHAR(255),
  CREATED_AT   TIMESTAMP,
  UPDATED_BY   VARCHAR(255),
  UPDATED_AT   TIMESTAMP
);

-- [v1.3] Module registry (Tier-1 grantable unit + dashboard display unit)
CREATE TABLE SEC_MODULE (
  ID           BIGINT        NOT NULL,
  MODULE_CODE  VARCHAR(50)   NOT NULL,
  NAME_AR      VARCHAR(200)  NOT NULL,
  NAME_EN      VARCHAR(100)  NOT NULL,
  IS_ACTIVE_FL SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_BY   VARCHAR(255),
  CREATED_AT   TIMESTAMP,
  UPDATED_BY   VARCHAR(255),
  UPDATED_AT   TIMESTAMP
);

CREATE TABLE SEC_PAGE (
  ID             BIGINT        NOT NULL,
  PAGE_CODE      VARCHAR(100)  NOT NULL,
  NAME_AR        VARCHAR(200)  NOT NULL,
  NAME_EN        VARCHAR(100)  NOT NULL,
  MODULE_FK      BIGINT        NOT NULL,   -- [v1.3] owning module -> SEC_MODULE (enables RULE-SEC-014 derivation)
  PARENT_PAGE_FK BIGINT,
  IS_ACTIVE_FL   SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_BY     VARCHAR(255),
  CREATED_AT     TIMESTAMP,
  UPDATED_BY     VARCHAR(255),
  UPDATED_AT     TIMESTAMP
);

-- ============================================================
-- BLOCK 3: CHILD TABLES (intra-module FK dependencies)
-- ============================================================
CREATE TABLE SEC_PERMISSION (
  ID              BIGINT        NOT NULL,
  PERMISSION_CODE VARCHAR(150)  NOT NULL,
  PERMISSION_TYPE VARCHAR(20)   NOT NULL,
  NAME_AR         VARCHAR(200)  NOT NULL,
  NAME_EN         VARCHAR(100)  NOT NULL,
  IS_ACTIVE_FL    SMALLINT      DEFAULT 1 NOT NULL,
  PAGE_FK         BIGINT        NOT NULL,
  CREATED_BY      VARCHAR(255),
  CREATED_AT      TIMESTAMP,
  UPDATED_BY      VARCHAR(255),
  UPDATED_AT      TIMESTAMP
);

CREATE TABLE SEC_REFRESH_TOKEN (
  ID              BIGINT        NOT NULL,
  TOKEN           VARCHAR(255)  NOT NULL,
  EXPIRES_AT      TIMESTAMP     NOT NULL,
  REVOKED_FL      SMALLINT      DEFAULT 0 NOT NULL,
  USER_ACCOUNT_FK BIGINT        NOT NULL,
  CREATED_BY      VARCHAR(255),
  CREATED_AT      TIMESTAMP,
  UPDATED_BY      VARCHAR(255),
  UPDATED_AT      TIMESTAMP
);

CREATE TABLE SEC_PASSWORD_RESET_TOKEN (
  ID              BIGINT        NOT NULL,
  TOKEN           VARCHAR(255)  NOT NULL,
  EXPIRES_AT      TIMESTAMP     NOT NULL,
  USED_FL         SMALLINT      DEFAULT 0 NOT NULL,
  USER_ACCOUNT_FK BIGINT        NOT NULL,
  CREATED_BY      VARCHAR(255),
  CREATED_AT      TIMESTAMP,
  UPDATED_BY      VARCHAR(255),
  UPDATED_AT      TIMESTAMP
);

CREATE TABLE SEC_ACCOUNT_ACTIVATION_TOKEN (
  ID              BIGINT        NOT NULL,
  TOKEN           VARCHAR(255)  NOT NULL,
  EXPIRES_AT      TIMESTAMP     NOT NULL,
  USED_FL         SMALLINT      DEFAULT 0 NOT NULL,
  USER_ACCOUNT_FK BIGINT        NOT NULL,
  CREATED_BY      VARCHAR(255),
  CREATED_AT      TIMESTAMP,
  UPDATED_BY      VARCHAR(255),
  UPDATED_AT      TIMESTAMP
);

CREATE TABLE SEC_USER_ROLE (
  USER_ACCOUNT_FK BIGINT NOT NULL,
  ROLE_FK         BIGINT NOT NULL
);

CREATE TABLE SEC_ROLE_PERMISSION (
  ROLE_FK       BIGINT NOT NULL,
  PERMISSION_FK BIGINT NOT NULL
);

-- [v1.3] Tier-1 grant: role x module
CREATE TABLE SEC_ROLE_MODULE (
  ROLE_FK   BIGINT NOT NULL,
  MODULE_FK BIGINT NOT NULL
);

-- ============================================================
-- BLOCK 4: COMMENTS
-- ============================================================
COMMENT ON TABLE SEC_USER_ACCOUNT IS 'SHARED identity entity (ENTITY-SEC-001). Consumed SOFT-READ by FILE/NOTIF. Deactivation: no cascade, history retained (RULE-SEC-012).';
COMMENT ON COLUMN SEC_USER_ACCOUNT.PREFERRED_LANG_ID IS 'Language code (LOV-SEC-001); runtime-loaded, no lookup table.';
COMMENT ON COLUMN SEC_USER_ACCOUNT.USER_STATUS_ID IS 'Account lifecycle code (LOV-SEC-002): PENDING_ACTIVATION/ACTIVE/INACTIVE; runtime-loaded.';
COMMENT ON COLUMN SEC_USER_ACCOUNT.FAILED_LOGIN_COUNT IS 'Failed-login counter for temporary lock (RULE-SEC-005).';
COMMENT ON COLUMN SEC_USER_ACCOUNT.LOCKED_UNTIL IS 'Temporary lock expiry (not a lifecycle status).';
COMMENT ON COLUMN SEC_USER_ACCOUNT.IS_ACTIVE_FL IS 'Active flag: 1=active, 0=inactive.';
COMMENT ON TABLE SEC_ROLE IS 'RBAC role (ENTITY-SEC-002). Tier-1 modules granted via SEC_ROLE_MODULE; Tier-2 screen permissions via SEC_ROLE_PERMISSION.';
COMMENT ON TABLE SEC_MODULE IS '[v1.3] Module registry (ENTITY-SEC-010). Tier-1 grantable unit + dashboard display unit; owns pages via SEC_PAGE.MODULE_FK.';
COMMENT ON COLUMN SEC_MODULE.MODULE_CODE IS 'Unique module code (e.g. SEC/FILE/NOTIF).';
COMMENT ON COLUMN SEC_MODULE.IS_ACTIVE_FL IS 'Active flag: 1=active, 0=inactive.';
COMMENT ON TABLE SEC_PERMISSION IS 'Permission auto-generated per Page (ENTITY-SEC-003 / CORE-9). Tier-2 enforcement.';
COMMENT ON COLUMN SEC_PERMISSION.PERMISSION_TYPE IS 'CORE-9 code convention: VIEW/CREATE/UPDATE/DELETE (not a runtime LOV).';
COMMENT ON COLUMN SEC_PERMISSION.PAGE_FK IS 'FK to SEC_PAGE.';
COMMENT ON TABLE SEC_PAGE IS 'Screen/Page registry — CORE-9 owner (ENTITY-SEC-004). Each page belongs to a module (MODULE_FK).';
COMMENT ON COLUMN SEC_PAGE.MODULE_FK IS '[v1.3] Owning module (FK -> SEC_MODULE, NOT NULL). Basis of RULE-SEC-014 derivation (no orphan screen permission).';
COMMENT ON COLUMN SEC_PAGE.PARENT_PAGE_FK IS 'Self-FK to SEC_PAGE for navigation hierarchy within the module.';
COMMENT ON TABLE SEC_REFRESH_TOKEN IS 'JWT refresh token; rotated on refresh (ENTITY-SEC-005 / RULE-SEC-006).';
COMMENT ON TABLE SEC_PASSWORD_RESET_TOKEN IS 'Single-use password reset token (ENTITY-SEC-006 / RULE-SEC-007).';
COMMENT ON TABLE SEC_ACCOUNT_ACTIVATION_TOKEN IS 'Single-use account activation token (ENTITY-SEC-007 / RULE-SEC-008).';
COMMENT ON TABLE SEC_USER_ROLE IS 'Join: user-role (ENTITY-SEC-008); composite PK, no surrogate id/audit.';
COMMENT ON TABLE SEC_ROLE_PERMISSION IS 'Join: role-permission, Tier-2 (ENTITY-SEC-009); composite PK. Subject to RULE-SEC-014 (enforced app-layer).';
COMMENT ON TABLE SEC_ROLE_MODULE IS '[v1.3] Join: role-module, Tier-1 grant (ENTITY-SEC-011); composite PK, no surrogate id/audit. Drives dashboard filter + screen-permission prerequisite (RULE-SEC-013).';

-- ============================================================
-- BLOCK 5: CONSTRAINTS
-- ============================================================
-- 5a. PRIMARY KEYS
ALTER TABLE SEC_USER_ACCOUNT             ADD CONSTRAINT PK_SEC_USER_ACCOUNT             PRIMARY KEY (ID);
ALTER TABLE SEC_ROLE                     ADD CONSTRAINT PK_SEC_ROLE                     PRIMARY KEY (ID);
ALTER TABLE SEC_MODULE                   ADD CONSTRAINT PK_SEC_MODULE                   PRIMARY KEY (ID);              -- [v1.3]
ALTER TABLE SEC_PERMISSION               ADD CONSTRAINT PK_SEC_PERMISSION               PRIMARY KEY (ID);
ALTER TABLE SEC_PAGE                     ADD CONSTRAINT PK_SEC_PAGE                     PRIMARY KEY (ID);
ALTER TABLE SEC_REFRESH_TOKEN            ADD CONSTRAINT PK_SEC_REFRESH_TOKEN            PRIMARY KEY (ID);
ALTER TABLE SEC_PASSWORD_RESET_TOKEN     ADD CONSTRAINT PK_SEC_PASSWORD_RESET_TOKEN     PRIMARY KEY (ID);
ALTER TABLE SEC_ACCOUNT_ACTIVATION_TOKEN ADD CONSTRAINT PK_SEC_ACCOUNT_ACTIVATION_TOKEN PRIMARY KEY (ID);
ALTER TABLE SEC_USER_ROLE                ADD CONSTRAINT PK_SEC_USER_ROLE                PRIMARY KEY (USER_ACCOUNT_FK, ROLE_FK);
ALTER TABLE SEC_ROLE_PERMISSION          ADD CONSTRAINT PK_SEC_ROLE_PERMISSION          PRIMARY KEY (ROLE_FK, PERMISSION_FK);
ALTER TABLE SEC_ROLE_MODULE              ADD CONSTRAINT PK_SEC_ROLE_MODULE              PRIMARY KEY (ROLE_FK, MODULE_FK);  -- [v1.3]

-- 5b. UNIQUE CONSTRAINTS  (RULE-SEC-001, RULE-SEC-010)
ALTER TABLE SEC_USER_ACCOUNT             ADD CONSTRAINT UQ_SEC_USER_ACCOUNT_USERNAME    UNIQUE (USERNAME);
ALTER TABLE SEC_USER_ACCOUNT             ADD CONSTRAINT UQ_SEC_USER_ACCOUNT_EMAIL       UNIQUE (EMAIL);
ALTER TABLE SEC_ROLE                     ADD CONSTRAINT UQ_SEC_ROLE_ROLE_CODE           UNIQUE (ROLE_CODE);
ALTER TABLE SEC_MODULE                   ADD CONSTRAINT UQ_SEC_MODULE_MODULE_CODE       UNIQUE (MODULE_CODE);          -- [v1.3] RULE-SEC-010 pattern
ALTER TABLE SEC_PERMISSION               ADD CONSTRAINT UQ_SEC_PERMISSION_PERM_CODE     UNIQUE (PERMISSION_CODE);
ALTER TABLE SEC_PAGE                     ADD CONSTRAINT UQ_SEC_PAGE_PAGE_CODE           UNIQUE (PAGE_CODE);
ALTER TABLE SEC_REFRESH_TOKEN            ADD CONSTRAINT UQ_SEC_REFRESH_TOKEN_TOKEN      UNIQUE (TOKEN);
ALTER TABLE SEC_PASSWORD_RESET_TOKEN     ADD CONSTRAINT UQ_SEC_PWD_RESET_TOKEN_TOKEN    UNIQUE (TOKEN);
ALTER TABLE SEC_ACCOUNT_ACTIVATION_TOKEN ADD CONSTRAINT UQ_SEC_ACT_TOKEN_TOKEN          UNIQUE (TOKEN);

-- 5c. CHECK CONSTRAINTS
ALTER TABLE SEC_USER_ACCOUNT             ADD CONSTRAINT CHK_SEC_USER_ACCOUNT_ACTIVE_FL  CHECK (IS_ACTIVE_FL IN (0,1));
ALTER TABLE SEC_ROLE                     ADD CONSTRAINT CHK_SEC_ROLE_ACTIVE_FL          CHECK (IS_ACTIVE_FL IN (0,1));
ALTER TABLE SEC_MODULE                   ADD CONSTRAINT CHK_SEC_MODULE_ACTIVE_FL        CHECK (IS_ACTIVE_FL IN (0,1));  -- [v1.3]
ALTER TABLE SEC_PERMISSION               ADD CONSTRAINT CHK_SEC_PERMISSION_ACTIVE_FL    CHECK (IS_ACTIVE_FL IN (0,1));
ALTER TABLE SEC_PERMISSION               ADD CONSTRAINT CHK_SEC_PERMISSION_TYPE         CHECK (PERMISSION_TYPE IN ('VIEW','CREATE','UPDATE','DELETE'));
ALTER TABLE SEC_PAGE                     ADD CONSTRAINT CHK_SEC_PAGE_ACTIVE_FL          CHECK (IS_ACTIVE_FL IN (0,1));
ALTER TABLE SEC_REFRESH_TOKEN            ADD CONSTRAINT CHK_SEC_REFRESH_TOKEN_REVOKED_FL CHECK (REVOKED_FL IN (0,1));
ALTER TABLE SEC_PASSWORD_RESET_TOKEN     ADD CONSTRAINT CHK_SEC_PWD_RESET_TOKEN_USED_FL CHECK (USED_FL IN (0,1));
ALTER TABLE SEC_ACCOUNT_ACTIVATION_TOKEN ADD CONSTRAINT CHK_SEC_ACT_TOKEN_USED_FL       CHECK (USED_FL IN (0,1));

-- 5d. INTRA-MODULE FOREIGN KEYS
ALTER TABLE SEC_PERMISSION               ADD CONSTRAINT FK_SEC_PERMISSION_PAGE    FOREIGN KEY (PAGE_FK)         REFERENCES SEC_PAGE (ID);
ALTER TABLE SEC_PAGE                     ADD CONSTRAINT FK_SEC_PAGE_MODULE        FOREIGN KEY (MODULE_FK)       REFERENCES SEC_MODULE (ID);        -- [v1.3]
ALTER TABLE SEC_PAGE                     ADD CONSTRAINT FK_SEC_PAGE_PARENT        FOREIGN KEY (PARENT_PAGE_FK)  REFERENCES SEC_PAGE (ID);
ALTER TABLE SEC_REFRESH_TOKEN            ADD CONSTRAINT FK_SEC_REFRESH_TOKEN_USER FOREIGN KEY (USER_ACCOUNT_FK) REFERENCES SEC_USER_ACCOUNT (ID);
ALTER TABLE SEC_PASSWORD_RESET_TOKEN     ADD CONSTRAINT FK_SEC_PWD_RESET_TOKEN_USER FOREIGN KEY (USER_ACCOUNT_FK) REFERENCES SEC_USER_ACCOUNT (ID);
ALTER TABLE SEC_ACCOUNT_ACTIVATION_TOKEN ADD CONSTRAINT FK_SEC_ACT_TOKEN_USER     FOREIGN KEY (USER_ACCOUNT_FK) REFERENCES SEC_USER_ACCOUNT (ID);
ALTER TABLE SEC_USER_ROLE                ADD CONSTRAINT FK_SEC_USER_ROLE_USER     FOREIGN KEY (USER_ACCOUNT_FK) REFERENCES SEC_USER_ACCOUNT (ID);
ALTER TABLE SEC_USER_ROLE                ADD CONSTRAINT FK_SEC_USER_ROLE_ROLE     FOREIGN KEY (ROLE_FK)         REFERENCES SEC_ROLE (ID);
ALTER TABLE SEC_ROLE_PERMISSION          ADD CONSTRAINT FK_SEC_ROLE_PERM_ROLE     FOREIGN KEY (ROLE_FK)         REFERENCES SEC_ROLE (ID);
ALTER TABLE SEC_ROLE_PERMISSION          ADD CONSTRAINT FK_SEC_ROLE_PERM_PERM     FOREIGN KEY (PERMISSION_FK)   REFERENCES SEC_PERMISSION (ID);
ALTER TABLE SEC_ROLE_MODULE              ADD CONSTRAINT FK_SEC_ROLE_MODULE_ROLE   FOREIGN KEY (ROLE_FK)         REFERENCES SEC_ROLE (ID);          -- [v1.3]
ALTER TABLE SEC_ROLE_MODULE              ADD CONSTRAINT FK_SEC_ROLE_MODULE_MODULE FOREIGN KEY (MODULE_FK)       REFERENCES SEC_MODULE (ID);        -- [v1.3]

-- Note (RULE-SEC-014): the "no orphan screen permission" invariant — a SEC_ROLE_PERMISSION row is
-- valid only if the role also holds SEC_ROLE_MODULE for the module of that permission's page
-- (SEC_PERMISSION.PAGE_FK -> SEC_PAGE.MODULE_FK) — is a cross-table conditional invariant not
-- expressible as a declarative constraint in PostgreSQL without a trigger/assertion. Per medium-
-- complexity / no-workflow governance it is enforced at the application/service layer (P3.1) and in
-- the UI picker (P2.5). The DDL above supplies the structural backbone (Page.MODULE_FK NOT NULL + SEC_ROLE_MODULE).

-- ============================================================
-- BLOCK 6: TRIGGERS   -- (none)
-- ============================================================

-- ============================================================
-- BLOCK 7: INDEXES
-- ============================================================
CREATE INDEX IDX_SEC_USER_ACCOUNT_STATUS     ON SEC_USER_ACCOUNT (USER_STATUS_ID);
CREATE INDEX IDX_SEC_PERMISSION_PAGE_FK      ON SEC_PERMISSION (PAGE_FK);
CREATE INDEX IDX_SEC_PAGE_MODULE_FK          ON SEC_PAGE (MODULE_FK);                        -- [v1.3]
CREATE INDEX IDX_SEC_PAGE_PARENT_PAGE_FK     ON SEC_PAGE (PARENT_PAGE_FK);
CREATE INDEX IDX_SEC_REFRESH_TOKEN_USER_FK   ON SEC_REFRESH_TOKEN (USER_ACCOUNT_FK);
CREATE INDEX IDX_SEC_PWD_RESET_TOKEN_USER_FK ON SEC_PASSWORD_RESET_TOKEN (USER_ACCOUNT_FK);
CREATE INDEX IDX_SEC_ACT_TOKEN_USER_FK       ON SEC_ACCOUNT_ACTIVATION_TOKEN (USER_ACCOUNT_FK);
CREATE INDEX IDX_SEC_USER_ROLE_ROLE_FK       ON SEC_USER_ROLE (ROLE_FK);
CREATE INDEX IDX_SEC_ROLE_PERM_PERMISSION_FK ON SEC_ROLE_PERMISSION (PERMISSION_FK);
CREATE INDEX IDX_SEC_ROLE_MODULE_MODULE_FK   ON SEC_ROLE_MODULE (MODULE_FK);                 -- [v1.3]

-- ============================================================
-- BLOCK 8: LOOKUP SEED DATA   -- (none — seed owned by SEC-BE phase; LOVs runtime-loaded)
-- ============================================================
