-- V3 — Security (SEC) security-registry seed
-- Source: governance/modules/SEC/packages/backend-execution/SEC-BE/SEC-BE.md (SECURITY SEED DATA REQUIREMENTS)
-- Seeds SEC module, SYS_ADMIN role, 4 admin pages, 16 CORE-9 permissions, Tier-1 + Tier-2 grants.
-- All FKs resolved by natural key (never a hardcoded id). Surrogate PKs from the V2 sequences.

-- 1. SEC_MODULE — module SEC (Tier-1 grantable unit)
INSERT INTO SEC_MODULE (ID, MODULE_CODE, NAME_AR, NAME_EN, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_MODULE'), 'SEC', 'الأمان', 'Security', 1, 'SYSTEM', CURRENT_TIMESTAMP);

-- 2. SEC_ROLE — SYS_ADMIN
INSERT INTO SEC_ROLE (ID, ROLE_CODE, NAME_AR, NAME_EN, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_ROLE'), 'SYS_ADMIN', 'مدير النظام', 'System Administrator', 1, 'SYSTEM', CURRENT_TIMESTAMP);

-- 3. SEC_PAGE — 4 admin screens, all MODULE_FK -> SEC, no parent nav
INSERT INTO SEC_PAGE (ID, PAGE_CODE, NAME_AR, NAME_EN, MODULE_FK, PARENT_PAGE_FK, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PAGE'), 'SEC_USERS', 'إدارة المستخدمين', 'User Management',
        (SELECT ID FROM SEC_MODULE WHERE MODULE_CODE = 'SEC'), NULL, 1, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PAGE (ID, PAGE_CODE, NAME_AR, NAME_EN, MODULE_FK, PARENT_PAGE_FK, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PAGE'), 'SEC_ROLES', 'الأدوار والوحدات والصلاحيات', 'Roles, Modules & Permissions',
        (SELECT ID FROM SEC_MODULE WHERE MODULE_CODE = 'SEC'), NULL, 1, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PAGE (ID, PAGE_CODE, NAME_AR, NAME_EN, MODULE_FK, PARENT_PAGE_FK, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PAGE'), 'SEC_PAGE_REGISTRY', 'سجل الصفحات', 'Page Registry',
        (SELECT ID FROM SEC_MODULE WHERE MODULE_CODE = 'SEC'), NULL, 1, 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PAGE (ID, PAGE_CODE, NAME_AR, NAME_EN, MODULE_FK, PARENT_PAGE_FK, IS_ACTIVE_FL, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PAGE'), 'SEC_MODULES', 'سجل الوحدات', 'Module Registry',
        (SELECT ID FROM SEC_MODULE WHERE MODULE_CODE = 'SEC'), NULL, 1, 'SYSTEM', CURRENT_TIMESTAMP);

-- 4. SEC_PERMISSION — 4 per page (CORE-9). code = PERM_<PAGE_CODE>_<TYPE>; name = <page name> - <TYPE>
--    (matches PermissionGenerationDomainService output so the seed equals runtime generation).
-- SEC_USERS
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_USERS_VIEW', 'VIEW', 'إدارة المستخدمين - VIEW', 'User Management - VIEW', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_USERS'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_USERS_CREATE', 'CREATE', 'إدارة المستخدمين - CREATE', 'User Management - CREATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_USERS'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_USERS_UPDATE', 'UPDATE', 'إدارة المستخدمين - UPDATE', 'User Management - UPDATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_USERS'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_USERS_DELETE', 'DELETE', 'إدارة المستخدمين - DELETE', 'User Management - DELETE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_USERS'), 'SYSTEM', CURRENT_TIMESTAMP);
-- SEC_ROLES
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_ROLES_VIEW', 'VIEW', 'الأدوار والوحدات والصلاحيات - VIEW', 'Roles, Modules & Permissions - VIEW', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_ROLES'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_ROLES_CREATE', 'CREATE', 'الأدوار والوحدات والصلاحيات - CREATE', 'Roles, Modules & Permissions - CREATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_ROLES'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_ROLES_UPDATE', 'UPDATE', 'الأدوار والوحدات والصلاحيات - UPDATE', 'Roles, Modules & Permissions - UPDATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_ROLES'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_ROLES_DELETE', 'DELETE', 'الأدوار والوحدات والصلاحيات - DELETE', 'Roles, Modules & Permissions - DELETE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_ROLES'), 'SYSTEM', CURRENT_TIMESTAMP);
-- SEC_PAGE_REGISTRY
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_PAGE_REGISTRY_VIEW', 'VIEW', 'سجل الصفحات - VIEW', 'Page Registry - VIEW', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_PAGE_REGISTRY'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_PAGE_REGISTRY_CREATE', 'CREATE', 'سجل الصفحات - CREATE', 'Page Registry - CREATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_PAGE_REGISTRY'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_PAGE_REGISTRY_UPDATE', 'UPDATE', 'سجل الصفحات - UPDATE', 'Page Registry - UPDATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_PAGE_REGISTRY'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_PAGE_REGISTRY_DELETE', 'DELETE', 'سجل الصفحات - DELETE', 'Page Registry - DELETE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_PAGE_REGISTRY'), 'SYSTEM', CURRENT_TIMESTAMP);
-- SEC_MODULES
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_MODULES_VIEW', 'VIEW', 'سجل الوحدات - VIEW', 'Module Registry - VIEW', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_MODULES'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_MODULES_CREATE', 'CREATE', 'سجل الوحدات - CREATE', 'Module Registry - CREATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_MODULES'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_MODULES_UPDATE', 'UPDATE', 'سجل الوحدات - UPDATE', 'Module Registry - UPDATE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_MODULES'), 'SYSTEM', CURRENT_TIMESTAMP);
INSERT INTO SEC_PERMISSION (ID, PERMISSION_CODE, PERMISSION_TYPE, NAME_AR, NAME_EN, IS_ACTIVE_FL, PAGE_FK, CREATED_BY, CREATED_AT)
VALUES (nextval('SEQ_SEC_PERMISSION'), 'PERM_SEC_MODULES_DELETE', 'DELETE', 'سجل الوحدات - DELETE', 'Module Registry - DELETE', 1,
        (SELECT ID FROM SEC_PAGE WHERE PAGE_CODE = 'SEC_MODULES'), 'SYSTEM', CURRENT_TIMESTAMP);

-- 5. SEC_ROLE_MODULE — Tier-1 grant (SYS_ADMIN, SEC). MUST precede Tier-2 grants (RULE-SEC-014 prerequisite).
INSERT INTO SEC_ROLE_MODULE (ROLE_FK, MODULE_FK)
VALUES ((SELECT ID FROM SEC_ROLE WHERE ROLE_CODE = 'SYS_ADMIN'),
        (SELECT ID FROM SEC_MODULE WHERE MODULE_CODE = 'SEC'));

-- 6. SEC_ROLE_PERMISSION — Tier-2: grant all 16 SEC screen permissions to SYS_ADMIN.
INSERT INTO SEC_ROLE_PERMISSION (ROLE_FK, PERMISSION_FK)
SELECT (SELECT ID FROM SEC_ROLE WHERE ROLE_CODE = 'SYS_ADMIN'), p.ID
FROM SEC_PERMISSION p
WHERE p.PERMISSION_CODE IN (
  'PERM_SEC_USERS_VIEW', 'PERM_SEC_USERS_CREATE', 'PERM_SEC_USERS_UPDATE', 'PERM_SEC_USERS_DELETE',
  'PERM_SEC_ROLES_VIEW', 'PERM_SEC_ROLES_CREATE', 'PERM_SEC_ROLES_UPDATE', 'PERM_SEC_ROLES_DELETE',
  'PERM_SEC_PAGE_REGISTRY_VIEW', 'PERM_SEC_PAGE_REGISTRY_CREATE', 'PERM_SEC_PAGE_REGISTRY_UPDATE', 'PERM_SEC_PAGE_REGISTRY_DELETE',
  'PERM_SEC_MODULES_VIEW', 'PERM_SEC_MODULES_CREATE', 'PERM_SEC_MODULES_UPDATE', 'PERM_SEC_MODULES_DELETE'
);
