"""
Resolves OpenAPI schema $refs into field lists (FieldSpec), and detects the
recurring response shapes generated by this codebase's stack:

  - the ApiResponse<T> envelope (success/message/data/error/timestamp),
    with the real payload living under "data"
  - Spring's Page<T> serialization (content/totalElements/... with the real
    item type under content.items)
  - a plain array response ("type": "array", "items": {$ref})

Everything here operates purely on the already-loaded OpenAPI document —
no Java source, no network calls beyond what openapi_extractor already did.
"""

from typing import Optional

from extractors import validation_extractor
from models.api_doc_model import FieldSpec

# The envelope is recognised by shape, not by an exact key set: matching the
# full set meant one optional field's absence silently disabled envelope
# detection everywhere -- which is what happened when this platform's
# ApiResponse<T> turned out to carry no `message` field, leaving every
# endpoint's response table showing the wrapper instead of the payload, and
# no shared envelope section at all. Requiring the two fields that DEFINE the
# wrapper, plus at least one of its supporting fields, keeps detection
# resistant to an optional field being added or dropped without matching a
# plain DTO that merely happens to have a `data` property.
ENVELOPE_REQUIRED_KEYS = {"success", "data"}
ENVELOPE_SUPPORTING_KEYS = {"error", "timestamp", "message"}
PAGE_KEYS = {"content", "totalElements"}


def resolve_ref(schema: dict, components: dict) -> tuple[dict, Optional[str]]:
    """Dereference a single-level $ref. Returns (resolved_schema, ref_name_or_None)."""
    if not schema:
        return {}, None
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        return components.get("schemas", {}).get(name, {}), name
    return schema, None


def schema_fields(schema: dict, components: dict, _visited: frozenset = frozenset()) -> list[FieldSpec]:
    """Field list for a resolved-or-ref'd object schema (not array/envelope aware).

    Also recursively expands any field whose own type (or array-item type) is
    itself an object schema with properties -- e.g. a search request's
    `filters: array<ContractFilter>` gets ContractFilter's own field, operator,
    value fields attached to FieldSpec.nested, instead of staying an opaque
    type name. `_visited` guards against self-referential schemas (e.g. a tree
    node's own `children` field) by marking FieldSpec.recursive_ref instead of
    expanding forever.
    """
    resolved, ref_name = resolve_ref(schema, components)
    if ref_name:
        _visited = _visited | {ref_name}
    props = resolved.get("properties", {})
    required_names = set(resolved.get("required", []))

    def _resolve(s: dict) -> tuple[dict, Optional[str]]:
        return resolve_ref(s, components)

    fields = [
        validation_extractor.build_field_spec(name, prop, name in required_names, _resolve)
        for name, prop in props.items()
    ]
    for f in fields:
        _expand_nested(f, components, _visited)
    return fields


def _expand_nested(f: FieldSpec, components: dict, visited: frozenset) -> None:
    schemas = components.get("schemas", {})
    ref_name = f.item_type if f.is_array else f.type
    ref_schema = schemas.get(ref_name) if ref_name else None
    if not ref_schema or not ref_schema.get("properties"):
        return
    if ref_name in visited:
        f.recursive_ref = ref_name
        return
    nested_description = ref_schema.get("description")
    if nested_description and nested_description != f.description:
        f.nested_schema_description = nested_description
    f.nested = schema_fields(ref_schema, components, visited | {ref_name})


def is_envelope_shape(resolved: dict) -> bool:
    props = set(resolved.get("properties", {}).keys())
    return ENVELOPE_REQUIRED_KEYS.issubset(props) and bool(props & ENVELOPE_SUPPORTING_KEYS)


def is_page_shape(resolved: dict) -> bool:
    return PAGE_KEYS.issubset(resolved.get("properties", {}).keys())


def describe_payload(schema: dict, components: dict) -> tuple[list[FieldSpec], bool, bool, Optional[str]]:
    """Unwraps the ApiResponse<T> envelope (if present) and describes the real
    payload underneath: (fields, is_array, is_page, schema_name)."""
    resolved, name = resolve_ref(schema, components)

    if is_envelope_shape(resolved):
        data_schema = resolved["properties"].get("data", {})
        return describe_payload(data_schema, components)

    if resolved.get("type") == "array":
        item_schema = resolved.get("items", {})
        _, item_name = resolve_ref(item_schema, components)
        return schema_fields(item_schema, components), True, False, item_name

    if is_page_shape(resolved):
        content_schema = resolved["properties"].get("content", {})
        item_schema = content_schema.get("items", {})
        _, item_name = resolve_ref(item_schema, components)
        return schema_fields(item_schema, components), False, True, item_name

    return schema_fields(schema, components), False, False, name


def _generic_schema_name(names: list[str]) -> Optional[str]:
    """["PageUserResponse", "PageRoleResponse"] -> "Page<T>". Returns the
    single name unchanged when there is only one, and never invents a base
    when the names share no prefix."""
    if not names:
        return None
    if len(names) == 1:
        return names[0]
    prefix = names[0]
    for name in names[1:]:
        while prefix and not name.startswith(prefix):
            prefix = prefix[:-1]
    return f"{prefix}<T>" if prefix else names[0]


def find_page_envelope(openapi: dict) -> tuple[Optional[str], list[FieldSpec]]:
    """Finds the first Spring Page<T> wrapper schema and describes its own
    bookkeeping fields (totalElements, totalPages, size, number, ...),
    excluding "content" since that's the per-endpoint item list already
    covered by each endpoint's own Response section. Returns (schema_name,
    fields), or (None, []) if no Page-shaped schema exists anywhere."""
    components = openapi.get("components", {})
    schemas = components.get("schemas", {})

    # springdoc emits one Page schema per item type (PageUserResponse,
    # PageActiveSessionResponse, ...). Their bookkeeping fields are identical,
    # so the section is named for the generic wrapper rather than for whichever
    # instantiation happened to come first in the document.
    # ⚠ Sorted, not document order: springdoc emits Page<T>'s properties in an
    # order that differs between JVM runs, and this table is shared bookkeeping
    # with no declaration order a reader would look up. Per-endpoint DTO tables
    # keep document order on purpose -- theirs matches the Java class.
    page_names = sorted(name for name, schema in schemas.items() if is_page_shape(schema))
    generic_name = _generic_schema_name(page_names)

    for name in page_names:
        schema = schemas[name]

        def _resolve(s: dict) -> tuple[dict, Optional[str]]:
            return resolve_ref(s, components)

        props = schema.get("properties", {})
        fields = [
            validation_extractor.build_field_spec(key, props[key], False, _resolve)
            for key in sorted(props)
            if key != "content"
        ]
        return generic_name, fields

    return None, []
