package com.erp.fin.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * API-FIN-023 request body (SVC-API-INT.md): {@code {code, startDate, endDate, periodCount}} —
 * REQ-FIN-031, "a start date, end date and period count". Excludes {fiscalYearPk, statusCode,
 * isActiveFl, audit}: the year is created OPEN and active by its entity defaults, and its periods
 * are generated by the service, never submitted.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Create a fiscal year and generate its periods - "
    + "إنشاء سنة مالية وتوليد فتراتها")
public class FiscalYearCreateRequest {

    @NotBlank(message = "{validation.required}")
    @Size(max = 10, message = "{validation.size}")
    @Schema(description = "Fiscal year code - رمز السنة المالية", example = "2026")
    private String code;

    @NotNull(message = "{validation.required}")
    @Schema(description = "First day of the fiscal year - أول أيام السنة المالية",
        example = "2026-01-01")
    private LocalDate startDate;

    @NotNull(message = "{validation.required}")
    @Schema(description = "Last day of the fiscal year - آخر أيام السنة المالية",
        example = "2026-12-31")
    private LocalDate endDate;

    @NotNull(message = "{validation.required}")
    @Positive(message = "{validation.min}")
    @Schema(description = "Number of periods to generate, each initially Open - عدد الفترات",
        example = "12")
    private Integer periodCount;
}
