-- ============================================================
-- V14 — Drop legacy SECURITY (SEC) module schema
-- The SEC module's Java code (JWT filter, PermissionConstants, controllers/services) was removed for
-- a ground-up rebuild. V2/V3 (and the SEC-registry seed rows added by V7/V9/V10/V13) are never
-- edited per this repo's Flyway policy — this migration forward-drops the tables/sequences they
-- created instead. The new SEC module's own migration will (re)create whatever schema it needs.
-- ============================================================

DROP TABLE IF EXISTS SEC_ROLE_MODULE CASCADE;
DROP TABLE IF EXISTS SEC_ROLE_PERMISSION CASCADE;
DROP TABLE IF EXISTS SEC_USER_ROLE CASCADE;
DROP TABLE IF EXISTS SEC_ACCOUNT_ACTIVATION_TOKEN CASCADE;
DROP TABLE IF EXISTS SEC_PASSWORD_RESET_TOKEN CASCADE;
DROP TABLE IF EXISTS SEC_REFRESH_TOKEN CASCADE;
DROP TABLE IF EXISTS SEC_PERMISSION CASCADE;
DROP TABLE IF EXISTS SEC_PAGE CASCADE;
DROP TABLE IF EXISTS SEC_MODULE CASCADE;
DROP TABLE IF EXISTS SEC_ROLE CASCADE;
DROP TABLE IF EXISTS SEC_USER_ACCOUNT CASCADE;

DROP SEQUENCE IF EXISTS SEQ_SEC_MODULE;
DROP SEQUENCE IF EXISTS SEQ_SEC_ACCOUNT_ACTIVATION_TOKEN;
DROP SEQUENCE IF EXISTS SEQ_SEC_PASSWORD_RESET_TOKEN;
DROP SEQUENCE IF EXISTS SEQ_SEC_REFRESH_TOKEN;
DROP SEQUENCE IF EXISTS SEQ_SEC_PAGE;
DROP SEQUENCE IF EXISTS SEQ_SEC_PERMISSION;
DROP SEQUENCE IF EXISTS SEQ_SEC_ROLE;
DROP SEQUENCE IF EXISTS SEQ_SEC_USER_ACCOUNT;
